// Copyright 2025 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

edition = "2023";

package turboci.orchestrator.v1;

import "google/protobuf/descriptor.proto";
import "turboci/orchestrator/v1/check_state.proto";
import "turboci/orchestrator/v1/identifier_kind.proto";

option go_package = "go.chromium.org/turboci/proto/go/orchestrator/v1;orchestrator";
option java_multiple_files = true;

// FieldOptions are field options which apply to TurboCI message fields.
message FieldOptions {
  // CheckFieldOptions are field options which apply to Check messages.
  message CheckFieldOptions {
    // Indicates that this field is mutable at this CheckState or earlier.
    //
    // We use `editable` here (instead of `mutable`) to avoid name mangling in
    // C++.
    //
    // Example (this indicates that `foo` is mutable during the PLANNING
    // state):
    //   message Check {
    //     string foo = 1 [
    //       (turboci).check.editable = CHECK_STATE_PLANNING
    //     ];
    //   }
    CheckState editable = 1;
  }
  // Field options which apply to Check messages.
  CheckFieldOptions check = 1;

  // IdentifierOptions are field options which apply to message containing
  // Identifiers.
  message IdentifierOptions {
    // Indicates a list of allowed target types for Identifiers within this
    // field. Commonly used with Edge messages, but may also directly annotate
    // Identifier fields.
    //
    // Example:
    //   message Foo {
    //     repeated Edge dependencies = 1 [
    //       (turboci).id.allowed: IDENTIFIER_KIND_STAGE,
    //       (turboci).id.allowed: IDENTIFIER_KIND_CHECK
    //     ];
    //   }
    repeated IdentifierKind allowed = 1;

    // TBD: An option to indicate that Identifiers in this field may refer to
    // nodes in other WorkPlans.
    //
    // bool allow_cross_workplan;
  }
  // Field options which apply to fields containing Identifiers.
  IdentifierOptions id = 2;
}

extend google.protobuf.FieldOptions {
  // TurboCI options for fields.
  FieldOptions turboci = 535801952;
}
