// Copyright 2025 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: turboci/orchestrator/v1/check.proto

package orchestrator

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A Check is a node in a TurboCI graph which ties together:
//   - A named objective of the Workflow (sometimes thought of as a question).
//     For example:
//   - Does source X build for platform Y?
//   - Do these tests built for Y pass when run on Z?
//   - Are the aggregate test results good enough to allow this CL to land?
//   - Options which describe *how* to answer that question. For example:
//   - Which compile targets should be built?
//   - Which test cases should be skipped? Or how many times should retry if
//     they fail?
//   - What test targets should we consider when evaluating the CL?
//   - The answers to that question (i.e. the results of the Check)
//   - Pointers to build artifacts, test results, small bits of workflow
//     specific output which don't fit nicely elsewhere, etc.
//
// Checks are not, themselves, executable, but Stages are the executable nodes
// which operate to plan and resolve Checks.
//
// Options and Result Data are held as protobuf Any messages in Datum objects
// which are children of this Check. Each Datum can be assigned to a different
// security realm (allowing for public/private inputs/outputs for the same
// Check).
//
// See also:
//   - Identifier.Check* (Identifiers for Checks, CheckOptions, etc.)
//   - CheckView (graph view object for a Check and contained messages)
//   - CheckEditView (graph view object for Edits of a Check)
type Check struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The Check's identifier.
	//
	// `identifier.id` is provided by the Stage which creates this Check.
	Identifier *Identifier_Check `protobuf:"bytes,1,opt,name=identifier" json:"identifier,omitempty"`
	// The coarse-grained kind of this Check.
	//
	// Used in UI and Data registration to restrict what data types are usable in
	// `options` and `results.data`.
	//
	// Used as part of a Checks query for a coarse-grained filter.
	Kind *CheckKind `protobuf:"varint,2,opt,name=kind,enum=turboci.orchestrator.v1.CheckKind" json:"kind,omitempty"`
	// The security realm for this Check.
	//
	// If unset on creation, then this will be populated with the realm of the
	// Stage which creates this Check.
	Realm *string `protobuf:"bytes,3,opt,name=realm" json:"realm,omitempty"`
	// The version of this Check.
	//
	// Updated any time fields in this Check change.
	//
	// Note that changing the data in an existing Check Option or a Check Result
	// Datum does not change any field data in this message, and thus will not
	// change this version number (adding a new entry in `options` or in
	// a `Result.data` would, however).
	Version *Revision `protobuf:"bytes,4,opt,name=version" json:"version,omitempty"`
	// The current state of the Check.
	State *CheckState `protobuf:"varint,5,opt,name=state,enum=turboci.orchestrator.v1.CheckState" json:"state,omitempty"`
	// Dependencies on other objects in the graph.
	//
	// All of these dependencies must be satisfied for this Check to be unblocked
	// and advance from the PLANNED to WAITING state.
	//
	// If the dependencies are unsatisfiable, then the Check will be immediately
	// moved to FINAL state and a single Result will be added with type `TBD`.
	//
	// Currently Checks may only depend on other Checks in the same workflow.
	Dependencies []*EdgeGroup `protobuf:"bytes,6,rep,name=dependencies" json:"dependencies,omitempty"`
	// Options form the bulk of 'how to answer this Check'.
	//
	// It is expected that small details (like assignments to specific
	// hardware/devices) will not be present here and will be decided by the
	// Stages which actually produce results for this Check. The balance of what
	// is in the Check options vs. what is in the Stage args is up to the workflow
	// authors. It should be expected that Check options will be consumed by
	// entities external to the Workflow (such as individual developers), and so
	// it's recommended that the option data here be formulated in a way to be
	// useful both in-workflow (to Stages) and to users outside the workflow. If
	// small execution details ARE stored here, it's recommended that they be
	// stored in a secondary data type to make it clear to external users that
	// these details are not intended to be intrinsic for reproduction/replication
	// of the Check results.
	//
	// Orchestrator will ensure that the option types here are registered to be
	// valid for this Check's kind.
	//
	// This field is kept unique by `type_url` and ordered by
	// identifier.options_idx.
	//
	// You can use QueryNodes to get a CheckView which includes this Check and
	// also CheckOptions.
	Options []*Check_OptionRef `protobuf:"bytes,7,rep,name=options" json:"options,omitempty"`
	// The list of Results this Check has.
	//
	// Any time a StageAttempt adds new result *data* for this Check for the first
	// time, a new Result will be added to this list.
	//
	// So, if you had 3 Stages, each with one Stage Attempt, which add result
	// data for this Check, you would see 3 Result messages. Similarly, if you
	// had one Stage with 3 Attempts, all 3 of which add result data for this
	// check, you would see 3 Result messages.
	//
	// Check.version is advanced when a new Result is added, or new data types are
	// added to an existing Result. However, CheckEdits will still be produced for
	// each write to each Result datum.
	Results       []*Check_Result `protobuf:"bytes,8,rep,name=results" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Check) Reset() {
	*x = Check{}
	mi := &file_turboci_orchestrator_v1_check_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Check) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Check) ProtoMessage() {}

func (x *Check) ProtoReflect() protoreflect.Message {
	mi := &file_turboci_orchestrator_v1_check_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Check.ProtoReflect.Descriptor instead.
func (*Check) Descriptor() ([]byte, []int) {
	return file_turboci_orchestrator_v1_check_proto_rawDescGZIP(), []int{0}
}

func (x *Check) GetIdentifier() *Identifier_Check {
	if x != nil {
		return x.Identifier
	}
	return nil
}

func (x *Check) GetKind() CheckKind {
	if x != nil && x.Kind != nil {
		return *x.Kind
	}
	return CheckKind_CHECK_KIND_UNKNOWN
}

func (x *Check) GetRealm() string {
	if x != nil && x.Realm != nil {
		return *x.Realm
	}
	return ""
}

func (x *Check) GetVersion() *Revision {
	if x != nil {
		return x.Version
	}
	return nil
}

func (x *Check) GetState() CheckState {
	if x != nil && x.State != nil {
		return *x.State
	}
	return CheckState_CHECK_STATE_UNKNOWN
}

func (x *Check) GetDependencies() []*EdgeGroup {
	if x != nil {
		return x.Dependencies
	}
	return nil
}

func (x *Check) GetOptions() []*Check_OptionRef {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *Check) GetResults() []*Check_Result {
	if x != nil {
		return x.Results
	}
	return nil
}

// OptionRef is a reference to a CheckOption.
type Check_OptionRef struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The Identifier for the CheckOption, which is a Datum.
	Identifier *Identifier_CheckOption `protobuf:"bytes,1,opt,name=identifier" json:"identifier,omitempty"`
	// The type_url of the data contained for this CheckOption.
	TypeUrl       *string `protobuf:"bytes,2,opt,name=type_url,json=typeUrl" json:"type_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Check_OptionRef) Reset() {
	*x = Check_OptionRef{}
	mi := &file_turboci_orchestrator_v1_check_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Check_OptionRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Check_OptionRef) ProtoMessage() {}

func (x *Check_OptionRef) ProtoReflect() protoreflect.Message {
	mi := &file_turboci_orchestrator_v1_check_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Check_OptionRef.ProtoReflect.Descriptor instead.
func (*Check_OptionRef) Descriptor() ([]byte, []int) {
	return file_turboci_orchestrator_v1_check_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Check_OptionRef) GetIdentifier() *Identifier_CheckOption {
	if x != nil {
		return x.Identifier
	}
	return nil
}

func (x *Check_OptionRef) GetTypeUrl() string {
	if x != nil && x.TypeUrl != nil {
		return *x.TypeUrl
	}
	return ""
}

// A Result is a container of result data for a Check.
//
// Results belong to exactly one Actor (usually a StageAttempt), and any given
// Actor may only have one Result per Check.
//
// A Check may have multiple Results, and each Result may have
// multiple pieces of result data. This could occur when multiple Stages all
// contribute results to the same Check (e.g. sharding, multiple executions,
// etc.).
type Check_Result struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The entity which created this Result.
	Owner *Actor `protobuf:"bytes,1,opt,name=owner" json:"owner,omitempty"`
	// The time at which this Result was created.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
	// Data form the bulk of the result.
	//
	// NOTE: Most data should be stored in ResultDB via turboci.ResultStorage.
	//
	// This field is kept unique by `type_url` and ordered by
	// identifier.options_idx.
	//
	// Orchestrator will ensure that the option types here are registered to be
	// valid for this Result's kind.
	//
	// You can use QueryNodes to get a CheckView which includes this Check and
	// also Result Data.
	Data []*Check_Result_ResultDatumRef `protobuf:"bytes,3,rep,name=data" json:"data,omitempty"`
	// The time at which this Result is finalized.
	//
	// This is set when:
	//   - A StageAttempt `owner` ends (becomes COMPLETE or INCOMPLETE).
	//   - The `owner` explicitly indicates that their results are final.
	//   - The Check advances to the FINAL state.
	FinalizedAt   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=finalized_at,json=finalizedAt" json:"finalized_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Check_Result) Reset() {
	*x = Check_Result{}
	mi := &file_turboci_orchestrator_v1_check_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Check_Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Check_Result) ProtoMessage() {}

func (x *Check_Result) ProtoReflect() protoreflect.Message {
	mi := &file_turboci_orchestrator_v1_check_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Check_Result.ProtoReflect.Descriptor instead.
func (*Check_Result) Descriptor() ([]byte, []int) {
	return file_turboci_orchestrator_v1_check_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Check_Result) GetOwner() *Actor {
	if x != nil {
		return x.Owner
	}
	return nil
}

func (x *Check_Result) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Check_Result) GetData() []*Check_Result_ResultDatumRef {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Check_Result) GetFinalizedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FinalizedAt
	}
	return nil
}

// ResultDatumRef is a reference to a CheckResultDatum.
type Check_Result_ResultDatumRef struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The Identifier for the CheckResultDatum.
	Identifier *Identifier_CheckResultDatum `protobuf:"bytes,1,opt,name=identifier" json:"identifier,omitempty"`
	// The type_url of the data contained for this CheckResultDatum.
	TypeUrl       *string `protobuf:"bytes,2,opt,name=type_url,json=typeUrl" json:"type_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Check_Result_ResultDatumRef) Reset() {
	*x = Check_Result_ResultDatumRef{}
	mi := &file_turboci_orchestrator_v1_check_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Check_Result_ResultDatumRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Check_Result_ResultDatumRef) ProtoMessage() {}

func (x *Check_Result_ResultDatumRef) ProtoReflect() protoreflect.Message {
	mi := &file_turboci_orchestrator_v1_check_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Check_Result_ResultDatumRef.ProtoReflect.Descriptor instead.
func (*Check_Result_ResultDatumRef) Descriptor() ([]byte, []int) {
	return file_turboci_orchestrator_v1_check_proto_rawDescGZIP(), []int{0, 1, 0}
}

func (x *Check_Result_ResultDatumRef) GetIdentifier() *Identifier_CheckResultDatum {
	if x != nil {
		return x.Identifier
	}
	return nil
}

func (x *Check_Result_ResultDatumRef) GetTypeUrl() string {
	if x != nil && x.TypeUrl != nil {
		return *x.TypeUrl
	}
	return ""
}

var File_turboci_orchestrator_v1_check_proto protoreflect.FileDescriptor

const file_turboci_orchestrator_v1_check_proto_rawDesc = "" +
	"\n" +
	"#turboci/orchestrator/v1/check.proto\x12\x17turboci.orchestrator.v1\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a#turboci/orchestrator/v1/actor.proto\x1a(turboci/orchestrator/v1/check_kind.proto\x1a)turboci/orchestrator/v1/check_state.proto\x1a(turboci/orchestrator/v1/edge_group.proto\x1a+turboci/orchestrator/v1/field_options.proto\x1a(turboci/orchestrator/v1/identifier.proto\x1a&turboci/orchestrator/v1/revision.proto\"\xac\b\n" +
	"\x05Check\x12N\n" +
	"\n" +
	"identifier\x18\x01 \x01(\v2).turboci.orchestrator.v1.Identifier.CheckB\x03\xe0A\x05R\n" +
	"identifier\x12;\n" +
	"\x04kind\x18\x02 \x01(\x0e2\".turboci.orchestrator.v1.CheckKindB\x03\xe0A\x05R\x04kind\x12\x19\n" +
	"\x05realm\x18\x03 \x01(\tB\x03\xe0A\x05R\x05realm\x12;\n" +
	"\aversion\x18\x04 \x01(\v2!.turboci.orchestrator.v1.RevisionR\aversion\x129\n" +
	"\x05state\x18\x05 \x01(\x0e2#.turboci.orchestrator.v1.CheckStateR\x05state\x12W\n" +
	"\fdependencies\x18\x06 \x03(\v2\".turboci.orchestrator.v1.EdgeGroupB\x0f\x82\x86\xf6\xfb\x0f\t\n" +
	"\x02\b\n" +
	"\x12\x03\n" +
	"\x01\x02R\fdependencies\x12N\n" +
	"\aoptions\x18\a \x03(\v2(.turboci.orchestrator.v1.Check.OptionRefB\n" +
	"\x82\x86\xf6\xfb\x0f\x04\n" +
	"\x02\b\n" +
	"R\aoptions\x12N\n" +
	"\aresults\x18\b \x03(\v2%.turboci.orchestrator.v1.Check.ResultB\r\xe0A\x03\x82\x86\xf6\xfb\x0f\x04\n" +
	"\x02\b\x1eR\aresults\x1aw\n" +
	"\tOptionRef\x12O\n" +
	"\n" +
	"identifier\x18\x01 \x01(\v2/.turboci.orchestrator.v1.Identifier.CheckOptionR\n" +
	"identifier\x12\x19\n" +
	"\btype_url\x18\x02 \x01(\tR\atypeUrl\x1a\x90\x03\n" +
	"\x06Result\x129\n" +
	"\x05owner\x18\x01 \x01(\v2\x1e.turboci.orchestrator.v1.ActorB\x03\xe0A\x03R\x05owner\x12>\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\tcreatedAt\x12H\n" +
	"\x04data\x18\x03 \x03(\v24.turboci.orchestrator.v1.Check.Result.ResultDatumRefR\x04data\x12=\n" +
	"\ffinalized_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\vfinalizedAt\x1a\x81\x01\n" +
	"\x0eResultDatumRef\x12T\n" +
	"\n" +
	"identifier\x18\x01 \x01(\v24.turboci.orchestrator.v1.Identifier.CheckResultDatumR\n" +
	"identifier\x12\x19\n" +
	"\btype_url\x18\x02 \x01(\tR\atypeUrlBAP\x01Z=go.chromium.org/turboci/proto/go/orchestrator/v1;orchestratorb\beditionsp\xe8\a"

var (
	file_turboci_orchestrator_v1_check_proto_rawDescOnce sync.Once
	file_turboci_orchestrator_v1_check_proto_rawDescData []byte
)

func file_turboci_orchestrator_v1_check_proto_rawDescGZIP() []byte {
	file_turboci_orchestrator_v1_check_proto_rawDescOnce.Do(func() {
		file_turboci_orchestrator_v1_check_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_turboci_orchestrator_v1_check_proto_rawDesc), len(file_turboci_orchestrator_v1_check_proto_rawDesc)))
	})
	return file_turboci_orchestrator_v1_check_proto_rawDescData
}

var file_turboci_orchestrator_v1_check_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_turboci_orchestrator_v1_check_proto_goTypes = []any{
	(*Check)(nil),                       // 0: turboci.orchestrator.v1.Check
	(*Check_OptionRef)(nil),             // 1: turboci.orchestrator.v1.Check.OptionRef
	(*Check_Result)(nil),                // 2: turboci.orchestrator.v1.Check.Result
	(*Check_Result_ResultDatumRef)(nil), // 3: turboci.orchestrator.v1.Check.Result.ResultDatumRef
	(*Identifier_Check)(nil),            // 4: turboci.orchestrator.v1.Identifier.Check
	(CheckKind)(0),                      // 5: turboci.orchestrator.v1.CheckKind
	(*Revision)(nil),                    // 6: turboci.orchestrator.v1.Revision
	(CheckState)(0),                     // 7: turboci.orchestrator.v1.CheckState
	(*EdgeGroup)(nil),                   // 8: turboci.orchestrator.v1.EdgeGroup
	(*Identifier_CheckOption)(nil),      // 9: turboci.orchestrator.v1.Identifier.CheckOption
	(*Actor)(nil),                       // 10: turboci.orchestrator.v1.Actor
	(*timestamppb.Timestamp)(nil),       // 11: google.protobuf.Timestamp
	(*Identifier_CheckResultDatum)(nil), // 12: turboci.orchestrator.v1.Identifier.CheckResultDatum
}
var file_turboci_orchestrator_v1_check_proto_depIdxs = []int32{
	4,  // 0: turboci.orchestrator.v1.Check.identifier:type_name -> turboci.orchestrator.v1.Identifier.Check
	5,  // 1: turboci.orchestrator.v1.Check.kind:type_name -> turboci.orchestrator.v1.CheckKind
	6,  // 2: turboci.orchestrator.v1.Check.version:type_name -> turboci.orchestrator.v1.Revision
	7,  // 3: turboci.orchestrator.v1.Check.state:type_name -> turboci.orchestrator.v1.CheckState
	8,  // 4: turboci.orchestrator.v1.Check.dependencies:type_name -> turboci.orchestrator.v1.EdgeGroup
	1,  // 5: turboci.orchestrator.v1.Check.options:type_name -> turboci.orchestrator.v1.Check.OptionRef
	2,  // 6: turboci.orchestrator.v1.Check.results:type_name -> turboci.orchestrator.v1.Check.Result
	9,  // 7: turboci.orchestrator.v1.Check.OptionRef.identifier:type_name -> turboci.orchestrator.v1.Identifier.CheckOption
	10, // 8: turboci.orchestrator.v1.Check.Result.owner:type_name -> turboci.orchestrator.v1.Actor
	11, // 9: turboci.orchestrator.v1.Check.Result.created_at:type_name -> google.protobuf.Timestamp
	3,  // 10: turboci.orchestrator.v1.Check.Result.data:type_name -> turboci.orchestrator.v1.Check.Result.ResultDatumRef
	11, // 11: turboci.orchestrator.v1.Check.Result.finalized_at:type_name -> google.protobuf.Timestamp
	12, // 12: turboci.orchestrator.v1.Check.Result.ResultDatumRef.identifier:type_name -> turboci.orchestrator.v1.Identifier.CheckResultDatum
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_turboci_orchestrator_v1_check_proto_init() }
func file_turboci_orchestrator_v1_check_proto_init() {
	if File_turboci_orchestrator_v1_check_proto != nil {
		return
	}
	file_turboci_orchestrator_v1_actor_proto_init()
	file_turboci_orchestrator_v1_check_kind_proto_init()
	file_turboci_orchestrator_v1_check_state_proto_init()
	file_turboci_orchestrator_v1_edge_group_proto_init()
	file_turboci_orchestrator_v1_field_options_proto_init()
	file_turboci_orchestrator_v1_identifier_proto_init()
	file_turboci_orchestrator_v1_revision_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_turboci_orchestrator_v1_check_proto_rawDesc), len(file_turboci_orchestrator_v1_check_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_turboci_orchestrator_v1_check_proto_goTypes,
		DependencyIndexes: file_turboci_orchestrator_v1_check_proto_depIdxs,
		MessageInfos:      file_turboci_orchestrator_v1_check_proto_msgTypes,
	}.Build()
	File_turboci_orchestrator_v1_check_proto = out.File
	file_turboci_orchestrator_v1_check_proto_goTypes = nil
	file_turboci_orchestrator_v1_check_proto_depIdxs = nil
}
