// Copyright 2025 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: turboci/orchestrator/v1/identifier.proto

package orchestrator

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A generic identifier that can be used to identify all TurboCI graph nodes.
//
// Within some message (e.g. Check), you may see usage of Identifier.X directly
// to indicate that the Identifier there can only be a single kind. Having the
// Identifier container, however, allows for generic structures like Edge which
// can refer to multiple kinds of nodes in different contexts.
//
// No string identifiers here may contain a colon.
type Identifier struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The type of this Identifier.
	//
	// This should be kept in sync with the `IdentifierKind` enum.
	//
	// Types that are valid to be assigned to Type:
	//
	//	*Identifier_WorkPlan_
	//	*Identifier_Check_
	//	*Identifier_CheckOption_
	//	*Identifier_CheckResultDatum_
	//	*Identifier_CheckEdit_
	//	*Identifier_CheckEditOption_
	//	*Identifier_Stage_
	//	*Identifier_StageAttempt_
	//	*Identifier_StageEdit_
	Type          isIdentifier_Type `protobuf_oneof:"type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Identifier) Reset() {
	*x = Identifier{}
	mi := &file_turboci_orchestrator_v1_identifier_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Identifier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Identifier) ProtoMessage() {}

func (x *Identifier) ProtoReflect() protoreflect.Message {
	mi := &file_turboci_orchestrator_v1_identifier_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Identifier.ProtoReflect.Descriptor instead.
func (*Identifier) Descriptor() ([]byte, []int) {
	return file_turboci_orchestrator_v1_identifier_proto_rawDescGZIP(), []int{0}
}

func (x *Identifier) GetType() isIdentifier_Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *Identifier) GetWorkPlan() *Identifier_WorkPlan {
	if x != nil {
		if x, ok := x.Type.(*Identifier_WorkPlan_); ok {
			return x.WorkPlan
		}
	}
	return nil
}

func (x *Identifier) GetCheck() *Identifier_Check {
	if x != nil {
		if x, ok := x.Type.(*Identifier_Check_); ok {
			return x.Check
		}
	}
	return nil
}

func (x *Identifier) GetCheckOption() *Identifier_CheckOption {
	if x != nil {
		if x, ok := x.Type.(*Identifier_CheckOption_); ok {
			return x.CheckOption
		}
	}
	return nil
}

func (x *Identifier) GetCheckResultDatum() *Identifier_CheckResultDatum {
	if x != nil {
		if x, ok := x.Type.(*Identifier_CheckResultDatum_); ok {
			return x.CheckResultDatum
		}
	}
	return nil
}

func (x *Identifier) GetCheckEdit() *Identifier_CheckEdit {
	if x != nil {
		if x, ok := x.Type.(*Identifier_CheckEdit_); ok {
			return x.CheckEdit
		}
	}
	return nil
}

func (x *Identifier) GetCheckEditOption() *Identifier_CheckEditOption {
	if x != nil {
		if x, ok := x.Type.(*Identifier_CheckEditOption_); ok {
			return x.CheckEditOption
		}
	}
	return nil
}

func (x *Identifier) GetStage() *Identifier_Stage {
	if x != nil {
		if x, ok := x.Type.(*Identifier_Stage_); ok {
			return x.Stage
		}
	}
	return nil
}

func (x *Identifier) GetStageAttempt() *Identifier_StageAttempt {
	if x != nil {
		if x, ok := x.Type.(*Identifier_StageAttempt_); ok {
			return x.StageAttempt
		}
	}
	return nil
}

func (x *Identifier) GetStageEdit() *Identifier_StageEdit {
	if x != nil {
		if x, ok := x.Type.(*Identifier_StageEdit_); ok {
			return x.StageEdit
		}
	}
	return nil
}

type isIdentifier_Type interface {
	isIdentifier_Type()
}

type Identifier_WorkPlan_ struct {
	// A whole WorkPlan.
	WorkPlan *Identifier_WorkPlan `protobuf:"bytes,1,opt,name=work_plan,json=workPlan,oneof"`
}

type Identifier_Check_ struct {
	// A Check within a WorkPlan.
	Check *Identifier_Check `protobuf:"bytes,2,opt,name=check,oneof"`
}

type Identifier_CheckOption_ struct {
	// Option data for a Check.
	CheckOption *Identifier_CheckOption `protobuf:"bytes,3,opt,name=check_option,json=checkOption,oneof"`
}

type Identifier_CheckResultDatum_ struct {
	// Data associated with a particular result in a Check.
	CheckResultDatum *Identifier_CheckResultDatum `protobuf:"bytes,4,opt,name=check_result_datum,json=checkResultDatum,oneof"`
}

type Identifier_CheckEdit_ struct {
	// An edit to a Check.
	CheckEdit *Identifier_CheckEdit `protobuf:"bytes,5,opt,name=check_edit,json=checkEdit,oneof"`
}

type Identifier_CheckEditOption_ struct {
	// Option data for an edit to a Check.
	CheckEditOption *Identifier_CheckEditOption `protobuf:"bytes,6,opt,name=check_edit_option,json=checkEditOption,oneof"`
}

type Identifier_Stage_ struct {
	// A Stage within a WorkPlan.
	Stage *Identifier_Stage `protobuf:"bytes,7,opt,name=stage,oneof"`
}

type Identifier_StageAttempt_ struct {
	// A specific attempt at a Stage.
	StageAttempt *Identifier_StageAttempt `protobuf:"bytes,8,opt,name=stage_attempt,json=stageAttempt,oneof"`
}

type Identifier_StageEdit_ struct {
	// An edit to a Stage.
	StageEdit *Identifier_StageEdit `protobuf:"bytes,9,opt,name=stage_edit,json=stageEdit,oneof"`
}

func (*Identifier_WorkPlan_) isIdentifier_Type() {}

func (*Identifier_Check_) isIdentifier_Type() {}

func (*Identifier_CheckOption_) isIdentifier_Type() {}

func (*Identifier_CheckResultDatum_) isIdentifier_Type() {}

func (*Identifier_CheckEdit_) isIdentifier_Type() {}

func (*Identifier_CheckEditOption_) isIdentifier_Type() {}

func (*Identifier_Stage_) isIdentifier_Type() {}

func (*Identifier_StageAttempt_) isIdentifier_Type() {}

func (*Identifier_StageEdit_) isIdentifier_Type() {}

// Identifies an entire TurboCI WorkPlan.
//
// Serialized as JUST "<id>", but this must start with "L".
//
// The portion of `id` after "L" will be an integer.
type Identifier_WorkPlan struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Globally unique identifier for this WorkPlan.
	//
	// Has the form "L<digits>" and is generated by the TurboCI service.
	Id            *string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Identifier_WorkPlan) Reset() {
	*x = Identifier_WorkPlan{}
	mi := &file_turboci_orchestrator_v1_identifier_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Identifier_WorkPlan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Identifier_WorkPlan) ProtoMessage() {}

func (x *Identifier_WorkPlan) ProtoReflect() protoreflect.Message {
	mi := &file_turboci_orchestrator_v1_identifier_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Identifier_WorkPlan.ProtoReflect.Descriptor instead.
func (*Identifier_WorkPlan) Descriptor() ([]byte, []int) {
	return file_turboci_orchestrator_v1_identifier_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Identifier_WorkPlan) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

// Identifies a Check within a WorkPlan.
//
// Serialized as "<work_plan>:C<id>".
//
// E.g. "<work_plan.id>:C<id>"
type Identifier_Check struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The WorkPlan this check is scoped to.
	WorkPlan *Identifier_WorkPlan `protobuf:"bytes,1,opt,name=work_plan,json=workPlan" json:"work_plan,omitempty"`
	// An opaque identifier unique within this WorkPlan.
	//
	// Provided by the Stage which added this Check.
	//
	// TBD: Specify the format of this ID as regex - it should have a maximum
	// length and not be allowed to contain a colon at the very least.
	Id            *string `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Identifier_Check) Reset() {
	*x = Identifier_Check{}
	mi := &file_turboci_orchestrator_v1_identifier_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Identifier_Check) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Identifier_Check) ProtoMessage() {}

func (x *Identifier_Check) ProtoReflect() protoreflect.Message {
	mi := &file_turboci_orchestrator_v1_identifier_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Identifier_Check.ProtoReflect.Descriptor instead.
func (*Identifier_Check) Descriptor() ([]byte, []int) {
	return file_turboci_orchestrator_v1_identifier_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Identifier_Check) GetWorkPlan() *Identifier_WorkPlan {
	if x != nil {
		return x.WorkPlan
	}
	return nil
}

func (x *Identifier_Check) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

// Identifies an option associated with a Check within a WorkPlan.
//
// Serializes as "<check>:O<idx>".
//
// E.g. "<check.work_plan.id>:C<check.id>:O<idx>"
//
// A CheckOption is a single `Datum`.
//
// This is separate from `Check` because it may reside in a different realm
// than the Check itself.
type Identifier_CheckOption struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The check that this option belongs to.
	Check *Identifier_Check `protobuf:"bytes,1,opt,name=check" json:"check,omitempty"`
	// The 1-based index of this datum within the Check.option list.
	OptionsIdx    *int32 `protobuf:"varint,2,opt,name=options_idx,json=optionsIdx" json:"options_idx,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Identifier_CheckOption) Reset() {
	*x = Identifier_CheckOption{}
	mi := &file_turboci_orchestrator_v1_identifier_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Identifier_CheckOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Identifier_CheckOption) ProtoMessage() {}

func (x *Identifier_CheckOption) ProtoReflect() protoreflect.Message {
	mi := &file_turboci_orchestrator_v1_identifier_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Identifier_CheckOption.ProtoReflect.Descriptor instead.
func (*Identifier_CheckOption) Descriptor() ([]byte, []int) {
	return file_turboci_orchestrator_v1_identifier_proto_rawDescGZIP(), []int{0, 2}
}

func (x *Identifier_CheckOption) GetCheck() *Identifier_Check {
	if x != nil {
		return x.Check
	}
	return nil
}

func (x *Identifier_CheckOption) GetOptionsIdx() int32 {
	if x != nil && x.OptionsIdx != nil {
		return *x.OptionsIdx
	}
	return 0
}

// Identifies a Datum for a Check's Result within a WorkPlan.
//
// Serialized as "<check_result>:R<results_idx>:D<results_data_idx>".
//
// E.g. "<check.work_plan.id>:C<check.id>:R<results_idx>:D<results_data_idx>"
//
// This is separate from `Check` because it may reside in a different realm
// than the Check itself.
type Identifier_CheckResultDatum struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The check that this result belongs to.
	Check *Identifier_Check `protobuf:"bytes,1,opt,name=check" json:"check,omitempty"`
	// The 1-based index of this result within the Check.results list.
	ResultsIdx *int32 `protobuf:"varint,2,opt,name=results_idx,json=resultsIdx" json:"results_idx,omitempty"`
	// The 1-based index of this datum within the Check.Result.data list.
	ResultsDataIdx *int32 `protobuf:"varint,3,opt,name=results_data_idx,json=resultsDataIdx" json:"results_data_idx,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Identifier_CheckResultDatum) Reset() {
	*x = Identifier_CheckResultDatum{}
	mi := &file_turboci_orchestrator_v1_identifier_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Identifier_CheckResultDatum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Identifier_CheckResultDatum) ProtoMessage() {}

func (x *Identifier_CheckResultDatum) ProtoReflect() protoreflect.Message {
	mi := &file_turboci_orchestrator_v1_identifier_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Identifier_CheckResultDatum.ProtoReflect.Descriptor instead.
func (*Identifier_CheckResultDatum) Descriptor() ([]byte, []int) {
	return file_turboci_orchestrator_v1_identifier_proto_rawDescGZIP(), []int{0, 3}
}

func (x *Identifier_CheckResultDatum) GetCheck() *Identifier_Check {
	if x != nil {
		return x.Check
	}
	return nil
}

func (x *Identifier_CheckResultDatum) GetResultsIdx() int32 {
	if x != nil && x.ResultsIdx != nil {
		return *x.ResultsIdx
	}
	return 0
}

func (x *Identifier_CheckResultDatum) GetResultsDataIdx() int32 {
	if x != nil && x.ResultsDataIdx != nil {
		return *x.ResultsDataIdx
	}
	return 0
}

// Identifies a CheckEdit within a WorkPlan.
//
// Serialized as "<check>:E<version>".
//
// E.g.
// "L<check.work_plan.id>:C<check.id>:ET<version.ts.seconds>/<version.ts.nanos>"
type Identifier_CheckEdit struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The check that this edit belongs to.
	Check *Identifier_Check `protobuf:"bytes,1,opt,name=check" json:"check,omitempty"`
	// The version of the Check at the time this edit was made.
	Version       *Revision `protobuf:"bytes,2,opt,name=version" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Identifier_CheckEdit) Reset() {
	*x = Identifier_CheckEdit{}
	mi := &file_turboci_orchestrator_v1_identifier_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Identifier_CheckEdit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Identifier_CheckEdit) ProtoMessage() {}

func (x *Identifier_CheckEdit) ProtoReflect() protoreflect.Message {
	mi := &file_turboci_orchestrator_v1_identifier_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Identifier_CheckEdit.ProtoReflect.Descriptor instead.
func (*Identifier_CheckEdit) Descriptor() ([]byte, []int) {
	return file_turboci_orchestrator_v1_identifier_proto_rawDescGZIP(), []int{0, 4}
}

func (x *Identifier_CheckEdit) GetCheck() *Identifier_Check {
	if x != nil {
		return x.Check
	}
	return nil
}

func (x *Identifier_CheckEdit) GetVersion() *Revision {
	if x != nil {
		return x.Version
	}
	return nil
}

// Identifies a CheckEditOption within a WorkPlan.
//
// Serialized as "<check_edit>:D<idx>".
//
// E.g.
// "L<check_edit.check.work_plan.id>:C<check_edit.check.id>:ET<check_edit.version.ts.seconds>/<check_edit.version.ts.nanos>:D<idx>"
//
// This is separate from `CheckEdit` because it may reside in a different
// realm than the CheckEdit itself.
type Identifier_CheckEditOption struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The check that this edit belongs to.
	CheckEdit *Identifier_CheckEdit `protobuf:"bytes,1,opt,name=check_edit,json=checkEdit" json:"check_edit,omitempty"`
	// The 1-based index of this datum within the Edit.check.delta.options
	// list.
	CheckDeltaOptionsIdx *int32 `protobuf:"varint,2,opt,name=check_delta_options_idx,json=checkDeltaOptionsIdx" json:"check_delta_options_idx,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Identifier_CheckEditOption) Reset() {
	*x = Identifier_CheckEditOption{}
	mi := &file_turboci_orchestrator_v1_identifier_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Identifier_CheckEditOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Identifier_CheckEditOption) ProtoMessage() {}

func (x *Identifier_CheckEditOption) ProtoReflect() protoreflect.Message {
	mi := &file_turboci_orchestrator_v1_identifier_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Identifier_CheckEditOption.ProtoReflect.Descriptor instead.
func (*Identifier_CheckEditOption) Descriptor() ([]byte, []int) {
	return file_turboci_orchestrator_v1_identifier_proto_rawDescGZIP(), []int{0, 5}
}

func (x *Identifier_CheckEditOption) GetCheckEdit() *Identifier_CheckEdit {
	if x != nil {
		return x.CheckEdit
	}
	return nil
}

func (x *Identifier_CheckEditOption) GetCheckDeltaOptionsIdx() int32 {
	if x != nil && x.CheckDeltaOptionsIdx != nil {
		return *x.CheckDeltaOptionsIdx
	}
	return 0
}

// Identifies a Stage within a WorkPlan.
//
// <id> MUST start with either "S" or "N".
//
// N-flavored Stages have additional synchronization with the WorkNodes
// table. These will have digits following the `N` prefix.
//
// S-flavored Stages don't have any special treatment and do not have a
// restricted suffix after the `S` prefix (other than the usual prohibition of
// the use of colons).
//
// Serialized as "<work_plan>:<id>" (note lack of prefix before <id>).
//
// E.g. "L<work_plan.id>:<id>"
//
// We considered adding a boolean like `is_worknode` to indicate the
// underlying nature of this Stage, but felt that it would lead to more
// complexity at callsites, because it would allow some invalid expressions
// like:
//   - `{work_plan: ..., id: "123"}` referring to a WorkNode.
//   - `{work_plan: ..., is_worknode: true, id: "abc"}` referring to a Stage.
//
// Instead, the N/S prefix is part of the `id` field - but this means that
// Identifier.Stage is unsatisfyingly unlike Identifier.Check. The main
// difference is that for the new Stage API `id` here can be an intentionally
// meaningful string (like Check.id), whereas in the WorkNode API it's an
// assigned integer. We strongly want to keep 1:1 Stage:WorkNode mapping, so
// this compromise allows that with hopefully not-too-much complexity overhead
// for non-WorkNode stages.
type Identifier_Stage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The WorkPlan that this Stage belongs to.
	WorkPlan *Identifier_WorkPlan `protobuf:"bytes,1,opt,name=work_plan,json=workPlan" json:"work_plan,omitempty"`
	// An opaque identifier unique within this WorkPlan.
	//
	// For Android WorkNodes, this will be "N" followed by a decimal integer.
	// Otherwise this will start with "S" and have a suffix supplied by the
	// Stage which added this.
	//
	// If the type of this Stage is WorkNode, then this MAY start with "N"
	// followed by a decimal representation of an integer. If this is the case,
	// then this Stage has special handling in the graph service to keep it
	// synchronized with its identical twin in the WorkNodes table.
	//
	// Otherwise this MUST start with "S".
	Id            *string `protobuf:"bytes,3,opt,name=id" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Identifier_Stage) Reset() {
	*x = Identifier_Stage{}
	mi := &file_turboci_orchestrator_v1_identifier_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Identifier_Stage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Identifier_Stage) ProtoMessage() {}

func (x *Identifier_Stage) ProtoReflect() protoreflect.Message {
	mi := &file_turboci_orchestrator_v1_identifier_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Identifier_Stage.ProtoReflect.Descriptor instead.
func (*Identifier_Stage) Descriptor() ([]byte, []int) {
	return file_turboci_orchestrator_v1_identifier_proto_rawDescGZIP(), []int{0, 6}
}

func (x *Identifier_Stage) GetWorkPlan() *Identifier_WorkPlan {
	if x != nil {
		return x.WorkPlan
	}
	return nil
}

func (x *Identifier_Stage) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

// Identifies a Stage Attempt within a Stage.
//
// Note that Stage.Attempt is embedded within a Stage, but we need a reference
// to it from various places (e.g. Check and Stage Edits), so it has an
// Identifier here. Most users will use Stage instead.
//
// Serialized as "<stage>:A<attempts_idx>".
//
// E.g. "<stage.work_plan.id>:<stage.id>:A<attempts_idx>"
type Identifier_StageAttempt struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The Stage that this Stage Attempt belongs to.
	Stage *Identifier_Stage `protobuf:"bytes,1,opt,name=stage" json:"stage,omitempty"`
	// The 1-based index of this attempt within the Stage.attempts list.
	AttemptsIdx   *int32 `protobuf:"varint,2,opt,name=attempts_idx,json=attemptsIdx" json:"attempts_idx,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Identifier_StageAttempt) Reset() {
	*x = Identifier_StageAttempt{}
	mi := &file_turboci_orchestrator_v1_identifier_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Identifier_StageAttempt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Identifier_StageAttempt) ProtoMessage() {}

func (x *Identifier_StageAttempt) ProtoReflect() protoreflect.Message {
	mi := &file_turboci_orchestrator_v1_identifier_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Identifier_StageAttempt.ProtoReflect.Descriptor instead.
func (*Identifier_StageAttempt) Descriptor() ([]byte, []int) {
	return file_turboci_orchestrator_v1_identifier_proto_rawDescGZIP(), []int{0, 7}
}

func (x *Identifier_StageAttempt) GetStage() *Identifier_Stage {
	if x != nil {
		return x.Stage
	}
	return nil
}

func (x *Identifier_StageAttempt) GetAttemptsIdx() int32 {
	if x != nil && x.AttemptsIdx != nil {
		return *x.AttemptsIdx
	}
	return 0
}

// Identifies a Stage Edit within a WorkPlan.
//
// Serialized as "<stage>:E<version>".
//
// E.g.
// "<stage.work_plan.id>:<stage.id>:ET<version.ts.seconds>/<version.ts.nanos>"
type Identifier_StageEdit struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The stage that this edit belongs to.
	Stage *Identifier_Stage `protobuf:"bytes,1,opt,name=stage" json:"stage,omitempty"`
	// The version of the Stage at the time this edit was made.
	Version       *Revision `protobuf:"bytes,2,opt,name=version" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Identifier_StageEdit) Reset() {
	*x = Identifier_StageEdit{}
	mi := &file_turboci_orchestrator_v1_identifier_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Identifier_StageEdit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Identifier_StageEdit) ProtoMessage() {}

func (x *Identifier_StageEdit) ProtoReflect() protoreflect.Message {
	mi := &file_turboci_orchestrator_v1_identifier_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Identifier_StageEdit.ProtoReflect.Descriptor instead.
func (*Identifier_StageEdit) Descriptor() ([]byte, []int) {
	return file_turboci_orchestrator_v1_identifier_proto_rawDescGZIP(), []int{0, 8}
}

func (x *Identifier_StageEdit) GetStage() *Identifier_Stage {
	if x != nil {
		return x.Stage
	}
	return nil
}

func (x *Identifier_StageEdit) GetVersion() *Revision {
	if x != nil {
		return x.Version
	}
	return nil
}

var File_turboci_orchestrator_v1_identifier_proto protoreflect.FileDescriptor

const file_turboci_orchestrator_v1_identifier_proto_rawDesc = "" +
	"\n" +
	"(turboci/orchestrator/v1/identifier.proto\x12\x17turboci.orchestrator.v1\x1a&turboci/orchestrator/v1/revision.proto\"\x9a\x0e\n" +
	"\n" +
	"Identifier\x12K\n" +
	"\twork_plan\x18\x01 \x01(\v2,.turboci.orchestrator.v1.Identifier.WorkPlanH\x00R\bworkPlan\x12A\n" +
	"\x05check\x18\x02 \x01(\v2).turboci.orchestrator.v1.Identifier.CheckH\x00R\x05check\x12T\n" +
	"\fcheck_option\x18\x03 \x01(\v2/.turboci.orchestrator.v1.Identifier.CheckOptionH\x00R\vcheckOption\x12d\n" +
	"\x12check_result_datum\x18\x04 \x01(\v24.turboci.orchestrator.v1.Identifier.CheckResultDatumH\x00R\x10checkResultDatum\x12N\n" +
	"\n" +
	"check_edit\x18\x05 \x01(\v2-.turboci.orchestrator.v1.Identifier.CheckEditH\x00R\tcheckEdit\x12a\n" +
	"\x11check_edit_option\x18\x06 \x01(\v23.turboci.orchestrator.v1.Identifier.CheckEditOptionH\x00R\x0fcheckEditOption\x12A\n" +
	"\x05stage\x18\a \x01(\v2).turboci.orchestrator.v1.Identifier.StageH\x00R\x05stage\x12W\n" +
	"\rstage_attempt\x18\b \x01(\v20.turboci.orchestrator.v1.Identifier.StageAttemptH\x00R\fstageAttempt\x12N\n" +
	"\n" +
	"stage_edit\x18\t \x01(\v2-.turboci.orchestrator.v1.Identifier.StageEditH\x00R\tstageEdit\x1a\x1a\n" +
	"\bWorkPlan\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x1ab\n" +
	"\x05Check\x12I\n" +
	"\twork_plan\x18\x01 \x01(\v2,.turboci.orchestrator.v1.Identifier.WorkPlanR\bworkPlan\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x1ao\n" +
	"\vCheckOption\x12?\n" +
	"\x05check\x18\x01 \x01(\v2).turboci.orchestrator.v1.Identifier.CheckR\x05check\x12\x1f\n" +
	"\voptions_idx\x18\x02 \x01(\x05R\n" +
	"optionsIdx\x1a\x9e\x01\n" +
	"\x10CheckResultDatum\x12?\n" +
	"\x05check\x18\x01 \x01(\v2).turboci.orchestrator.v1.Identifier.CheckR\x05check\x12\x1f\n" +
	"\vresults_idx\x18\x02 \x01(\x05R\n" +
	"resultsIdx\x12(\n" +
	"\x10results_data_idx\x18\x03 \x01(\x05R\x0eresultsDataIdx\x1a\x89\x01\n" +
	"\tCheckEdit\x12?\n" +
	"\x05check\x18\x01 \x01(\v2).turboci.orchestrator.v1.Identifier.CheckR\x05check\x12;\n" +
	"\aversion\x18\x02 \x01(\v2!.turboci.orchestrator.v1.RevisionR\aversion\x1a\x96\x01\n" +
	"\x0fCheckEditOption\x12L\n" +
	"\n" +
	"check_edit\x18\x01 \x01(\v2-.turboci.orchestrator.v1.Identifier.CheckEditR\tcheckEdit\x125\n" +
	"\x17check_delta_options_idx\x18\x02 \x01(\x05R\x14checkDeltaOptionsIdx\x1ab\n" +
	"\x05Stage\x12I\n" +
	"\twork_plan\x18\x01 \x01(\v2,.turboci.orchestrator.v1.Identifier.WorkPlanR\bworkPlan\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\x1ar\n" +
	"\fStageAttempt\x12?\n" +
	"\x05stage\x18\x01 \x01(\v2).turboci.orchestrator.v1.Identifier.StageR\x05stage\x12!\n" +
	"\fattempts_idx\x18\x02 \x01(\x05R\vattemptsIdx\x1a\x89\x01\n" +
	"\tStageEdit\x12?\n" +
	"\x05stage\x18\x01 \x01(\v2).turboci.orchestrator.v1.Identifier.StageR\x05stage\x12;\n" +
	"\aversion\x18\x02 \x01(\v2!.turboci.orchestrator.v1.RevisionR\aversionB\x06\n" +
	"\x04typeBAP\x01Z=go.chromium.org/turboci/proto/go/orchestrator/v1;orchestratorb\beditionsp\xe8\a"

var (
	file_turboci_orchestrator_v1_identifier_proto_rawDescOnce sync.Once
	file_turboci_orchestrator_v1_identifier_proto_rawDescData []byte
)

func file_turboci_orchestrator_v1_identifier_proto_rawDescGZIP() []byte {
	file_turboci_orchestrator_v1_identifier_proto_rawDescOnce.Do(func() {
		file_turboci_orchestrator_v1_identifier_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_turboci_orchestrator_v1_identifier_proto_rawDesc), len(file_turboci_orchestrator_v1_identifier_proto_rawDesc)))
	})
	return file_turboci_orchestrator_v1_identifier_proto_rawDescData
}

var file_turboci_orchestrator_v1_identifier_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_turboci_orchestrator_v1_identifier_proto_goTypes = []any{
	(*Identifier)(nil),                  // 0: turboci.orchestrator.v1.Identifier
	(*Identifier_WorkPlan)(nil),         // 1: turboci.orchestrator.v1.Identifier.WorkPlan
	(*Identifier_Check)(nil),            // 2: turboci.orchestrator.v1.Identifier.Check
	(*Identifier_CheckOption)(nil),      // 3: turboci.orchestrator.v1.Identifier.CheckOption
	(*Identifier_CheckResultDatum)(nil), // 4: turboci.orchestrator.v1.Identifier.CheckResultDatum
	(*Identifier_CheckEdit)(nil),        // 5: turboci.orchestrator.v1.Identifier.CheckEdit
	(*Identifier_CheckEditOption)(nil),  // 6: turboci.orchestrator.v1.Identifier.CheckEditOption
	(*Identifier_Stage)(nil),            // 7: turboci.orchestrator.v1.Identifier.Stage
	(*Identifier_StageAttempt)(nil),     // 8: turboci.orchestrator.v1.Identifier.StageAttempt
	(*Identifier_StageEdit)(nil),        // 9: turboci.orchestrator.v1.Identifier.StageEdit
	(*Revision)(nil),                    // 10: turboci.orchestrator.v1.Revision
}
var file_turboci_orchestrator_v1_identifier_proto_depIdxs = []int32{
	1,  // 0: turboci.orchestrator.v1.Identifier.work_plan:type_name -> turboci.orchestrator.v1.Identifier.WorkPlan
	2,  // 1: turboci.orchestrator.v1.Identifier.check:type_name -> turboci.orchestrator.v1.Identifier.Check
	3,  // 2: turboci.orchestrator.v1.Identifier.check_option:type_name -> turboci.orchestrator.v1.Identifier.CheckOption
	4,  // 3: turboci.orchestrator.v1.Identifier.check_result_datum:type_name -> turboci.orchestrator.v1.Identifier.CheckResultDatum
	5,  // 4: turboci.orchestrator.v1.Identifier.check_edit:type_name -> turboci.orchestrator.v1.Identifier.CheckEdit
	6,  // 5: turboci.orchestrator.v1.Identifier.check_edit_option:type_name -> turboci.orchestrator.v1.Identifier.CheckEditOption
	7,  // 6: turboci.orchestrator.v1.Identifier.stage:type_name -> turboci.orchestrator.v1.Identifier.Stage
	8,  // 7: turboci.orchestrator.v1.Identifier.stage_attempt:type_name -> turboci.orchestrator.v1.Identifier.StageAttempt
	9,  // 8: turboci.orchestrator.v1.Identifier.stage_edit:type_name -> turboci.orchestrator.v1.Identifier.StageEdit
	1,  // 9: turboci.orchestrator.v1.Identifier.Check.work_plan:type_name -> turboci.orchestrator.v1.Identifier.WorkPlan
	2,  // 10: turboci.orchestrator.v1.Identifier.CheckOption.check:type_name -> turboci.orchestrator.v1.Identifier.Check
	2,  // 11: turboci.orchestrator.v1.Identifier.CheckResultDatum.check:type_name -> turboci.orchestrator.v1.Identifier.Check
	2,  // 12: turboci.orchestrator.v1.Identifier.CheckEdit.check:type_name -> turboci.orchestrator.v1.Identifier.Check
	10, // 13: turboci.orchestrator.v1.Identifier.CheckEdit.version:type_name -> turboci.orchestrator.v1.Revision
	5,  // 14: turboci.orchestrator.v1.Identifier.CheckEditOption.check_edit:type_name -> turboci.orchestrator.v1.Identifier.CheckEdit
	1,  // 15: turboci.orchestrator.v1.Identifier.Stage.work_plan:type_name -> turboci.orchestrator.v1.Identifier.WorkPlan
	7,  // 16: turboci.orchestrator.v1.Identifier.StageAttempt.stage:type_name -> turboci.orchestrator.v1.Identifier.Stage
	7,  // 17: turboci.orchestrator.v1.Identifier.StageEdit.stage:type_name -> turboci.orchestrator.v1.Identifier.Stage
	10, // 18: turboci.orchestrator.v1.Identifier.StageEdit.version:type_name -> turboci.orchestrator.v1.Revision
	19, // [19:19] is the sub-list for method output_type
	19, // [19:19] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_turboci_orchestrator_v1_identifier_proto_init() }
func file_turboci_orchestrator_v1_identifier_proto_init() {
	if File_turboci_orchestrator_v1_identifier_proto != nil {
		return
	}
	file_turboci_orchestrator_v1_revision_proto_init()
	file_turboci_orchestrator_v1_identifier_proto_msgTypes[0].OneofWrappers = []any{
		(*Identifier_WorkPlan_)(nil),
		(*Identifier_Check_)(nil),
		(*Identifier_CheckOption_)(nil),
		(*Identifier_CheckResultDatum_)(nil),
		(*Identifier_CheckEdit_)(nil),
		(*Identifier_CheckEditOption_)(nil),
		(*Identifier_Stage_)(nil),
		(*Identifier_StageAttempt_)(nil),
		(*Identifier_StageEdit_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_turboci_orchestrator_v1_identifier_proto_rawDesc), len(file_turboci_orchestrator_v1_identifier_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_turboci_orchestrator_v1_identifier_proto_goTypes,
		DependencyIndexes: file_turboci_orchestrator_v1_identifier_proto_depIdxs,
		MessageInfos:      file_turboci_orchestrator_v1_identifier_proto_msgTypes,
	}.Build()
	File_turboci_orchestrator_v1_identifier_proto = out.File
	file_turboci_orchestrator_v1_identifier_proto_goTypes = nil
	file_turboci_orchestrator_v1_identifier_proto_depIdxs = nil
}
