// Copyright 2025 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: turboci/orchestrator/v1/stage_attempt_state.proto

package orchestrator

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// StageAttemptState describes the current state of a StageAttempt.
//
// This state machine is much more complicated than Check or Stage state
// because:
//   - It revolves around synchronous / asynchronous state reconciliation
//     with external Executors.
//   - It subsumes a major portion of the historical WorkNode state machine in
//     a way that will allow us to be compatible with WorkNode state semantics.
//
// This state evolves like:
//
//	PENDING -> THROTTLED
//	PENDING -> RUNNING
//	PENDING -> COMPLETE
//	PENDING -> INCOMPLETE
//	PENDING -> SCHEDULED
//
//	THROTTLED -> INCOMPLETE
//	THROTTLED -> PENDING
//
//	SCHEDULED -> RUNNING
//	SCHEDULED -> COMPLETE
//	SCHEDULED -> INCOMPLETE
//
//	RUNNING -> CANCELLING
//	RUNNING -> TEARING_DOWN
//	RUNNING -> COMPLETE
//	RUNNING -> INCOMPLETE
//
//	CANCELLING -> TEARING_DOWN
//	CANCELLING -> INCOMPLETE
//
//	TEARING_DOWN -> COMPLETE
//	TEARING_DOWN -> INCOMPLETE
//
//	INCOMPLETE and COMPLETE are terminal states.
//
// The Nth StageAttempt (i.e. any StageAttempt after the first) may also be
// created in an AWAITING_RETRY state rather than PENDING.
//
//	AWAITING_RETRY -> PENDING
//	AWAITING_RETRY -> INCOMPLETE
//
// The Orchestrator manages StageAttempt state evolution in conjunction with the
// Executor, and explicit state transitions made explicitly by the StageAttempt
// itself. The only state transition which can be activated by a third party
// would be transitions to INCOMPLETE or CANCELLING done when the Stage is
// cancelled.
//
// These states have enum values in multiples of 10 in case we need to add more
// states later which fall between these initial states.
type StageAttemptState int32

const (
	// UNKNOWN is the default, invalid, state.
	StageAttemptState_STAGE_ATTEMPT_STATE_UNKNOWN StageAttemptState = 0
	// This is an initial state for a StageAttempt and indicates that the
	// StageAttempt is available for an Executor, but either:
	//   - The Orchestrator has not yet sent this StageAttempt to the Executor.
	//   - [WorkNode only] The Executor has advertised this Stage on pub/sub, but
	//     it has not yet been "Popped".
	//
	// This state can transition to THROTTLED, SCHEDULED, RUNNING, COMPLETE or
	// INCOMPLETE.
	StageAttemptState_STAGE_ATTEMPT_STATE_PENDING StageAttemptState = 10
	// This state indicates that the StageAttempt was PENDING, but is now picked
	// up for execution by an Executor.
	//
	// This state can transition to RUNNING, COMPLETE or INCOMPLETE.
	StageAttemptState_STAGE_ATTEMPT_STATE_SCHEDULED StageAttemptState = 30
	// This state indicates that the StageAttempt is now actually being executed
	// by an Executor.
	//
	// This state can transition to COMPLETE or INCOMPLETE.
	StageAttemptState_STAGE_ATTEMPT_STATE_RUNNING StageAttemptState = 40
	// This state indicates that the StageAttempt has been cancelled, but this has
	// not yet been communicated to the running STAGE_ATTEMPT.
	//
	// The StageAttempt must be assumed to internally consider itself to be
	// RUNNING while viewing this state from the API - this means that the
	// `running` heartbeat and timeout still apply during this state.
	//
	// This state will transition to TEARING_DOWN as soon as TurboCI has
	// confirmation that the StageAttempt knows it's been cancelled.
	//
	// This state is explicitly different than TEARING_DOWN to avoid the
	// possibility that a Stage is cancelled, but the Stage Attempt doesn't see
	// this until its next valid heartbeat - thus effectively losing up to 1.9x
	// the heartbeat interval out of its TEARING_DOWN timeout.
	StageAttemptState_STAGE_ATTEMPT_STATE_CANCELLING StageAttemptState = 50
	// This state indicates that the StageAttempt is doing some work after the
	// 'RUNNING' state.
	//
	// This is meant to model things like:
	//   - doing best-effort cleanup
	//   - exporting logs or other state to other systems
	//   - things like swarming's isolated upload/cache cleanup phase
	//
	// This state will only be used if the stage attempt has execution policy with
	// a non-zero timeout for this state.
	//
	// This state can transition to COMPLETE or INCOMPLETE.
	StageAttemptState_STAGE_ATTEMPT_STATE_TEARING_DOWN StageAttemptState = 60
	// This is a final state which indicates that this StageAttempt finished
	// everything the Executor intended it to do.
	//
	// NOTE: 'finished everything the Executor intended it to do' does not imply
	// workflow-level success criteria such as "all tests passed" or "the build
	// successfully compiled". This is more like "the test harness ran all of the
	// tests (regardless of their outcome)" or "the build started and all possible
	// compilation actions were done". These outcomes are highy varied and nuanced
	// (e.g. tests may be graded on flakiness, not simply pass/fail, build may
	// have failed on an optional target but successfully completed the required
	// targets). These workflow-level outcomes are reflected in the Check Results
	// which this StageAttempt would have written during its execution.
	//
	// NOTE: It is currently allowed for an Executor to request a retry of this
	// Stage, even as it marks the StageAttempt as COMPLETE. This can happen in
	// cases where the workflow-level criteria failed and the Executor wants a
	// 'quick and dirty' retry. More nuanced retries should be done at the
	// workflow level by adding additional follow-up Stages which can e.g. just
	// retry the subset of failing tests/build targets, or wait until a wider
	// analysis of other, parallel, stages have completed to make a smarter retry
	// decision.
	//
	// This state is terminal (but if a retry was requested, a new StageAttempt
	// may be created for this Stage).
	StageAttemptState_STAGE_ATTEMPT_STATE_COMPLETE StageAttemptState = 70
	// This is a final state which indicates that this StageAttempt was not able
	// to complete everything that the Executor intended it to do.
	//
	// The Orchestrator itself can transition the StageAttempt to this state in
	// the event of a heartbeat timeout. This state can also be entered by
	// explicit external actions (e.g. the Executor marking the stage as
	// INCOMPLETE, or external cancellation signals).
	//
	// Like COMPLETE, a retry can be requested for this state, even when the state
	// is explicitly written by the Executor. Similarly, the Executor could mark
	// the StageAttempt as INCOMPLETE without a retry for e.g. a non-retriable
	// failure (e.g. lack of resources).
	//
	// This state is terminal (but if a retry was requested, a new StageAttempt
	// may be created for this Stage).
	StageAttemptState_STAGE_ATTEMPT_STATE_INCOMPLETE StageAttemptState = 80
	// This is an initial state and indicates that a previous StageAttempt went to
	// a terminal state (COMPLETE or INCOMPLETE), a retry was requested, AND the
	// Stage's execution policy permitted a retry.
	//
	// Transition to PENDING is automatic after the execution policy's computed
	// retry delay.
	//
	// This state can transition to PENDING or INCOMPLETE.
	StageAttemptState_STAGE_ATTEMPT_STATE_AWAITING_RETRY StageAttemptState = 90
)

// Enum value maps for StageAttemptState.
var (
	StageAttemptState_name = map[int32]string{
		0:  "STAGE_ATTEMPT_STATE_UNKNOWN",
		10: "STAGE_ATTEMPT_STATE_PENDING",
		30: "STAGE_ATTEMPT_STATE_SCHEDULED",
		40: "STAGE_ATTEMPT_STATE_RUNNING",
		50: "STAGE_ATTEMPT_STATE_CANCELLING",
		60: "STAGE_ATTEMPT_STATE_TEARING_DOWN",
		70: "STAGE_ATTEMPT_STATE_COMPLETE",
		80: "STAGE_ATTEMPT_STATE_INCOMPLETE",
		90: "STAGE_ATTEMPT_STATE_AWAITING_RETRY",
	}
	StageAttemptState_value = map[string]int32{
		"STAGE_ATTEMPT_STATE_UNKNOWN":        0,
		"STAGE_ATTEMPT_STATE_PENDING":        10,
		"STAGE_ATTEMPT_STATE_SCHEDULED":      30,
		"STAGE_ATTEMPT_STATE_RUNNING":        40,
		"STAGE_ATTEMPT_STATE_CANCELLING":     50,
		"STAGE_ATTEMPT_STATE_TEARING_DOWN":   60,
		"STAGE_ATTEMPT_STATE_COMPLETE":       70,
		"STAGE_ATTEMPT_STATE_INCOMPLETE":     80,
		"STAGE_ATTEMPT_STATE_AWAITING_RETRY": 90,
	}
)

func (x StageAttemptState) Enum() *StageAttemptState {
	p := new(StageAttemptState)
	*p = x
	return p
}

func (x StageAttemptState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StageAttemptState) Descriptor() protoreflect.EnumDescriptor {
	return file_turboci_orchestrator_v1_stage_attempt_state_proto_enumTypes[0].Descriptor()
}

func (StageAttemptState) Type() protoreflect.EnumType {
	return &file_turboci_orchestrator_v1_stage_attempt_state_proto_enumTypes[0]
}

func (x StageAttemptState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StageAttemptState.Descriptor instead.
func (StageAttemptState) EnumDescriptor() ([]byte, []int) {
	return file_turboci_orchestrator_v1_stage_attempt_state_proto_rawDescGZIP(), []int{0}
}

var File_turboci_orchestrator_v1_stage_attempt_state_proto protoreflect.FileDescriptor

const file_turboci_orchestrator_v1_stage_attempt_state_proto_rawDesc = "" +
	"\n" +
	"1turboci/orchestrator/v1/stage_attempt_state.proto\x12\x17turboci.orchestrator.v1*\xd1\x02\n" +
	"\x11StageAttemptState\x12\x1f\n" +
	"\x1bSTAGE_ATTEMPT_STATE_UNKNOWN\x10\x00\x12\x1f\n" +
	"\x1bSTAGE_ATTEMPT_STATE_PENDING\x10\n" +
	"\x12!\n" +
	"\x1dSTAGE_ATTEMPT_STATE_SCHEDULED\x10\x1e\x12\x1f\n" +
	"\x1bSTAGE_ATTEMPT_STATE_RUNNING\x10(\x12\"\n" +
	"\x1eSTAGE_ATTEMPT_STATE_CANCELLING\x102\x12$\n" +
	" STAGE_ATTEMPT_STATE_TEARING_DOWN\x10<\x12 \n" +
	"\x1cSTAGE_ATTEMPT_STATE_COMPLETE\x10F\x12\"\n" +
	"\x1eSTAGE_ATTEMPT_STATE_INCOMPLETE\x10P\x12&\n" +
	"\"STAGE_ATTEMPT_STATE_AWAITING_RETRY\x10ZBAP\x01Z=go.chromium.org/turboci/proto/go/orchestrator/v1;orchestratorb\beditionsp\xe8\a"

var (
	file_turboci_orchestrator_v1_stage_attempt_state_proto_rawDescOnce sync.Once
	file_turboci_orchestrator_v1_stage_attempt_state_proto_rawDescData []byte
)

func file_turboci_orchestrator_v1_stage_attempt_state_proto_rawDescGZIP() []byte {
	file_turboci_orchestrator_v1_stage_attempt_state_proto_rawDescOnce.Do(func() {
		file_turboci_orchestrator_v1_stage_attempt_state_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_turboci_orchestrator_v1_stage_attempt_state_proto_rawDesc), len(file_turboci_orchestrator_v1_stage_attempt_state_proto_rawDesc)))
	})
	return file_turboci_orchestrator_v1_stage_attempt_state_proto_rawDescData
}

var file_turboci_orchestrator_v1_stage_attempt_state_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_turboci_orchestrator_v1_stage_attempt_state_proto_goTypes = []any{
	(StageAttemptState)(0), // 0: turboci.orchestrator.v1.StageAttemptState
}
var file_turboci_orchestrator_v1_stage_attempt_state_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_turboci_orchestrator_v1_stage_attempt_state_proto_init() }
func file_turboci_orchestrator_v1_stage_attempt_state_proto_init() {
	if File_turboci_orchestrator_v1_stage_attempt_state_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_turboci_orchestrator_v1_stage_attempt_state_proto_rawDesc), len(file_turboci_orchestrator_v1_stage_attempt_state_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_turboci_orchestrator_v1_stage_attempt_state_proto_goTypes,
		DependencyIndexes: file_turboci_orchestrator_v1_stage_attempt_state_proto_depIdxs,
		EnumInfos:         file_turboci_orchestrator_v1_stage_attempt_state_proto_enumTypes,
	}.Build()
	File_turboci_orchestrator_v1_stage_attempt_state_proto = out.File
	file_turboci_orchestrator_v1_stage_attempt_state_proto_goTypes = nil
	file_turboci_orchestrator_v1_stage_attempt_state_proto_depIdxs = nil
}
