// Copyright 2025 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: turboci/orchestrator/v1/turbo_ci_orchestrator_service.proto

package orchestrator

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_turboci_orchestrator_v1_turbo_ci_orchestrator_service_proto protoreflect.FileDescriptor

const file_turboci_orchestrator_v1_turbo_ci_orchestrator_service_proto_rawDesc = "" +
	"\n" +
	";turboci/orchestrator/v1/turbo_ci_orchestrator_service.proto\x12\x17turboci.orchestrator.v1\x1a,turboci/orchestrator/v1/method_options.proto\x1a1turboci/orchestrator/v1/write_nodes_request.proto\x1a2turboci/orchestrator/v1/write_nodes_response.proto2\x84\x01\n" +
	"\x13TurboCIOrchestrator\x12m\n" +
	"\n" +
	"WriteNodes\x12*.turboci.orchestrator.v1.WriteNodesRequest\x1a+.turboci.orchestrator.v1.WriteNodesResponse\"\x06\xd2\xd5\xdb\xd2\x0f\x00BAP\x01Z=go.chromium.org/turboci/proto/go/orchestrator/v1;orchestratorb\beditionsp\xe8\a"

var file_turboci_orchestrator_v1_turbo_ci_orchestrator_service_proto_goTypes = []any{
	(*WriteNodesRequest)(nil),  // 0: turboci.orchestrator.v1.WriteNodesRequest
	(*WriteNodesResponse)(nil), // 1: turboci.orchestrator.v1.WriteNodesResponse
}
var file_turboci_orchestrator_v1_turbo_ci_orchestrator_service_proto_depIdxs = []int32{
	0, // 0: turboci.orchestrator.v1.TurboCIOrchestrator.WriteNodes:input_type -> turboci.orchestrator.v1.WriteNodesRequest
	1, // 1: turboci.orchestrator.v1.TurboCIOrchestrator.WriteNodes:output_type -> turboci.orchestrator.v1.WriteNodesResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_turboci_orchestrator_v1_turbo_ci_orchestrator_service_proto_init() }
func file_turboci_orchestrator_v1_turbo_ci_orchestrator_service_proto_init() {
	if File_turboci_orchestrator_v1_turbo_ci_orchestrator_service_proto != nil {
		return
	}
	file_turboci_orchestrator_v1_method_options_proto_init()
	file_turboci_orchestrator_v1_write_nodes_request_proto_init()
	file_turboci_orchestrator_v1_write_nodes_response_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_turboci_orchestrator_v1_turbo_ci_orchestrator_service_proto_rawDesc), len(file_turboci_orchestrator_v1_turbo_ci_orchestrator_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_turboci_orchestrator_v1_turbo_ci_orchestrator_service_proto_goTypes,
		DependencyIndexes: file_turboci_orchestrator_v1_turbo_ci_orchestrator_service_proto_depIdxs,
	}.Build()
	File_turboci_orchestrator_v1_turbo_ci_orchestrator_service_proto = out.File
	file_turboci_orchestrator_v1_turbo_ci_orchestrator_service_proto_goTypes = nil
	file_turboci_orchestrator_v1_turbo_ci_orchestrator_service_proto_depIdxs = nil
}
