// Copyright 2025 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: turboci/orchestrator/v1/value.proto

package orchestrator

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Value wraps a google.protobuf.Any but also provides a space for the server to
// give back an alternate serialization of the Any.
//
// The fields other than `value` are only conditionally set if the user
// requested alternate serialization.
//
// These alternate serializations use an eventually-consistent version of the
// proto, so it's possible for this to be missing fields vs. what is in the
// binary `value` field. These alternate serializations can be requested via
// QueryNodes with `alternate_serialization` set. The intent is to allow UIs to
// generically display this data, or for scripts (potentially including LLMs) to
// observe the data without having the proto descriptors handy.
//
// When writing this type to the server, only `value` is allowed to be
// populated.
type Value struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The actual value.
	Value *anypb.Any `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
	// If true the server knows that `value` contains unknown fields according to
	// the current proto descriptor loaded on the server.
	//
	// This can happen if the server's copy of the proto descriptor for `value` is
	// out of date vs the descriptor used by the writer for this Datum.
	HasUnknownFields *bool `protobuf:"varint,2,opt,name=has_unknown_fields,json=hasUnknownFields" json:"has_unknown_fields,omitempty"`
	// A ProtoJSON-serialized version of `value`.
	ValueJson     *string `protobuf:"bytes,3,opt,name=value_json,json=valueJson" json:"value_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Value) Reset() {
	*x = Value{}
	mi := &file_turboci_orchestrator_v1_value_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_turboci_orchestrator_v1_value_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_turboci_orchestrator_v1_value_proto_rawDescGZIP(), []int{0}
}

func (x *Value) GetValue() *anypb.Any {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Value) GetHasUnknownFields() bool {
	if x != nil && x.HasUnknownFields != nil {
		return *x.HasUnknownFields
	}
	return false
}

func (x *Value) GetValueJson() string {
	if x != nil && x.ValueJson != nil {
		return *x.ValueJson
	}
	return ""
}

var File_turboci_orchestrator_v1_value_proto protoreflect.FileDescriptor

const file_turboci_orchestrator_v1_value_proto_rawDesc = "" +
	"\n" +
	"#turboci/orchestrator/v1/value.proto\x12\x17turboci.orchestrator.v1\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/protobuf/any.proto\"\x8a\x01\n" +
	"\x05Value\x12*\n" +
	"\x05value\x18\x01 \x01(\v2\x14.google.protobuf.AnyR\x05value\x121\n" +
	"\x12has_unknown_fields\x18\x02 \x01(\bB\x03\xe0A\x03R\x10hasUnknownFields\x12\"\n" +
	"\n" +
	"value_json\x18\x03 \x01(\tB\x03\xe0A\x03R\tvalueJsonBAP\x01Z=go.chromium.org/turboci/proto/go/orchestrator/v1;orchestratorb\beditionsp\xe8\a"

var (
	file_turboci_orchestrator_v1_value_proto_rawDescOnce sync.Once
	file_turboci_orchestrator_v1_value_proto_rawDescData []byte
)

func file_turboci_orchestrator_v1_value_proto_rawDescGZIP() []byte {
	file_turboci_orchestrator_v1_value_proto_rawDescOnce.Do(func() {
		file_turboci_orchestrator_v1_value_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_turboci_orchestrator_v1_value_proto_rawDesc), len(file_turboci_orchestrator_v1_value_proto_rawDesc)))
	})
	return file_turboci_orchestrator_v1_value_proto_rawDescData
}

var file_turboci_orchestrator_v1_value_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_turboci_orchestrator_v1_value_proto_goTypes = []any{
	(*Value)(nil),     // 0: turboci.orchestrator.v1.Value
	(*anypb.Any)(nil), // 1: google.protobuf.Any
}
var file_turboci_orchestrator_v1_value_proto_depIdxs = []int32{
	1, // 0: turboci.orchestrator.v1.Value.value:type_name -> google.protobuf.Any
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_turboci_orchestrator_v1_value_proto_init() }
func file_turboci_orchestrator_v1_value_proto_init() {
	if File_turboci_orchestrator_v1_value_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_turboci_orchestrator_v1_value_proto_rawDesc), len(file_turboci_orchestrator_v1_value_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_turboci_orchestrator_v1_value_proto_goTypes,
		DependencyIndexes: file_turboci_orchestrator_v1_value_proto_depIdxs,
		MessageInfos:      file_turboci_orchestrator_v1_value_proto_msgTypes,
	}.Build()
	File_turboci_orchestrator_v1_value_proto = out.File
	file_turboci_orchestrator_v1_value_proto_goTypes = nil
	file_turboci_orchestrator_v1_value_proto_depIdxs = nil
}
