// Copyright 2025 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: turboci/orchestrator/v1/write_nodes_response.proto

package orchestrator

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Response message for TurboCIGraphService.WriteNodes.
type WriteNodesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteNodesResponse) Reset() {
	*x = WriteNodesResponse{}
	mi := &file_turboci_orchestrator_v1_write_nodes_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteNodesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteNodesResponse) ProtoMessage() {}

func (x *WriteNodesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_turboci_orchestrator_v1_write_nodes_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteNodesResponse.ProtoReflect.Descriptor instead.
func (*WriteNodesResponse) Descriptor() ([]byte, []int) {
	return file_turboci_orchestrator_v1_write_nodes_response_proto_rawDescGZIP(), []int{0}
}

var File_turboci_orchestrator_v1_write_nodes_response_proto protoreflect.FileDescriptor

const file_turboci_orchestrator_v1_write_nodes_response_proto_rawDesc = "" +
	"\n" +
	"2turboci/orchestrator/v1/write_nodes_response.proto\x12\x17turboci.orchestrator.v1\"\x14\n" +
	"\x12WriteNodesResponseBAP\x01Z=go.chromium.org/turboci/proto/go/orchestrator/v1;orchestratorb\beditionsp\xe8\a"

var (
	file_turboci_orchestrator_v1_write_nodes_response_proto_rawDescOnce sync.Once
	file_turboci_orchestrator_v1_write_nodes_response_proto_rawDescData []byte
)

func file_turboci_orchestrator_v1_write_nodes_response_proto_rawDescGZIP() []byte {
	file_turboci_orchestrator_v1_write_nodes_response_proto_rawDescOnce.Do(func() {
		file_turboci_orchestrator_v1_write_nodes_response_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_turboci_orchestrator_v1_write_nodes_response_proto_rawDesc), len(file_turboci_orchestrator_v1_write_nodes_response_proto_rawDesc)))
	})
	return file_turboci_orchestrator_v1_write_nodes_response_proto_rawDescData
}

var file_turboci_orchestrator_v1_write_nodes_response_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_turboci_orchestrator_v1_write_nodes_response_proto_goTypes = []any{
	(*WriteNodesResponse)(nil), // 0: turboci.orchestrator.v1.WriteNodesResponse
}
var file_turboci_orchestrator_v1_write_nodes_response_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_turboci_orchestrator_v1_write_nodes_response_proto_init() }
func file_turboci_orchestrator_v1_write_nodes_response_proto_init() {
	if File_turboci_orchestrator_v1_write_nodes_response_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_turboci_orchestrator_v1_write_nodes_response_proto_rawDesc), len(file_turboci_orchestrator_v1_write_nodes_response_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_turboci_orchestrator_v1_write_nodes_response_proto_goTypes,
		DependencyIndexes: file_turboci_orchestrator_v1_write_nodes_response_proto_depIdxs,
		MessageInfos:      file_turboci_orchestrator_v1_write_nodes_response_proto_msgTypes,
	}.Build()
	File_turboci_orchestrator_v1_write_nodes_response_proto = out.File
	file_turboci_orchestrator_v1_write_nodes_response_proto_goTypes = nil
	file_turboci_orchestrator_v1_write_nodes_response_proto_depIdxs = nil
}
