// Copyright 2025 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: turboci/graph/ids/v1/identifier.proto

package idspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A generic identifier that can be used to identify all TurboCI graph nodes.
//
// Within some message (e.g. Check), you may see usage of Identifier.X directly
// to indicate that the Identifier there can only be a single kind. Having the
// Identifier container, however, allows for generic structures like Edge which
// can refer to multiple kinds of nodes in different contexts.
//
// No string identifiers here may contain a colon.
type Identifier struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Type isIdentifier_Type      `protobuf_oneof:"type"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Identifier) Reset() {
	*x = Identifier{}
	mi := &file_turboci_graph_ids_v1_identifier_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Identifier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Identifier) ProtoMessage() {}

func (x *Identifier) ProtoReflect() protoreflect.Message {
	mi := &file_turboci_graph_ids_v1_identifier_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Identifier) GetWorkPlan() *WorkPlan {
	if x != nil {
		if x, ok := x.xxx_hidden_Type.(*identifier_WorkPlan); ok {
			return x.WorkPlan
		}
	}
	return nil
}

func (x *Identifier) GetCheck() *Check {
	if x != nil {
		if x, ok := x.xxx_hidden_Type.(*identifier_Check); ok {
			return x.Check
		}
	}
	return nil
}

func (x *Identifier) GetCheckResult() *CheckResult {
	if x != nil {
		if x, ok := x.xxx_hidden_Type.(*identifier_CheckResult); ok {
			return x.CheckResult
		}
	}
	return nil
}

func (x *Identifier) GetCheckEdit() *CheckEdit {
	if x != nil {
		if x, ok := x.xxx_hidden_Type.(*identifier_CheckEdit); ok {
			return x.CheckEdit
		}
	}
	return nil
}

func (x *Identifier) GetStage() *Stage {
	if x != nil {
		if x, ok := x.xxx_hidden_Type.(*identifier_Stage); ok {
			return x.Stage
		}
	}
	return nil
}

func (x *Identifier) GetStageAttempt() *StageAttempt {
	if x != nil {
		if x, ok := x.xxx_hidden_Type.(*identifier_StageAttempt); ok {
			return x.StageAttempt
		}
	}
	return nil
}

func (x *Identifier) GetStageEdit() *StageEdit {
	if x != nil {
		if x, ok := x.xxx_hidden_Type.(*identifier_StageEdit); ok {
			return x.StageEdit
		}
	}
	return nil
}

func (x *Identifier) SetWorkPlan(v *WorkPlan) {
	if v == nil {
		x.xxx_hidden_Type = nil
		return
	}
	x.xxx_hidden_Type = &identifier_WorkPlan{v}
}

func (x *Identifier) SetCheck(v *Check) {
	if v == nil {
		x.xxx_hidden_Type = nil
		return
	}
	x.xxx_hidden_Type = &identifier_Check{v}
}

func (x *Identifier) SetCheckResult(v *CheckResult) {
	if v == nil {
		x.xxx_hidden_Type = nil
		return
	}
	x.xxx_hidden_Type = &identifier_CheckResult{v}
}

func (x *Identifier) SetCheckEdit(v *CheckEdit) {
	if v == nil {
		x.xxx_hidden_Type = nil
		return
	}
	x.xxx_hidden_Type = &identifier_CheckEdit{v}
}

func (x *Identifier) SetStage(v *Stage) {
	if v == nil {
		x.xxx_hidden_Type = nil
		return
	}
	x.xxx_hidden_Type = &identifier_Stage{v}
}

func (x *Identifier) SetStageAttempt(v *StageAttempt) {
	if v == nil {
		x.xxx_hidden_Type = nil
		return
	}
	x.xxx_hidden_Type = &identifier_StageAttempt{v}
}

func (x *Identifier) SetStageEdit(v *StageEdit) {
	if v == nil {
		x.xxx_hidden_Type = nil
		return
	}
	x.xxx_hidden_Type = &identifier_StageEdit{v}
}

func (x *Identifier) HasType() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Type != nil
}

func (x *Identifier) HasWorkPlan() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Type.(*identifier_WorkPlan)
	return ok
}

func (x *Identifier) HasCheck() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Type.(*identifier_Check)
	return ok
}

func (x *Identifier) HasCheckResult() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Type.(*identifier_CheckResult)
	return ok
}

func (x *Identifier) HasCheckEdit() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Type.(*identifier_CheckEdit)
	return ok
}

func (x *Identifier) HasStage() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Type.(*identifier_Stage)
	return ok
}

func (x *Identifier) HasStageAttempt() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Type.(*identifier_StageAttempt)
	return ok
}

func (x *Identifier) HasStageEdit() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Type.(*identifier_StageEdit)
	return ok
}

func (x *Identifier) ClearType() {
	x.xxx_hidden_Type = nil
}

func (x *Identifier) ClearWorkPlan() {
	if _, ok := x.xxx_hidden_Type.(*identifier_WorkPlan); ok {
		x.xxx_hidden_Type = nil
	}
}

func (x *Identifier) ClearCheck() {
	if _, ok := x.xxx_hidden_Type.(*identifier_Check); ok {
		x.xxx_hidden_Type = nil
	}
}

func (x *Identifier) ClearCheckResult() {
	if _, ok := x.xxx_hidden_Type.(*identifier_CheckResult); ok {
		x.xxx_hidden_Type = nil
	}
}

func (x *Identifier) ClearCheckEdit() {
	if _, ok := x.xxx_hidden_Type.(*identifier_CheckEdit); ok {
		x.xxx_hidden_Type = nil
	}
}

func (x *Identifier) ClearStage() {
	if _, ok := x.xxx_hidden_Type.(*identifier_Stage); ok {
		x.xxx_hidden_Type = nil
	}
}

func (x *Identifier) ClearStageAttempt() {
	if _, ok := x.xxx_hidden_Type.(*identifier_StageAttempt); ok {
		x.xxx_hidden_Type = nil
	}
}

func (x *Identifier) ClearStageEdit() {
	if _, ok := x.xxx_hidden_Type.(*identifier_StageEdit); ok {
		x.xxx_hidden_Type = nil
	}
}

const Identifier_Type_not_set_case case_Identifier_Type = 0
const Identifier_WorkPlan_case case_Identifier_Type = 1
const Identifier_Check_case case_Identifier_Type = 2
const Identifier_CheckResult_case case_Identifier_Type = 4
const Identifier_CheckEdit_case case_Identifier_Type = 6
const Identifier_Stage_case case_Identifier_Type = 8
const Identifier_StageAttempt_case case_Identifier_Type = 9
const Identifier_StageEdit_case case_Identifier_Type = 10

func (x *Identifier) WhichType() case_Identifier_Type {
	if x == nil {
		return Identifier_Type_not_set_case
	}
	switch x.xxx_hidden_Type.(type) {
	case *identifier_WorkPlan:
		return Identifier_WorkPlan_case
	case *identifier_Check:
		return Identifier_Check_case
	case *identifier_CheckResult:
		return Identifier_CheckResult_case
	case *identifier_CheckEdit:
		return Identifier_CheckEdit_case
	case *identifier_Stage:
		return Identifier_Stage_case
	case *identifier_StageAttempt:
		return Identifier_StageAttempt_case
	case *identifier_StageEdit:
		return Identifier_StageEdit_case
	default:
		return Identifier_Type_not_set_case
	}
}

type Identifier_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The type of this Identifier.
	//
	// This should be kept in sync with the `IdentifierKind` enum.

	// Fields of oneof xxx_hidden_Type:
	// A whole WorkPlan.
	WorkPlan *WorkPlan
	// A Check within a WorkPlan.
	Check *Check
	// A particular Check.Result.
	CheckResult *CheckResult
	// An edit to a Check.
	CheckEdit *CheckEdit
	// A Stage within a WorkPlan.
	Stage *Stage
	// A specific attempt at a Stage.
	StageAttempt *StageAttempt
	// An edit to a Stage.
	StageEdit *StageEdit
	// -- end of xxx_hidden_Type
}

func (b0 Identifier_builder) Build() *Identifier {
	m0 := &Identifier{}
	b, x := &b0, m0
	_, _ = b, x
	if b.WorkPlan != nil {
		x.xxx_hidden_Type = &identifier_WorkPlan{b.WorkPlan}
	}
	if b.Check != nil {
		x.xxx_hidden_Type = &identifier_Check{b.Check}
	}
	if b.CheckResult != nil {
		x.xxx_hidden_Type = &identifier_CheckResult{b.CheckResult}
	}
	if b.CheckEdit != nil {
		x.xxx_hidden_Type = &identifier_CheckEdit{b.CheckEdit}
	}
	if b.Stage != nil {
		x.xxx_hidden_Type = &identifier_Stage{b.Stage}
	}
	if b.StageAttempt != nil {
		x.xxx_hidden_Type = &identifier_StageAttempt{b.StageAttempt}
	}
	if b.StageEdit != nil {
		x.xxx_hidden_Type = &identifier_StageEdit{b.StageEdit}
	}
	return m0
}

type case_Identifier_Type protoreflect.FieldNumber

func (x case_Identifier_Type) String() string {
	md := file_turboci_graph_ids_v1_identifier_proto_msgTypes[0].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isIdentifier_Type interface {
	isIdentifier_Type()
}

type identifier_WorkPlan struct {
	// A whole WorkPlan.
	WorkPlan *WorkPlan `protobuf:"bytes,1,opt,name=work_plan,json=workPlan,proto3,oneof"`
}

type identifier_Check struct {
	// A Check within a WorkPlan.
	Check *Check `protobuf:"bytes,2,opt,name=check,proto3,oneof"`
}

type identifier_CheckResult struct {
	// A particular Check.Result.
	CheckResult *CheckResult `protobuf:"bytes,4,opt,name=check_result,json=checkResult,proto3,oneof"`
}

type identifier_CheckEdit struct {
	// An edit to a Check.
	CheckEdit *CheckEdit `protobuf:"bytes,6,opt,name=check_edit,json=checkEdit,proto3,oneof"`
}

type identifier_Stage struct {
	// A Stage within a WorkPlan.
	Stage *Stage `protobuf:"bytes,8,opt,name=stage,proto3,oneof"`
}

type identifier_StageAttempt struct {
	// A specific attempt at a Stage.
	StageAttempt *StageAttempt `protobuf:"bytes,9,opt,name=stage_attempt,json=stageAttempt,proto3,oneof"`
}

type identifier_StageEdit struct {
	// An edit to a Stage.
	StageEdit *StageEdit `protobuf:"bytes,10,opt,name=stage_edit,json=stageEdit,proto3,oneof"`
}

func (*identifier_WorkPlan) isIdentifier_Type() {}

func (*identifier_Check) isIdentifier_Type() {}

func (*identifier_CheckResult) isIdentifier_Type() {}

func (*identifier_CheckEdit) isIdentifier_Type() {}

func (*identifier_Stage) isIdentifier_Type() {}

func (*identifier_StageAttempt) isIdentifier_Type() {}

func (*identifier_StageEdit) isIdentifier_Type() {}

// Identifies an entire TurboCI WorkPlan.
//
// Serialized as "L<id>".
type WorkPlan struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          *string                `protobuf:"bytes,1,opt,name=id,proto3,oneof"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *WorkPlan) Reset() {
	*x = WorkPlan{}
	mi := &file_turboci_graph_ids_v1_identifier_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkPlan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkPlan) ProtoMessage() {}

func (x *WorkPlan) ProtoReflect() protoreflect.Message {
	mi := &file_turboci_graph_ids_v1_identifier_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *WorkPlan) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *WorkPlan) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *WorkPlan) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *WorkPlan) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

type WorkPlan_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Globally unique identifier for this WorkPlan.
	//
	// Has the form "<digits>" and is generated by the TurboCI service.
	Id *string
}

func (b0 WorkPlan_builder) Build() *WorkPlan {
	m0 := &WorkPlan{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Id = b.Id
	}
	return m0
}

// Identifies a Check within a WorkPlan.
//
// Serialized as "<work_plan>:C<id>".
//
// E.g. "L<work_plan.id>:C<id>"
type Check struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_WorkPlan    *WorkPlan              `protobuf:"bytes,1,opt,name=work_plan,json=workPlan,proto3,oneof"`
	xxx_hidden_Id          *string                `protobuf:"bytes,2,opt,name=id,proto3,oneof"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Check) Reset() {
	*x = Check{}
	mi := &file_turboci_graph_ids_v1_identifier_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Check) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Check) ProtoMessage() {}

func (x *Check) ProtoReflect() protoreflect.Message {
	mi := &file_turboci_graph_ids_v1_identifier_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Check) GetWorkPlan() *WorkPlan {
	if x != nil {
		return x.xxx_hidden_WorkPlan
	}
	return nil
}

func (x *Check) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *Check) SetWorkPlan(v *WorkPlan) {
	x.xxx_hidden_WorkPlan = v
}

func (x *Check) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *Check) HasWorkPlan() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_WorkPlan != nil
}

func (x *Check) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Check) ClearWorkPlan() {
	x.xxx_hidden_WorkPlan = nil
}

func (x *Check) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Id = nil
}

type Check_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The WorkPlan this check is scoped to.
	WorkPlan *WorkPlan
	// An opaque identifier unique within this WorkPlan.
	//
	// Provided by the Stage which added this Check.
	//
	// TBD: Specify the format of this ID as regex - it should have a maximum
	// length and not be allowed to contain a colon at the very least.
	Id *string
}

func (b0 Check_builder) Build() *Check {
	m0 := &Check{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_WorkPlan = b.WorkPlan
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Id = b.Id
	}
	return m0
}

// Identifies a Check Result within a WorkPlan.
//
// Serialized as "<check>:R<results_idx>".
//
// E.g. "L<check.work_plan.id>:C<check.id>:R<idx>"
//
// This is separate from `Check` because it may reside in a different realm
// than the Check itself.
type CheckResult struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Check       *Check                 `protobuf:"bytes,1,opt,name=check,proto3,oneof"`
	xxx_hidden_Idx         int32                  `protobuf:"varint,2,opt,name=idx,proto3,oneof"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CheckResult) Reset() {
	*x = CheckResult{}
	mi := &file_turboci_graph_ids_v1_identifier_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckResult) ProtoMessage() {}

func (x *CheckResult) ProtoReflect() protoreflect.Message {
	mi := &file_turboci_graph_ids_v1_identifier_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CheckResult) GetCheck() *Check {
	if x != nil {
		return x.xxx_hidden_Check
	}
	return nil
}

func (x *CheckResult) GetIdx() int32 {
	if x != nil {
		return x.xxx_hidden_Idx
	}
	return 0
}

func (x *CheckResult) SetCheck(v *Check) {
	x.xxx_hidden_Check = v
}

func (x *CheckResult) SetIdx(v int32) {
	x.xxx_hidden_Idx = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *CheckResult) HasCheck() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Check != nil
}

func (x *CheckResult) HasIdx() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *CheckResult) ClearCheck() {
	x.xxx_hidden_Check = nil
}

func (x *CheckResult) ClearIdx() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Idx = 0
}

type CheckResult_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The check that this result belongs to.
	Check *Check
	// The 1-based index of this result within the Check.results list.
	//
	// This is 1-based to distinguish it from 0/unset (which is invalid).
	Idx *int32
}

func (b0 CheckResult_builder) Build() *CheckResult {
	m0 := &CheckResult{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Check = b.Check
	if b.Idx != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Idx = *b.Idx
	}
	return m0
}

// Identifies a CheckEdit within a WorkPlan.
//
// Serialized as "<check>:V<version>".
//
// E.g.
// "L<check.work_plan.id>:C<check.id>:V<version.seconds>/<version.nanos>"
type CheckEdit struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Check   *Check                 `protobuf:"bytes,1,opt,name=check,proto3,oneof"`
	xxx_hidden_Version *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=version,proto3,oneof"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CheckEdit) Reset() {
	*x = CheckEdit{}
	mi := &file_turboci_graph_ids_v1_identifier_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckEdit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckEdit) ProtoMessage() {}

func (x *CheckEdit) ProtoReflect() protoreflect.Message {
	mi := &file_turboci_graph_ids_v1_identifier_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CheckEdit) GetCheck() *Check {
	if x != nil {
		return x.xxx_hidden_Check
	}
	return nil
}

func (x *CheckEdit) GetVersion() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_Version
	}
	return nil
}

func (x *CheckEdit) SetCheck(v *Check) {
	x.xxx_hidden_Check = v
}

func (x *CheckEdit) SetVersion(v *timestamppb.Timestamp) {
	x.xxx_hidden_Version = v
}

func (x *CheckEdit) HasCheck() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Check != nil
}

func (x *CheckEdit) HasVersion() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Version != nil
}

func (x *CheckEdit) ClearCheck() {
	x.xxx_hidden_Check = nil
}

func (x *CheckEdit) ClearVersion() {
	x.xxx_hidden_Version = nil
}

type CheckEdit_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The check that this edit belongs to.
	Check *Check
	// The version of the Check at the time this edit was made.
	Version *timestamppb.Timestamp
}

func (b0 CheckEdit_builder) Build() *CheckEdit {
	m0 := &CheckEdit{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Check = b.Check
	x.xxx_hidden_Version = b.Version
	return m0
}

// Identifies a Stage within a WorkPlan.
//
// If the Stage has the WorkNode type, `is_worknode` will be true, otherwise it
// is false.
//
// Worknode Stages have additional synchronization with the WorkNodes table.
// These Stages will have a numeric `id`.
//
// non-WorkNode Stages don't have any special treatment and do not have
// a restricted format for `id` (other than the usual prohibition of the use of
// colons).
//
// Serialized as "<work_plan>:?<id>" where ? is N for WorkNode Stages, and
// S for non-WorkNode Stages.
//
// E.g. "L<work_plan.id>:S<id>" or "L<work_plan.id>:N<id>".
type Stage struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_WorkPlan    *WorkPlan              `protobuf:"bytes,1,opt,name=work_plan,json=workPlan,proto3,oneof"`
	xxx_hidden_IsWorknode  bool                   `protobuf:"varint,2,opt,name=is_worknode,json=isWorknode,proto3,oneof"`
	xxx_hidden_Id          *string                `protobuf:"bytes,3,opt,name=id,proto3,oneof"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Stage) Reset() {
	*x = Stage{}
	mi := &file_turboci_graph_ids_v1_identifier_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stage) ProtoMessage() {}

func (x *Stage) ProtoReflect() protoreflect.Message {
	mi := &file_turboci_graph_ids_v1_identifier_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Stage) GetWorkPlan() *WorkPlan {
	if x != nil {
		return x.xxx_hidden_WorkPlan
	}
	return nil
}

func (x *Stage) GetIsWorknode() bool {
	if x != nil {
		return x.xxx_hidden_IsWorknode
	}
	return false
}

func (x *Stage) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *Stage) SetWorkPlan(v *WorkPlan) {
	x.xxx_hidden_WorkPlan = v
}

func (x *Stage) SetIsWorknode(v bool) {
	x.xxx_hidden_IsWorknode = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *Stage) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *Stage) HasWorkPlan() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_WorkPlan != nil
}

func (x *Stage) HasIsWorknode() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Stage) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *Stage) ClearWorkPlan() {
	x.xxx_hidden_WorkPlan = nil
}

func (x *Stage) ClearIsWorknode() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_IsWorknode = false
}

func (x *Stage) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Id = nil
}

type Stage_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The WorkPlan that this Stage belongs to.
	WorkPlan *WorkPlan
	// True if this Stage represents a WorkNode, false otherwise.
	IsWorknode *bool
	// An opaque identifier unique within this WorkPlan.
	//
	// For WorkNodes (`is_worknode` is true), this will a decimal integer.
	//
	// Otherwise this will be an arbitrary string supplied by the Stage which
	// added this.
	Id *string
}

func (b0 Stage_builder) Build() *Stage {
	m0 := &Stage{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_WorkPlan = b.WorkPlan
	if b.IsWorknode != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_IsWorknode = *b.IsWorknode
	}
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_Id = b.Id
	}
	return m0
}

// Identifies a Stage Attempt within a Stage.
//
// Note that Stage.Attempt is embedded within a Stage, but we need a reference
// to it from various places (e.g. Check and Stage Edits), so it has an
// Identifier here. Most users will use Stage instead.
//
// Serialized as "<stage>:A<attempts_idx>".
//
// E.g. "L<stage.work_plan.id>:<stage.id>:A<attempts_idx>"
type StageAttempt struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Stage       *Stage                 `protobuf:"bytes,1,opt,name=stage,proto3,oneof"`
	xxx_hidden_Idx         int32                  `protobuf:"varint,2,opt,name=idx,proto3,oneof"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *StageAttempt) Reset() {
	*x = StageAttempt{}
	mi := &file_turboci_graph_ids_v1_identifier_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StageAttempt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StageAttempt) ProtoMessage() {}

func (x *StageAttempt) ProtoReflect() protoreflect.Message {
	mi := &file_turboci_graph_ids_v1_identifier_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StageAttempt) GetStage() *Stage {
	if x != nil {
		return x.xxx_hidden_Stage
	}
	return nil
}

func (x *StageAttempt) GetIdx() int32 {
	if x != nil {
		return x.xxx_hidden_Idx
	}
	return 0
}

func (x *StageAttempt) SetStage(v *Stage) {
	x.xxx_hidden_Stage = v
}

func (x *StageAttempt) SetIdx(v int32) {
	x.xxx_hidden_Idx = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *StageAttempt) HasStage() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Stage != nil
}

func (x *StageAttempt) HasIdx() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *StageAttempt) ClearStage() {
	x.xxx_hidden_Stage = nil
}

func (x *StageAttempt) ClearIdx() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Idx = 0
}

type StageAttempt_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The Stage that this Stage Attempt belongs to.
	Stage *Stage
	// The 1-based index of this attempt within the Stage.attempts list.
	//
	// This is 1-based to distinguish it from 0/unset (which is invalid).
	Idx *int32
}

func (b0 StageAttempt_builder) Build() *StageAttempt {
	m0 := &StageAttempt{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Stage = b.Stage
	if b.Idx != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Idx = *b.Idx
	}
	return m0
}

// Identifies a Stage Edit within a WorkPlan.
//
// Serialized as "<stage>:V<version>".
//
// E.g.
// "L<stage.work_plan.id>:<stage.id>:V<version.seconds>/<version.nanos>"
type StageEdit struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Stage   *Stage                 `protobuf:"bytes,1,opt,name=stage,proto3,oneof"`
	xxx_hidden_Version *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=version,proto3,oneof"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *StageEdit) Reset() {
	*x = StageEdit{}
	mi := &file_turboci_graph_ids_v1_identifier_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StageEdit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StageEdit) ProtoMessage() {}

func (x *StageEdit) ProtoReflect() protoreflect.Message {
	mi := &file_turboci_graph_ids_v1_identifier_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StageEdit) GetStage() *Stage {
	if x != nil {
		return x.xxx_hidden_Stage
	}
	return nil
}

func (x *StageEdit) GetVersion() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_Version
	}
	return nil
}

func (x *StageEdit) SetStage(v *Stage) {
	x.xxx_hidden_Stage = v
}

func (x *StageEdit) SetVersion(v *timestamppb.Timestamp) {
	x.xxx_hidden_Version = v
}

func (x *StageEdit) HasStage() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Stage != nil
}

func (x *StageEdit) HasVersion() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Version != nil
}

func (x *StageEdit) ClearStage() {
	x.xxx_hidden_Stage = nil
}

func (x *StageEdit) ClearVersion() {
	x.xxx_hidden_Version = nil
}

type StageEdit_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The stage that this edit belongs to.
	Stage *Stage
	// The version of the Stage at the time this edit was made.
	Version *timestamppb.Timestamp
}

func (b0 StageEdit_builder) Build() *StageEdit {
	m0 := &StageEdit{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Stage = b.Stage
	x.xxx_hidden_Version = b.Version
	return m0
}

var File_turboci_graph_ids_v1_identifier_proto protoreflect.FileDescriptor

const file_turboci_graph_ids_v1_identifier_proto_rawDesc = "" +
	"\n" +
	"%turboci/graph/ids/v1/identifier.proto\x12\x14turboci.graph.ids.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9b\x04\n" +
	"\n" +
	"Identifier\x12=\n" +
	"\twork_plan\x18\x01 \x01(\v2\x1e.turboci.graph.ids.v1.WorkPlanH\x00R\bworkPlan\x123\n" +
	"\x05check\x18\x02 \x01(\v2\x1b.turboci.graph.ids.v1.CheckH\x00R\x05check\x12F\n" +
	"\fcheck_result\x18\x04 \x01(\v2!.turboci.graph.ids.v1.CheckResultH\x00R\vcheckResult\x12@\n" +
	"\n" +
	"check_edit\x18\x06 \x01(\v2\x1f.turboci.graph.ids.v1.CheckEditH\x00R\tcheckEdit\x123\n" +
	"\x05stage\x18\b \x01(\v2\x1b.turboci.graph.ids.v1.StageH\x00R\x05stage\x12I\n" +
	"\rstage_attempt\x18\t \x01(\v2\".turboci.graph.ids.v1.StageAttemptH\x00R\fstageAttempt\x12@\n" +
	"\n" +
	"stage_edit\x18\n" +
	" \x01(\v2\x1f.turboci.graph.ids.v1.StageEditH\x00R\tstageEditB\x06\n" +
	"\x04typeJ\x04\b\x03\x10\x04J\x04\b\x05\x10\x06J\x04\b\a\x10\bR\fcheck_optionR\x12check_result_datumR\x11check_edit_option\"&\n" +
	"\bWorkPlan\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tH\x00R\x02id\x88\x01\x01B\x05\n" +
	"\x03_id\"s\n" +
	"\x05Check\x12@\n" +
	"\twork_plan\x18\x01 \x01(\v2\x1e.turboci.graph.ids.v1.WorkPlanH\x00R\bworkPlan\x88\x01\x01\x12\x13\n" +
	"\x02id\x18\x02 \x01(\tH\x01R\x02id\x88\x01\x01B\f\n" +
	"\n" +
	"_work_planB\x05\n" +
	"\x03_id\"n\n" +
	"\vCheckResult\x126\n" +
	"\x05check\x18\x01 \x01(\v2\x1b.turboci.graph.ids.v1.CheckH\x00R\x05check\x88\x01\x01\x12\x15\n" +
	"\x03idx\x18\x02 \x01(\x05H\x01R\x03idx\x88\x01\x01B\b\n" +
	"\x06_checkB\x06\n" +
	"\x04_idx\"\x94\x01\n" +
	"\tCheckEdit\x126\n" +
	"\x05check\x18\x01 \x01(\v2\x1b.turboci.graph.ids.v1.CheckH\x00R\x05check\x88\x01\x01\x129\n" +
	"\aversion\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\aversion\x88\x01\x01B\b\n" +
	"\x06_checkB\n" +
	"\n" +
	"\b_version\"\xa9\x01\n" +
	"\x05Stage\x12@\n" +
	"\twork_plan\x18\x01 \x01(\v2\x1e.turboci.graph.ids.v1.WorkPlanH\x00R\bworkPlan\x88\x01\x01\x12$\n" +
	"\vis_worknode\x18\x02 \x01(\bH\x01R\n" +
	"isWorknode\x88\x01\x01\x12\x13\n" +
	"\x02id\x18\x03 \x01(\tH\x02R\x02id\x88\x01\x01B\f\n" +
	"\n" +
	"_work_planB\x0e\n" +
	"\f_is_worknodeB\x05\n" +
	"\x03_id\"o\n" +
	"\fStageAttempt\x126\n" +
	"\x05stage\x18\x01 \x01(\v2\x1b.turboci.graph.ids.v1.StageH\x00R\x05stage\x88\x01\x01\x12\x15\n" +
	"\x03idx\x18\x02 \x01(\x05H\x01R\x03idx\x88\x01\x01B\b\n" +
	"\x06_stageB\x06\n" +
	"\x04_idx\"\x94\x01\n" +
	"\tStageEdit\x126\n" +
	"\x05stage\x18\x01 \x01(\v2\x1b.turboci.graph.ids.v1.StageH\x00R\x05stage\x88\x01\x01\x129\n" +
	"\aversion\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\aversion\x88\x01\x01B\b\n" +
	"\x06_stageB\n" +
	"\n" +
	"\b_versionB7P\x01Z3go.chromium.org/turboci/proto/go/graph/ids/v1;idspbb\x06proto3"

var file_turboci_graph_ids_v1_identifier_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_turboci_graph_ids_v1_identifier_proto_goTypes = []any{
	(*Identifier)(nil),            // 0: turboci.graph.ids.v1.Identifier
	(*WorkPlan)(nil),              // 1: turboci.graph.ids.v1.WorkPlan
	(*Check)(nil),                 // 2: turboci.graph.ids.v1.Check
	(*CheckResult)(nil),           // 3: turboci.graph.ids.v1.CheckResult
	(*CheckEdit)(nil),             // 4: turboci.graph.ids.v1.CheckEdit
	(*Stage)(nil),                 // 5: turboci.graph.ids.v1.Stage
	(*StageAttempt)(nil),          // 6: turboci.graph.ids.v1.StageAttempt
	(*StageEdit)(nil),             // 7: turboci.graph.ids.v1.StageEdit
	(*timestamppb.Timestamp)(nil), // 8: google.protobuf.Timestamp
}
var file_turboci_graph_ids_v1_identifier_proto_depIdxs = []int32{
	1,  // 0: turboci.graph.ids.v1.Identifier.work_plan:type_name -> turboci.graph.ids.v1.WorkPlan
	2,  // 1: turboci.graph.ids.v1.Identifier.check:type_name -> turboci.graph.ids.v1.Check
	3,  // 2: turboci.graph.ids.v1.Identifier.check_result:type_name -> turboci.graph.ids.v1.CheckResult
	4,  // 3: turboci.graph.ids.v1.Identifier.check_edit:type_name -> turboci.graph.ids.v1.CheckEdit
	5,  // 4: turboci.graph.ids.v1.Identifier.stage:type_name -> turboci.graph.ids.v1.Stage
	6,  // 5: turboci.graph.ids.v1.Identifier.stage_attempt:type_name -> turboci.graph.ids.v1.StageAttempt
	7,  // 6: turboci.graph.ids.v1.Identifier.stage_edit:type_name -> turboci.graph.ids.v1.StageEdit
	1,  // 7: turboci.graph.ids.v1.Check.work_plan:type_name -> turboci.graph.ids.v1.WorkPlan
	2,  // 8: turboci.graph.ids.v1.CheckResult.check:type_name -> turboci.graph.ids.v1.Check
	2,  // 9: turboci.graph.ids.v1.CheckEdit.check:type_name -> turboci.graph.ids.v1.Check
	8,  // 10: turboci.graph.ids.v1.CheckEdit.version:type_name -> google.protobuf.Timestamp
	1,  // 11: turboci.graph.ids.v1.Stage.work_plan:type_name -> turboci.graph.ids.v1.WorkPlan
	5,  // 12: turboci.graph.ids.v1.StageAttempt.stage:type_name -> turboci.graph.ids.v1.Stage
	5,  // 13: turboci.graph.ids.v1.StageEdit.stage:type_name -> turboci.graph.ids.v1.Stage
	8,  // 14: turboci.graph.ids.v1.StageEdit.version:type_name -> google.protobuf.Timestamp
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_turboci_graph_ids_v1_identifier_proto_init() }
func file_turboci_graph_ids_v1_identifier_proto_init() {
	if File_turboci_graph_ids_v1_identifier_proto != nil {
		return
	}
	file_turboci_graph_ids_v1_identifier_proto_msgTypes[0].OneofWrappers = []any{
		(*identifier_WorkPlan)(nil),
		(*identifier_Check)(nil),
		(*identifier_CheckResult)(nil),
		(*identifier_CheckEdit)(nil),
		(*identifier_Stage)(nil),
		(*identifier_StageAttempt)(nil),
		(*identifier_StageEdit)(nil),
	}
	file_turboci_graph_ids_v1_identifier_proto_msgTypes[1].OneofWrappers = []any{}
	file_turboci_graph_ids_v1_identifier_proto_msgTypes[2].OneofWrappers = []any{}
	file_turboci_graph_ids_v1_identifier_proto_msgTypes[3].OneofWrappers = []any{}
	file_turboci_graph_ids_v1_identifier_proto_msgTypes[4].OneofWrappers = []any{}
	file_turboci_graph_ids_v1_identifier_proto_msgTypes[5].OneofWrappers = []any{}
	file_turboci_graph_ids_v1_identifier_proto_msgTypes[6].OneofWrappers = []any{}
	file_turboci_graph_ids_v1_identifier_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_turboci_graph_ids_v1_identifier_proto_rawDesc), len(file_turboci_graph_ids_v1_identifier_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_turboci_graph_ids_v1_identifier_proto_goTypes,
		DependencyIndexes: file_turboci_graph_ids_v1_identifier_proto_depIdxs,
		MessageInfos:      file_turboci_graph_ids_v1_identifier_proto_msgTypes,
	}.Build()
	File_turboci_graph_ids_v1_identifier_proto = out.File
	file_turboci_graph_ids_v1_identifier_proto_goTypes = nil
	file_turboci_graph_ids_v1_identifier_proto_depIdxs = nil
}
