// Copyright 2025 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: turboci/graph/ids/v1/identifier_kind.proto

package idspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// IdentifierKind enumerates the different kinds of Identifiers, and is used to
// annotate fields containing Edges to indicate which kinds of nodes are
// allowed.
//
// This should be kept in sync with the `type` oneof in Identifier.
type IdentifierKind int32

const (
	// Default value.
	IdentifierKind_IDENTIFIER_KIND_UNKNOWN IdentifierKind = 0
	// An Identifier.WorkPlan.
	IdentifierKind_IDENTIFIER_KIND_WORK_PLAN IdentifierKind = 1
	// An Identifier.Check.
	IdentifierKind_IDENTIFIER_KIND_CHECK IdentifierKind = 2
	// An Identifier.CheckOption.
	IdentifierKind_IDENTIFIER_KIND_CHECK_OPTION IdentifierKind = 3
	// An Identifier.CheckResult.
	IdentifierKind_IDENTIFIER_KIND_CHECK_RESULT IdentifierKind = 4
	// An Identifier.CheckResultDatum.
	IdentifierKind_IDENTIFIER_KIND_CHECK_RESULT_DATUM IdentifierKind = 5
	// An Identifier.CheckEdit.
	IdentifierKind_IDENTIFIER_KIND_CHECK_EDIT IdentifierKind = 6
	// An Identifier.CheckEditOption.
	IdentifierKind_IDENTIFIER_KIND_CHECK_EDIT_OPTION IdentifierKind = 7
	// An Identifier.CheckEditReason
	IdentifierKind_IDENTIFIER_KIND_CHECK_EDIT_REASON IdentifierKind = 11
	// An Identifier.Stage.
	IdentifierKind_IDENTIFIER_KIND_STAGE IdentifierKind = 8
	// An Identifier.StageAttempt.
	IdentifierKind_IDENTIFIER_KIND_STAGE_ATTEMPT IdentifierKind = 9
	// An Identifier.StageEdit.
	IdentifierKind_IDENTIFIER_KIND_STAGE_EDIT IdentifierKind = 10
	// An Identifier.StageEditReason
	IdentifierKind_IDENTIFIER_KIND_STAGE_EDIT_REASON IdentifierKind = 12
)

// Enum value maps for IdentifierKind.
var (
	IdentifierKind_name = map[int32]string{
		0:  "IDENTIFIER_KIND_UNKNOWN",
		1:  "IDENTIFIER_KIND_WORK_PLAN",
		2:  "IDENTIFIER_KIND_CHECK",
		3:  "IDENTIFIER_KIND_CHECK_OPTION",
		4:  "IDENTIFIER_KIND_CHECK_RESULT",
		5:  "IDENTIFIER_KIND_CHECK_RESULT_DATUM",
		6:  "IDENTIFIER_KIND_CHECK_EDIT",
		7:  "IDENTIFIER_KIND_CHECK_EDIT_OPTION",
		11: "IDENTIFIER_KIND_CHECK_EDIT_REASON",
		8:  "IDENTIFIER_KIND_STAGE",
		9:  "IDENTIFIER_KIND_STAGE_ATTEMPT",
		10: "IDENTIFIER_KIND_STAGE_EDIT",
		12: "IDENTIFIER_KIND_STAGE_EDIT_REASON",
	}
	IdentifierKind_value = map[string]int32{
		"IDENTIFIER_KIND_UNKNOWN":            0,
		"IDENTIFIER_KIND_WORK_PLAN":          1,
		"IDENTIFIER_KIND_CHECK":              2,
		"IDENTIFIER_KIND_CHECK_OPTION":       3,
		"IDENTIFIER_KIND_CHECK_RESULT":       4,
		"IDENTIFIER_KIND_CHECK_RESULT_DATUM": 5,
		"IDENTIFIER_KIND_CHECK_EDIT":         6,
		"IDENTIFIER_KIND_CHECK_EDIT_OPTION":  7,
		"IDENTIFIER_KIND_CHECK_EDIT_REASON":  11,
		"IDENTIFIER_KIND_STAGE":              8,
		"IDENTIFIER_KIND_STAGE_ATTEMPT":      9,
		"IDENTIFIER_KIND_STAGE_EDIT":         10,
		"IDENTIFIER_KIND_STAGE_EDIT_REASON":  12,
	}
)

func (x IdentifierKind) Enum() *IdentifierKind {
	p := new(IdentifierKind)
	*p = x
	return p
}

func (x IdentifierKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IdentifierKind) Descriptor() protoreflect.EnumDescriptor {
	return file_turboci_graph_ids_v1_identifier_kind_proto_enumTypes[0].Descriptor()
}

func (IdentifierKind) Type() protoreflect.EnumType {
	return &file_turboci_graph_ids_v1_identifier_kind_proto_enumTypes[0]
}

func (x IdentifierKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

var File_turboci_graph_ids_v1_identifier_kind_proto protoreflect.FileDescriptor

const file_turboci_graph_ids_v1_identifier_kind_proto_rawDesc = "" +
	"\n" +
	"*turboci/graph/ids/v1/identifier_kind.proto\x12\x14turboci.graph.ids.v1*\xc6\x03\n" +
	"\x0eIdentifierKind\x12\x1b\n" +
	"\x17IDENTIFIER_KIND_UNKNOWN\x10\x00\x12\x1d\n" +
	"\x19IDENTIFIER_KIND_WORK_PLAN\x10\x01\x12\x19\n" +
	"\x15IDENTIFIER_KIND_CHECK\x10\x02\x12 \n" +
	"\x1cIDENTIFIER_KIND_CHECK_OPTION\x10\x03\x12 \n" +
	"\x1cIDENTIFIER_KIND_CHECK_RESULT\x10\x04\x12&\n" +
	"\"IDENTIFIER_KIND_CHECK_RESULT_DATUM\x10\x05\x12\x1e\n" +
	"\x1aIDENTIFIER_KIND_CHECK_EDIT\x10\x06\x12%\n" +
	"!IDENTIFIER_KIND_CHECK_EDIT_OPTION\x10\a\x12%\n" +
	"!IDENTIFIER_KIND_CHECK_EDIT_REASON\x10\v\x12\x19\n" +
	"\x15IDENTIFIER_KIND_STAGE\x10\b\x12!\n" +
	"\x1dIDENTIFIER_KIND_STAGE_ATTEMPT\x10\t\x12\x1e\n" +
	"\x1aIDENTIFIER_KIND_STAGE_EDIT\x10\n" +
	"\x12%\n" +
	"!IDENTIFIER_KIND_STAGE_EDIT_REASON\x10\fB7P\x01Z3go.chromium.org/turboci/proto/go/graph/ids/v1;idspbb\x06proto3"

var file_turboci_graph_ids_v1_identifier_kind_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_turboci_graph_ids_v1_identifier_kind_proto_goTypes = []any{
	(IdentifierKind)(0), // 0: turboci.graph.ids.v1.IdentifierKind
}
var file_turboci_graph_ids_v1_identifier_kind_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_turboci_graph_ids_v1_identifier_kind_proto_init() }
func file_turboci_graph_ids_v1_identifier_kind_proto_init() {
	if File_turboci_graph_ids_v1_identifier_kind_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_turboci_graph_ids_v1_identifier_kind_proto_rawDesc), len(file_turboci_graph_ids_v1_identifier_kind_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_turboci_graph_ids_v1_identifier_kind_proto_goTypes,
		DependencyIndexes: file_turboci_graph_ids_v1_identifier_kind_proto_depIdxs,
		EnumInfos:         file_turboci_graph_ids_v1_identifier_kind_proto_enumTypes,
	}.Build()
	File_turboci_graph_ids_v1_identifier_kind_proto = out.File
	file_turboci_graph_ids_v1_identifier_kind_proto_goTypes = nil
	file_turboci_graph_ids_v1_identifier_kind_proto_depIdxs = nil
}
