# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: turboci/graph/executor/v1/cancel_stage.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'turboci/graph/executor/v1/cancel_stage.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from turboci.graph.ids.v1 import identifier_pb2 as turboci_dot_graph_dot_ids_dot_v1_dot_identifier__pb2
from turboci.graph.orchestrator.v1 import stage_pb2 as turboci_dot_graph_dot_orchestrator_dot_v1_dot_stage__pb2
from turboci.graph.orchestrator.v1 import value_data_pb2 as turboci_dot_graph_dot_orchestrator_dot_v1_dot_value__data__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,turboci/graph/executor/v1/cancel_stage.proto\x12\x19turboci.graph.executor.v1\x1a%turboci/graph/ids/v1/identifier.proto\x1a)turboci/graph/orchestrator/v1/stage.proto\x1a.turboci/graph/orchestrator/v1/value_data.proto\"\x86\x03\n\x12\x43\x61ncelStageRequest\x12\x38\n\x05stage\x18\x01 \x01(\x0b\x32$.turboci.graph.orchestrator.v1.StageH\x00\x88\x01\x01\x12P\n\nvalue_data\x18\x04 \x03(\x0b\x32<.turboci.graph.executor.v1.CancelStageRequest.ValueDataEntry\x12\x38\n\x07\x61ttempt\x18\x02 \x01(\x0b\x32\".turboci.graph.ids.v1.StageAttemptH\x01\x88\x01\x01\x12 \n\x13stage_attempt_token\x18\x03 \x01(\tH\x02\x88\x01\x01\x1aZ\n\x0eValueDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x37\n\x05value\x18\x02 \x01(\x0b\x32(.turboci.graph.orchestrator.v1.ValueData:\x02\x38\x01\x42\x08\n\x06_stageB\n\n\x08_attemptB\x16\n\x14_stage_attempt_token\"\x15\n\x13\x43\x61ncelStageResponseBAP\x01Z=go.chromium.org/turboci/proto/go/graph/executor/v1;executorpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'turboci.graph.executor.v1.cancel_stage_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'P\001Z=go.chromium.org/turboci/proto/go/graph/executor/v1;executorpb'
  _globals['_CANCELSTAGEREQUEST_VALUEDATAENTRY']._loaded_options = None
  _globals['_CANCELSTAGEREQUEST_VALUEDATAENTRY']._serialized_options = b'8\001'
  _globals['_CANCELSTAGEREQUEST']._serialized_start=206
  _globals['_CANCELSTAGEREQUEST']._serialized_end=596
  _globals['_CANCELSTAGEREQUEST_VALUEDATAENTRY']._serialized_start=460
  _globals['_CANCELSTAGEREQUEST_VALUEDATAENTRY']._serialized_end=550
  _globals['_CANCELSTAGERESPONSE']._serialized_start=598
  _globals['_CANCELSTAGERESPONSE']._serialized_end=619
# @@protoc_insertion_point(module_scope)
