# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: turboci/graph/executor/v1/turbo_ci_stage_executor_service.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'turboci/graph/executor/v1/turbo_ci_stage_executor_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from turboci.graph.executor.v1 import cancel_stage_pb2 as turboci_dot_graph_dot_executor_dot_v1_dot_cancel__stage__pb2
from turboci.graph.executor.v1 import run_stage_pb2 as turboci_dot_graph_dot_executor_dot_v1_dot_run__stage__pb2
from turboci.graph.executor.v1 import validate_stage_pb2 as turboci_dot_graph_dot_executor_dot_v1_dot_validate__stage__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n?turboci/graph/executor/v1/turbo_ci_stage_executor_service.proto\x12\x19turboci.graph.executor.v1\x1a,turboci/graph/executor/v1/cancel_stage.proto\x1a)turboci/graph/executor/v1/run_stage.proto\x1a.turboci/graph/executor/v1/validate_stage.proto2\xe3\x02\n\x14TurboCIStageExecutor\x12t\n\rValidateStage\x12/.turboci.graph.executor.v1.ValidateStageRequest\x1a\x30.turboci.graph.executor.v1.ValidateStageResponse\"\x00\x12\x65\n\x08RunStage\x12*.turboci.graph.executor.v1.RunStageRequest\x1a+.turboci.graph.executor.v1.RunStageResponse\"\x00\x12n\n\x0b\x43\x61ncelStage\x12-.turboci.graph.executor.v1.CancelStageRequest\x1a..turboci.graph.executor.v1.CancelStageResponse\"\x00\x42LP\x01ZHgo.chromium.org/turboci/proto/go/graph/executor/v1/grpcpb;executorgrpcpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'turboci.graph.executor.v1.turbo_ci_stage_executor_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'P\001ZHgo.chromium.org/turboci/proto/go/graph/executor/v1/grpcpb;executorgrpcpb'
  _globals['_TURBOCISTAGEEXECUTOR']._serialized_start=232
  _globals['_TURBOCISTAGEEXECUTOR']._serialized_end=587
# @@protoc_insertion_point(module_scope)
