// Copyright 2025 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package turboci.graph.orchestrator.v1;

import "turboci/graph/ids/v1/identifier.proto";

option go_package = "go.chromium.org/turboci/proto/go/graph/orchestrator/v1;orchestratorpb";
option java_multiple_files = true;

// Edge is a singular pointer to some node with an Identifier.
//
// Typically Edges must always point to nodes in the same graph, though this may
// be lifted in the future.
message Edge {
  // Target indicates the node that this Edge points to.
  //
  // Currently only Checks and Stages are supported.
  optional ids.v1.Identifier target = 1;

  // TODO: Add a way to set a condition on this edge.
  //
  // For now let's start with resolving edges when `target.state` is it's FINAL
  // variant. I suspect that we'll quickly need to at least change which state
  // we depend on (e.g. for Stages I think we will want to depend on
  // `STAGE_STATE_WAITING_FOR_GROUP` in order to add Stages which don't start
  // until after the current Stage finishes execution).
  //
  // message Condition {
  //   // selected minimum state must match the type of `target`.
  //   // required. Prior to this state this Condition is unfulfilled.
  //   //
  //   // At/After this state the Condition will be resolved to either true or
  //   // false.
  //   oneof min_state {
  //     CheckState minimum_check_state = 1;
  //     StageState minimum_stage_state = 2;
  //   }
  //
  //   // CEL: https://github.com/google/cel-spec
  //   //
  //   // Will be statically checked against check/stage fields which are
  //   // immutable at `min_state`.
  //   //
  //   // Will be evaluated exactly once on `target` when it reaches the minimum
  //   // state.
  //   string expression = 2;
  // }
}
