// Copyright 2025 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package turboci.graph.orchestrator.v1;

option go_package = "go.chromium.org/turboci/proto/go/graph/orchestrator/v1;orchestratorpb";
option java_multiple_files = true;

// Failure is for stage attempt execution failure information.
//
// Note: this message is not intended to be used for workflow-level failures.
// For example if a stage attempt finishes everything it is intended to do
// (i.e. to run a suite of tests), and it produces some failure
// results (i.e. some tests failed), those results should be reported to the
// corresponding check's result.Data, not here.
message Failure {
  // Human-readable error message.
  optional string message = 1;

  // Type of the failure.
  oneof type {
    // Failure to transition a stage attempt to SCHEDULED state.
    ToScheduled to_scheduled = 2;
    // Failure to transition a stage attempt to RUNNING state.
    ToRunning to_running = 3;
    // TODO: add more failure types when needed.
  }
}

// Failure to transition a stage attempt to SCHEDULED state.
// Can be used by:
// * the Stage Executor to update a stage attempt if it fails to schedule the
//   execution for it.
// * the Orchestrator to update
//   * a stage attempt if it exceeds its execution_policy.Timeout.PendingThrottled.
//   * a check's result from this failed stage attempt.
message ToScheduled {}

// Failure to transition a stage attempt to RUNNING state.
// Can be used by:
// * the Stage Executor to update a stage attempt if it fails to execute.
// * the Orchestrator to update
//   * a stage attempt if it exceeds its execution_policy.Timeout.Scheduled.
//   * a check's result from this failed stage attempt.
message ToRunning {}
