# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: turboci/graph/orchestrator/v1/actor.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'turboci/graph/orchestrator/v1/actor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from turboci.graph.ids.v1 import identifier_pb2 as turboci_dot_graph_dot_ids_dot_v1_dot_identifier__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)turboci/graph/orchestrator/v1/actor.proto\x12\x1dturboci.graph.orchestrator.v1\x1a%turboci/graph/ids/v1/identifier.proto\"\xca\x03\n\x05\x41\x63tor\x12;\n\rstage_attempt\x18\x01 \x01(\x0b\x32\".turboci.graph.ids.v1.StageAttemptH\x00\x12I\n\x0corchestrator\x18\x02 \x01(\x0b\x32\x31.turboci.graph.orchestrator.v1.Actor.OrchestratorH\x00\x12P\n\x10workplan_creator\x18\x03 \x01(\x0b\x32\x34.turboci.graph.orchestrator.v1.Actor.WorkplanCreatorH\x00\x12\x41\n\x08\x65xternal\x18\x04 \x01(\x0b\x32-.turboci.graph.orchestrator.v1.Actor.ExternalH\x00\x12W\n\x14legacy_workplan_user\x18\x05 \x01(\x0b\x32\x37.turboci.graph.orchestrator.v1.Actor.LegacyWorkplanUserH\x00\x1a\x0e\n\x0cOrchestrator\x1a\x11\n\x0fWorkplanCreator\x1a\n\n\x08\x45xternal\x1a\x14\n\x12LegacyWorkplanUserB\x06\n\x04kindBIP\x01ZEgo.chromium.org/turboci/proto/go/graph/orchestrator/v1;orchestratorpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'turboci.graph.orchestrator.v1.actor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'P\001ZEgo.chromium.org/turboci/proto/go/graph/orchestrator/v1;orchestratorpb'
  _globals['_ACTOR']._serialized_start=116
  _globals['_ACTOR']._serialized_end=574
  _globals['_ACTOR_ORCHESTRATOR']._serialized_start=499
  _globals['_ACTOR_ORCHESTRATOR']._serialized_end=513
  _globals['_ACTOR_WORKPLANCREATOR']._serialized_start=515
  _globals['_ACTOR_WORKPLANCREATOR']._serialized_end=532
  _globals['_ACTOR_EXTERNAL']._serialized_start=534
  _globals['_ACTOR_EXTERNAL']._serialized_end=544
  _globals['_ACTOR_LEGACYWORKPLANUSER']._serialized_start=546
  _globals['_ACTOR_LEGACYWORKPLANUSER']._serialized_end=566
# @@protoc_insertion_point(module_scope)
