# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: turboci/graph/orchestrator/v1/query_nodes_request.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'turboci/graph/orchestrator/v1/query_nodes_request.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from turboci.graph.orchestrator.v1 import query_pb2 as turboci_dot_graph_dot_orchestrator_dot_v1_dot_query__pb2
from turboci.graph.orchestrator.v1 import revision_pb2 as turboci_dot_graph_dot_orchestrator_dot_v1_dot_revision__pb2
from turboci.graph.orchestrator.v1 import type_info_pb2 as turboci_dot_graph_dot_orchestrator_dot_v1_dot_type__info__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n7turboci/graph/orchestrator/v1/query_nodes_request.proto\x12\x1dturboci.graph.orchestrator.v1\x1a)turboci/graph/orchestrator/v1/query.proto\x1a,turboci/graph/orchestrator/v1/revision.proto\x1a-turboci/graph/orchestrator/v1/type_info.proto\"\xbb\x03\n\x11QueryNodesRequest\x12\x12\n\x05token\x18\x01 \x01(\tH\x00\x88\x01\x01\x12?\n\ttype_info\x18\x02 \x01(\x0b\x32\'.turboci.graph.orchestrator.v1.TypeInfoH\x01\x88\x01\x01\x12Y\n\x07version\x18\x03 \x01(\x0b\x32\x43.turboci.graph.orchestrator.v1.QueryNodesRequest.VersionRestrictionH\x02\x88\x01\x01\x12\x33\n\x05query\x18\x04 \x03(\x0b\x32$.turboci.graph.orchestrator.v1.Query\x1a\x9c\x01\n\x12VersionRestriction\x12:\n\x07require\x18\x01 \x01(\x0b\x32\'.turboci.graph.orchestrator.v1.RevisionH\x00\x12;\n\x08snapshot\x18\x02 \x01(\x0b\x32\'.turboci.graph.orchestrator.v1.RevisionH\x00\x42\r\n\x0brestrictionB\x08\n\x06_tokenB\x0c\n\n_type_infoB\n\n\x08_versionBIP\x01ZEgo.chromium.org/turboci/proto/go/graph/orchestrator/v1;orchestratorpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'turboci.graph.orchestrator.v1.query_nodes_request_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'P\001ZEgo.chromium.org/turboci/proto/go/graph/orchestrator/v1;orchestratorpb'
  _globals['_QUERYNODESREQUEST']._serialized_start=227
  _globals['_QUERYNODESREQUEST']._serialized_end=670
  _globals['_QUERYNODESREQUEST_VERSIONRESTRICTION']._serialized_start=478
  _globals['_QUERYNODESREQUEST_VERSIONRESTRICTION']._serialized_end=634
# @@protoc_insertion_point(module_scope)
