from turboci.graph.orchestrator.v1 import allocate_worknode_ids_request_pb2 as _allocate_worknode_ids_request_pb2
from turboci.graph.orchestrator.v1 import allocate_worknode_ids_response_pb2 as _allocate_worknode_ids_response_pb2
from turboci.graph.orchestrator.v1 import create_workplan_request_pb2 as _create_workplan_request_pb2
from turboci.graph.orchestrator.v1 import create_workplan_response_pb2 as _create_workplan_response_pb2
from turboci.graph.orchestrator.v1 import query_nodes_request_pb2 as _query_nodes_request_pb2
from turboci.graph.orchestrator.v1 import query_nodes_response_pb2 as _query_nodes_response_pb2
from turboci.graph.orchestrator.v1 import read_workplan_request_pb2 as _read_workplan_request_pb2
from turboci.graph.orchestrator.v1 import read_workplan_response_pb2 as _read_workplan_response_pb2
from turboci.graph.orchestrator.v1 import write_nodes_request_pb2 as _write_nodes_request_pb2
from turboci.graph.orchestrator.v1 import write_nodes_response_pb2 as _write_nodes_response_pb2
from google.protobuf import descriptor as _descriptor
from typing import ClassVar as _ClassVar

DESCRIPTOR: _descriptor.FileDescriptor
