// Copyright 2026 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: turboci/graph/orchestrator/v1/builtin_executor.proto

package orchestratorpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// BuiltinExecutor enumerates stage kinds that Orchestrator implements natively.
type BuiltinExecutor int32

const (
	// UNKNOWN is the same as "the stage is implemented by an external executor".
	BuiltinExecutor_BUILTIN_EXECUTOR_UNKNOWN BuiltinExecutor = 0
	// This executor just immediately finishes the stage (with a single COMPLETE
	// attempt) as soon as the stage is unblocked.
	//
	// By being a builtin executor, it can do so in the same transaction that
	// unblocks the stage, skipping a lot of overhead associated with actually
	// launching a real attempt.
	//
	// Noop stage are useful for grouping dependencies. A stage with a particular
	// args type URL can be defined as a noop by setting `noop: true` in the stage
	// registry config entry for this type URL.
	BuiltinExecutor_BUILTIN_EXECUTOR_NOOP BuiltinExecutor = 1
)

// Enum value maps for BuiltinExecutor.
var (
	BuiltinExecutor_name = map[int32]string{
		0: "BUILTIN_EXECUTOR_UNKNOWN",
		1: "BUILTIN_EXECUTOR_NOOP",
	}
	BuiltinExecutor_value = map[string]int32{
		"BUILTIN_EXECUTOR_UNKNOWN": 0,
		"BUILTIN_EXECUTOR_NOOP":    1,
	}
)

func (x BuiltinExecutor) Enum() *BuiltinExecutor {
	p := new(BuiltinExecutor)
	*p = x
	return p
}

func (x BuiltinExecutor) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BuiltinExecutor) Descriptor() protoreflect.EnumDescriptor {
	return file_turboci_graph_orchestrator_v1_builtin_executor_proto_enumTypes[0].Descriptor()
}

func (BuiltinExecutor) Type() protoreflect.EnumType {
	return &file_turboci_graph_orchestrator_v1_builtin_executor_proto_enumTypes[0]
}

func (x BuiltinExecutor) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

var File_turboci_graph_orchestrator_v1_builtin_executor_proto protoreflect.FileDescriptor

const file_turboci_graph_orchestrator_v1_builtin_executor_proto_rawDesc = "" +
	"\n" +
	"4turboci/graph/orchestrator/v1/builtin_executor.proto\x12\x1dturboci.graph.orchestrator.v1*J\n" +
	"\x0fBuiltinExecutor\x12\x1c\n" +
	"\x18BUILTIN_EXECUTOR_UNKNOWN\x10\x00\x12\x19\n" +
	"\x15BUILTIN_EXECUTOR_NOOP\x10\x01BIP\x01ZEgo.chromium.org/turboci/proto/go/graph/orchestrator/v1;orchestratorpbb\x06proto3"

var file_turboci_graph_orchestrator_v1_builtin_executor_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_turboci_graph_orchestrator_v1_builtin_executor_proto_goTypes = []any{
	(BuiltinExecutor)(0), // 0: turboci.graph.orchestrator.v1.BuiltinExecutor
}
var file_turboci_graph_orchestrator_v1_builtin_executor_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_turboci_graph_orchestrator_v1_builtin_executor_proto_init() }
func file_turboci_graph_orchestrator_v1_builtin_executor_proto_init() {
	if File_turboci_graph_orchestrator_v1_builtin_executor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_turboci_graph_orchestrator_v1_builtin_executor_proto_rawDesc), len(file_turboci_graph_orchestrator_v1_builtin_executor_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_turboci_graph_orchestrator_v1_builtin_executor_proto_goTypes,
		DependencyIndexes: file_turboci_graph_orchestrator_v1_builtin_executor_proto_depIdxs,
		EnumInfos:         file_turboci_graph_orchestrator_v1_builtin_executor_proto_enumTypes,
	}.Build()
	File_turboci_graph_orchestrator_v1_builtin_executor_proto = out.File
	file_turboci_graph_orchestrator_v1_builtin_executor_proto_goTypes = nil
	file_turboci_graph_orchestrator_v1_builtin_executor_proto_depIdxs = nil
}
