// Copyright 2025 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: turboci/graph/orchestrator/v1/check_view.proto

package orchestratorpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CheckView is a collated, partial, view of a single Check and the nodes
// which belong to it.
type CheckView struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Check *Check                 `protobuf:"bytes,1,opt,name=check,proto3,oneof"`
	xxx_hidden_Edits *[]*Edit               `protobuf:"bytes,2,rep,name=edits,proto3"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CheckView) Reset() {
	*x = CheckView{}
	mi := &file_turboci_graph_orchestrator_v1_check_view_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckView) ProtoMessage() {}

func (x *CheckView) ProtoReflect() protoreflect.Message {
	mi := &file_turboci_graph_orchestrator_v1_check_view_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CheckView) GetCheck() *Check {
	if x != nil {
		return x.xxx_hidden_Check
	}
	return nil
}

func (x *CheckView) GetEdits() []*Edit {
	if x != nil {
		if x.xxx_hidden_Edits != nil {
			return *x.xxx_hidden_Edits
		}
	}
	return nil
}

func (x *CheckView) SetCheck(v *Check) {
	x.xxx_hidden_Check = v
}

func (x *CheckView) SetEdits(v []*Edit) {
	x.xxx_hidden_Edits = &v
}

func (x *CheckView) HasCheck() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Check != nil
}

func (x *CheckView) ClearCheck() {
	x.xxx_hidden_Check = nil
}

type CheckView_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The Check itself - always present.
	Check *Check
	// CheckEdits for this Check.
	//
	// Sorted by `version`.
	Edits []*Edit
}

func (b0 CheckView_builder) Build() *CheckView {
	m0 := &CheckView{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Check = b.Check
	x.xxx_hidden_Edits = &b.Edits
	return m0
}

var File_turboci_graph_orchestrator_v1_check_view_proto protoreflect.FileDescriptor

const file_turboci_graph_orchestrator_v1_check_view_proto_rawDesc = "" +
	"\n" +
	".turboci/graph/orchestrator/v1/check_view.proto\x12\x1dturboci.graph.orchestrator.v1\x1a)turboci/graph/orchestrator/v1/check.proto\x1a(turboci/graph/orchestrator/v1/edit.proto\"\x91\x01\n" +
	"\tCheckView\x12?\n" +
	"\x05check\x18\x01 \x01(\v2$.turboci.graph.orchestrator.v1.CheckH\x00R\x05check\x88\x01\x01\x129\n" +
	"\x05edits\x18\x02 \x03(\v2#.turboci.graph.orchestrator.v1.EditR\x05editsB\b\n" +
	"\x06_checkBIP\x01ZEgo.chromium.org/turboci/proto/go/graph/orchestrator/v1;orchestratorpbb\x06proto3"

var file_turboci_graph_orchestrator_v1_check_view_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_turboci_graph_orchestrator_v1_check_view_proto_goTypes = []any{
	(*CheckView)(nil), // 0: turboci.graph.orchestrator.v1.CheckView
	(*Check)(nil),     // 1: turboci.graph.orchestrator.v1.Check
	(*Edit)(nil),      // 2: turboci.graph.orchestrator.v1.Edit
}
var file_turboci_graph_orchestrator_v1_check_view_proto_depIdxs = []int32{
	1, // 0: turboci.graph.orchestrator.v1.CheckView.check:type_name -> turboci.graph.orchestrator.v1.Check
	2, // 1: turboci.graph.orchestrator.v1.CheckView.edits:type_name -> turboci.graph.orchestrator.v1.Edit
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_turboci_graph_orchestrator_v1_check_view_proto_init() }
func file_turboci_graph_orchestrator_v1_check_view_proto_init() {
	if File_turboci_graph_orchestrator_v1_check_view_proto != nil {
		return
	}
	file_turboci_graph_orchestrator_v1_check_proto_init()
	file_turboci_graph_orchestrator_v1_edit_proto_init()
	file_turboci_graph_orchestrator_v1_check_view_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_turboci_graph_orchestrator_v1_check_view_proto_rawDesc), len(file_turboci_graph_orchestrator_v1_check_view_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_turboci_graph_orchestrator_v1_check_view_proto_goTypes,
		DependencyIndexes: file_turboci_graph_orchestrator_v1_check_view_proto_depIdxs,
		MessageInfos:      file_turboci_graph_orchestrator_v1_check_view_proto_msgTypes,
	}.Build()
	File_turboci_graph_orchestrator_v1_check_view_proto = out.File
	file_turboci_graph_orchestrator_v1_check_view_proto_goTypes = nil
	file_turboci_graph_orchestrator_v1_check_view_proto_depIdxs = nil
}
