// Copyright 2025 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: turboci/graph/orchestrator/v1/check_view.proto

package orchestratorpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CheckView is a collated, partial, view of a single Check and the nodes
// which belong to it.
type CheckView struct {
	state                 protoimpl.MessageState     `protogen:"opaque.v1"`
	xxx_hidden_Check      *Check                     `protobuf:"bytes,1,opt,name=check,proto3,oneof"`
	xxx_hidden_OptionData map[string]*Datum          `protobuf:"bytes,2,rep,name=option_data,json=optionData,proto3" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	xxx_hidden_Edits      *[]*CheckEditView          `protobuf:"bytes,3,rep,name=edits,proto3"`
	xxx_hidden_Results    map[int32]*CheckResultView `protobuf:"bytes,4,rep,name=results,proto3" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *CheckView) Reset() {
	*x = CheckView{}
	mi := &file_turboci_graph_orchestrator_v1_check_view_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckView) ProtoMessage() {}

func (x *CheckView) ProtoReflect() protoreflect.Message {
	mi := &file_turboci_graph_orchestrator_v1_check_view_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CheckView) GetCheck() *Check {
	if x != nil {
		return x.xxx_hidden_Check
	}
	return nil
}

func (x *CheckView) GetOptionData() map[string]*Datum {
	if x != nil {
		return x.xxx_hidden_OptionData
	}
	return nil
}

func (x *CheckView) GetEdits() []*CheckEditView {
	if x != nil {
		if x.xxx_hidden_Edits != nil {
			return *x.xxx_hidden_Edits
		}
	}
	return nil
}

func (x *CheckView) GetResults() map[int32]*CheckResultView {
	if x != nil {
		return x.xxx_hidden_Results
	}
	return nil
}

func (x *CheckView) SetCheck(v *Check) {
	x.xxx_hidden_Check = v
}

func (x *CheckView) SetOptionData(v map[string]*Datum) {
	x.xxx_hidden_OptionData = v
}

func (x *CheckView) SetEdits(v []*CheckEditView) {
	x.xxx_hidden_Edits = &v
}

func (x *CheckView) SetResults(v map[int32]*CheckResultView) {
	x.xxx_hidden_Results = v
}

func (x *CheckView) HasCheck() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Check != nil
}

func (x *CheckView) ClearCheck() {
	x.xxx_hidden_Check = nil
}

type CheckView_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The Check itself - always present.
	Check *Check
	// Data for the Check's options which are visible and of a type which was
	// requested.
	//
	// Indexed by type_url.
	//
	// NOTE: If we add an additional distinguisher other than type_url, it will
	// need to also be rendered in this string key. Probably <tag>:<type_url>.
	OptionData map[string]*Datum
	// CheckEdits for this Check.
	//
	// Sorted by `edit.version`.
	Edits []*CheckEditView
	// Result data for this Check.
	//
	// Indexed by `identifier.idx`.
	Results map[int32]*CheckResultView
}

func (b0 CheckView_builder) Build() *CheckView {
	m0 := &CheckView{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Check = b.Check
	x.xxx_hidden_OptionData = b.OptionData
	x.xxx_hidden_Edits = &b.Edits
	x.xxx_hidden_Results = b.Results
	return m0
}

var File_turboci_graph_orchestrator_v1_check_view_proto protoreflect.FileDescriptor

const file_turboci_graph_orchestrator_v1_check_view_proto_rawDesc = "" +
	"\n" +
	".turboci/graph/orchestrator/v1/check_view.proto\x12\x1dturboci.graph.orchestrator.v1\x1a)turboci/graph/orchestrator/v1/check.proto\x1a3turboci/graph/orchestrator/v1/check_edit_view.proto\x1a5turboci/graph/orchestrator/v1/check_result_view.proto\x1a)turboci/graph/orchestrator/v1/datum.proto\"\x97\x04\n" +
	"\tCheckView\x12?\n" +
	"\x05check\x18\x01 \x01(\v2$.turboci.graph.orchestrator.v1.CheckH\x00R\x05check\x88\x01\x01\x12Y\n" +
	"\voption_data\x18\x02 \x03(\v28.turboci.graph.orchestrator.v1.CheckView.OptionDataEntryR\n" +
	"optionData\x12B\n" +
	"\x05edits\x18\x03 \x03(\v2,.turboci.graph.orchestrator.v1.CheckEditViewR\x05edits\x12O\n" +
	"\aresults\x18\x04 \x03(\v25.turboci.graph.orchestrator.v1.CheckView.ResultsEntryR\aresults\x1ac\n" +
	"\x0fOptionDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12:\n" +
	"\x05value\x18\x02 \x01(\v2$.turboci.graph.orchestrator.v1.DatumR\x05value:\x028\x01\x1aj\n" +
	"\fResultsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12D\n" +
	"\x05value\x18\x02 \x01(\v2..turboci.graph.orchestrator.v1.CheckResultViewR\x05value:\x028\x01B\b\n" +
	"\x06_checkBIP\x01ZEgo.chromium.org/turboci/proto/go/graph/orchestrator/v1;orchestratorpbb\x06proto3"

var file_turboci_graph_orchestrator_v1_check_view_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_turboci_graph_orchestrator_v1_check_view_proto_goTypes = []any{
	(*CheckView)(nil),       // 0: turboci.graph.orchestrator.v1.CheckView
	nil,                     // 1: turboci.graph.orchestrator.v1.CheckView.OptionDataEntry
	nil,                     // 2: turboci.graph.orchestrator.v1.CheckView.ResultsEntry
	(*Check)(nil),           // 3: turboci.graph.orchestrator.v1.Check
	(*CheckEditView)(nil),   // 4: turboci.graph.orchestrator.v1.CheckEditView
	(*Datum)(nil),           // 5: turboci.graph.orchestrator.v1.Datum
	(*CheckResultView)(nil), // 6: turboci.graph.orchestrator.v1.CheckResultView
}
var file_turboci_graph_orchestrator_v1_check_view_proto_depIdxs = []int32{
	3, // 0: turboci.graph.orchestrator.v1.CheckView.check:type_name -> turboci.graph.orchestrator.v1.Check
	1, // 1: turboci.graph.orchestrator.v1.CheckView.option_data:type_name -> turboci.graph.orchestrator.v1.CheckView.OptionDataEntry
	4, // 2: turboci.graph.orchestrator.v1.CheckView.edits:type_name -> turboci.graph.orchestrator.v1.CheckEditView
	2, // 3: turboci.graph.orchestrator.v1.CheckView.results:type_name -> turboci.graph.orchestrator.v1.CheckView.ResultsEntry
	5, // 4: turboci.graph.orchestrator.v1.CheckView.OptionDataEntry.value:type_name -> turboci.graph.orchestrator.v1.Datum
	6, // 5: turboci.graph.orchestrator.v1.CheckView.ResultsEntry.value:type_name -> turboci.graph.orchestrator.v1.CheckResultView
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_turboci_graph_orchestrator_v1_check_view_proto_init() }
func file_turboci_graph_orchestrator_v1_check_view_proto_init() {
	if File_turboci_graph_orchestrator_v1_check_view_proto != nil {
		return
	}
	file_turboci_graph_orchestrator_v1_check_proto_init()
	file_turboci_graph_orchestrator_v1_check_edit_view_proto_init()
	file_turboci_graph_orchestrator_v1_check_result_view_proto_init()
	file_turboci_graph_orchestrator_v1_datum_proto_init()
	file_turboci_graph_orchestrator_v1_check_view_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_turboci_graph_orchestrator_v1_check_view_proto_rawDesc), len(file_turboci_graph_orchestrator_v1_check_view_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_turboci_graph_orchestrator_v1_check_view_proto_goTypes,
		DependencyIndexes: file_turboci_graph_orchestrator_v1_check_view_proto_depIdxs,
		MessageInfos:      file_turboci_graph_orchestrator_v1_check_view_proto_msgTypes,
	}.Build()
	File_turboci_graph_orchestrator_v1_check_view_proto = out.File
	file_turboci_graph_orchestrator_v1_check_view_proto_goTypes = nil
	file_turboci_graph_orchestrator_v1_check_view_proto_depIdxs = nil
}
