// Copyright 2025 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: turboci/graph/orchestrator/v1/check_kind.proto

package orchestratorpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CheckKind informs the 'general' type of this Check, independent of whatever
// options it may have.
//
// This serves two primary purposes:
//   - This establishes a colloquial way to refer to Checks (e.g. 'a test check'
//     vs 'a build check').
//   - DataMap type registration can indicate what kinds of Checks that type
//     can be used on, to allow some high-level partitioning; e.g. a TestFilter
//     might only show up on TEST Checks, not SOURCE checks.
type CheckKind int32

const (
	// UNKNOWN is the default, invalid, kind.
	CheckKind_CHECK_KIND_UNKNOWN CheckKind = 0
	// SOURCE is a Check which describes in various detail one or more external
	// inputs to the workflow. Resolving a SOURCE check may include actions like
	// "find all commits with this label set", or "traverse dependency references
	// in these source points to generate a full set of commits/artifacts".
	CheckKind_CHECK_KIND_SOURCE CheckKind = 1
	// BUILD is a Check which transforms some inputs (typically SOURCE checks)
	// into one or more output artifacts.
	CheckKind_CHECK_KIND_BUILD CheckKind = 2
	// TEST is a Check which consumes one or more artifacts (usually from BUILDs)
	// and/or SOURCEs, and determines if these artifacts are correct in some
	// fashion.
	CheckKind_CHECK_KIND_TEST CheckKind = 3
	// ANALYSIS is a Check which consumes ~anything, and makes some
	// meta-determiniation. For example, an Analysis could consume sources, builds
	// and tests and make a determiation like "this CL can land".
	CheckKind_CHECK_KIND_ANALYSIS CheckKind = 4
)

// Enum value maps for CheckKind.
var (
	CheckKind_name = map[int32]string{
		0: "CHECK_KIND_UNKNOWN",
		1: "CHECK_KIND_SOURCE",
		2: "CHECK_KIND_BUILD",
		3: "CHECK_KIND_TEST",
		4: "CHECK_KIND_ANALYSIS",
	}
	CheckKind_value = map[string]int32{
		"CHECK_KIND_UNKNOWN":  0,
		"CHECK_KIND_SOURCE":   1,
		"CHECK_KIND_BUILD":    2,
		"CHECK_KIND_TEST":     3,
		"CHECK_KIND_ANALYSIS": 4,
	}
)

func (x CheckKind) Enum() *CheckKind {
	p := new(CheckKind)
	*p = x
	return p
}

func (x CheckKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CheckKind) Descriptor() protoreflect.EnumDescriptor {
	return file_turboci_graph_orchestrator_v1_check_kind_proto_enumTypes[0].Descriptor()
}

func (CheckKind) Type() protoreflect.EnumType {
	return &file_turboci_graph_orchestrator_v1_check_kind_proto_enumTypes[0]
}

func (x CheckKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

var File_turboci_graph_orchestrator_v1_check_kind_proto protoreflect.FileDescriptor

const file_turboci_graph_orchestrator_v1_check_kind_proto_rawDesc = "" +
	"\n" +
	".turboci/graph/orchestrator/v1/check_kind.proto\x12\x1dturboci.graph.orchestrator.v1*~\n" +
	"\tCheckKind\x12\x16\n" +
	"\x12CHECK_KIND_UNKNOWN\x10\x00\x12\x15\n" +
	"\x11CHECK_KIND_SOURCE\x10\x01\x12\x14\n" +
	"\x10CHECK_KIND_BUILD\x10\x02\x12\x13\n" +
	"\x0fCHECK_KIND_TEST\x10\x03\x12\x17\n" +
	"\x13CHECK_KIND_ANALYSIS\x10\x04BIP\x01ZEgo.chromium.org/turboci/proto/go/graph/orchestrator/v1;orchestratorpbb\x06proto3"

var file_turboci_graph_orchestrator_v1_check_kind_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_turboci_graph_orchestrator_v1_check_kind_proto_goTypes = []any{
	(CheckKind)(0), // 0: turboci.graph.orchestrator.v1.CheckKind
}
var file_turboci_graph_orchestrator_v1_check_kind_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_turboci_graph_orchestrator_v1_check_kind_proto_init() }
func file_turboci_graph_orchestrator_v1_check_kind_proto_init() {
	if File_turboci_graph_orchestrator_v1_check_kind_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_turboci_graph_orchestrator_v1_check_kind_proto_rawDesc), len(file_turboci_graph_orchestrator_v1_check_kind_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_turboci_graph_orchestrator_v1_check_kind_proto_goTypes,
		DependencyIndexes: file_turboci_graph_orchestrator_v1_check_kind_proto_depIdxs,
		EnumInfos:         file_turboci_graph_orchestrator_v1_check_kind_proto_enumTypes,
	}.Build()
	File_turboci_graph_orchestrator_v1_check_kind_proto = out.File
	file_turboci_graph_orchestrator_v1_check_kind_proto_goTypes = nil
	file_turboci_graph_orchestrator_v1_check_kind_proto_depIdxs = nil
}
