// Copyright 2025 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: turboci/graph/orchestrator/v1/datum.proto

package orchestratorpb

import (
	v1 "go.chromium.org/turboci/proto/go/graph/ids/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Datum is a simple wrapper around an `Any`.
//
// The wrapper currently provides a way for stages in the workflow to control
// data accessibility by mapping a realm to each Datum.
//
// We anticipate that in the future we will want to allow the writer of a Datum
// to include additional indexable values to allow clients of TurboCI to e.g.
// search for Checks whose options contain "type" with some specific value.
type Datum struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The identifier of this Datum.
	//
	// This is used to map the Datum to the appropriate object (e.g. CheckOption,
	// CheckResult, etc.).
	Identifier *v1.Identifier `protobuf:"bytes,1,opt,name=identifier" json:"identifier,omitempty"`
	// Maps this datum to a security realm.
	//
	// If omitted, this Datum inherits the realm of the object that it belongs to
	// (i.e. Check or Check Result).
	Realm *string `protobuf:"bytes,2,opt,name=realm" json:"realm,omitempty"`
	// The version of this Datum in the database.
	Version *Revision `protobuf:"bytes,3,opt,name=version" json:"version,omitempty"`
	// The actual value of this Datum.
	//
	// The TurboCI orchestrator requires that the type_url of the `value` here be
	// [pre-registered](TBD). This registration ensures that:
	//   - The proto type URL is known to the service frontend (otherwise the
	//     service frontend will reject the type).
	//   - The type is compatible in the context of this Datum (i.e. within
	//     a Check or Check.Result of a certain Kind).
	//
	// Once a type is registered, however, the Orchestrator service will not
	// require the content to be conformant to its registered type. That is
	// - Workflows may run with newer versions of the type definition for a given
	// registered type. This allows rapid prototyping of workflows without the
	// need to land and deploy schema changes ahead of time.
	//
	// The `type_url` of this value is immutable.
	Value         *Value `protobuf:"bytes,4,opt,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Datum) Reset() {
	*x = Datum{}
	mi := &file_turboci_graph_orchestrator_v1_datum_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Datum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Datum) ProtoMessage() {}

func (x *Datum) ProtoReflect() protoreflect.Message {
	mi := &file_turboci_graph_orchestrator_v1_datum_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Datum.ProtoReflect.Descriptor instead.
func (*Datum) Descriptor() ([]byte, []int) {
	return file_turboci_graph_orchestrator_v1_datum_proto_rawDescGZIP(), []int{0}
}

func (x *Datum) GetIdentifier() *v1.Identifier {
	if x != nil {
		return x.Identifier
	}
	return nil
}

func (x *Datum) GetRealm() string {
	if x != nil && x.Realm != nil {
		return *x.Realm
	}
	return ""
}

func (x *Datum) GetVersion() *Revision {
	if x != nil {
		return x.Version
	}
	return nil
}

func (x *Datum) GetValue() *Value {
	if x != nil {
		return x.Value
	}
	return nil
}

var File_turboci_graph_orchestrator_v1_datum_proto protoreflect.FileDescriptor

const file_turboci_graph_orchestrator_v1_datum_proto_rawDesc = "" +
	"\n" +
	")turboci/graph/orchestrator/v1/datum.proto\x12\x1dturboci.graph.orchestrator.v1\x1a\x1fgoogle/api/field_behavior.proto\x1a%turboci/graph/ids/v1/identifier.proto\x1a1turboci/graph/orchestrator/v1/field_options.proto\x1a,turboci/graph/orchestrator/v1/revision.proto\x1a)turboci/graph/orchestrator/v1/value.proto\"\xf2\x01\n" +
	"\x05Datum\x12O\n" +
	"\n" +
	"identifier\x18\x01 \x01(\v2 .turboci.graph.ids.v1.IdentifierB\r\x82\x86\xf6\xfb\x0f\a\x12\x05\n" +
	"\x03\x03\x05\aR\n" +
	"identifier\x12\x19\n" +
	"\x05realm\x18\x02 \x01(\tB\x03\xe0A\x05R\x05realm\x12A\n" +
	"\aversion\x18\x03 \x01(\v2'.turboci.graph.orchestrator.v1.RevisionR\aversion\x12:\n" +
	"\x05value\x18\x04 \x01(\v2$.turboci.graph.orchestrator.v1.ValueR\x05valueBIP\x01ZEgo.chromium.org/turboci/proto/go/graph/orchestrator/v1;orchestratorpbb\beditionsp\xe8\a"

var (
	file_turboci_graph_orchestrator_v1_datum_proto_rawDescOnce sync.Once
	file_turboci_graph_orchestrator_v1_datum_proto_rawDescData []byte
)

func file_turboci_graph_orchestrator_v1_datum_proto_rawDescGZIP() []byte {
	file_turboci_graph_orchestrator_v1_datum_proto_rawDescOnce.Do(func() {
		file_turboci_graph_orchestrator_v1_datum_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_turboci_graph_orchestrator_v1_datum_proto_rawDesc), len(file_turboci_graph_orchestrator_v1_datum_proto_rawDesc)))
	})
	return file_turboci_graph_orchestrator_v1_datum_proto_rawDescData
}

var file_turboci_graph_orchestrator_v1_datum_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_turboci_graph_orchestrator_v1_datum_proto_goTypes = []any{
	(*Datum)(nil),         // 0: turboci.graph.orchestrator.v1.Datum
	(*v1.Identifier)(nil), // 1: turboci.graph.ids.v1.Identifier
	(*Revision)(nil),      // 2: turboci.graph.orchestrator.v1.Revision
	(*Value)(nil),         // 3: turboci.graph.orchestrator.v1.Value
}
var file_turboci_graph_orchestrator_v1_datum_proto_depIdxs = []int32{
	1, // 0: turboci.graph.orchestrator.v1.Datum.identifier:type_name -> turboci.graph.ids.v1.Identifier
	2, // 1: turboci.graph.orchestrator.v1.Datum.version:type_name -> turboci.graph.orchestrator.v1.Revision
	3, // 2: turboci.graph.orchestrator.v1.Datum.value:type_name -> turboci.graph.orchestrator.v1.Value
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_turboci_graph_orchestrator_v1_datum_proto_init() }
func file_turboci_graph_orchestrator_v1_datum_proto_init() {
	if File_turboci_graph_orchestrator_v1_datum_proto != nil {
		return
	}
	file_turboci_graph_orchestrator_v1_field_options_proto_init()
	file_turboci_graph_orchestrator_v1_revision_proto_init()
	file_turboci_graph_orchestrator_v1_value_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_turboci_graph_orchestrator_v1_datum_proto_rawDesc), len(file_turboci_graph_orchestrator_v1_datum_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_turboci_graph_orchestrator_v1_datum_proto_goTypes,
		DependencyIndexes: file_turboci_graph_orchestrator_v1_datum_proto_depIdxs,
		MessageInfos:      file_turboci_graph_orchestrator_v1_datum_proto_msgTypes,
	}.Build()
	File_turboci_graph_orchestrator_v1_datum_proto = out.File
	file_turboci_graph_orchestrator_v1_datum_proto_goTypes = nil
	file_turboci_graph_orchestrator_v1_datum_proto_depIdxs = nil
}
