// Copyright 2025 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: turboci/graph/orchestrator/v1/field_options.proto

package orchestratorpb

import (
	v1 "go.chromium.org/turboci/proto/go/graph/ids/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FieldOptions are field options which apply to TurboCI message fields.
type FieldOptions struct {
	state                          protoimpl.MessageState          `protogen:"opaque.v1"`
	xxx_hidden_Check               *FieldOptions_CheckFieldOptions `protobuf:"bytes,1,opt,name=check,proto3,oneof"`
	xxx_hidden_Id                  *FieldOptions_IdentifierOptions `protobuf:"bytes,2,opt,name=id,proto3,oneof"`
	xxx_hidden_CreationOnly        bool                            `protobuf:"varint,3,opt,name=creation_only,json=creationOnly,proto3,oneof"`
	xxx_hidden_RealmInheritsWriter bool                            `protobuf:"varint,4,opt,name=realm_inherits_writer,json=realmInheritsWriter,proto3,oneof"`
	XXX_raceDetectHookData         protoimpl.RaceDetectHookData
	XXX_presence                   [1]uint32
	unknownFields                  protoimpl.UnknownFields
	sizeCache                      protoimpl.SizeCache
}

func (x *FieldOptions) Reset() {
	*x = FieldOptions{}
	mi := &file_turboci_graph_orchestrator_v1_field_options_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldOptions) ProtoMessage() {}

func (x *FieldOptions) ProtoReflect() protoreflect.Message {
	mi := &file_turboci_graph_orchestrator_v1_field_options_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *FieldOptions) GetCheck() *FieldOptions_CheckFieldOptions {
	if x != nil {
		return x.xxx_hidden_Check
	}
	return nil
}

func (x *FieldOptions) GetId() *FieldOptions_IdentifierOptions {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return nil
}

func (x *FieldOptions) GetCreationOnly() bool {
	if x != nil {
		return x.xxx_hidden_CreationOnly
	}
	return false
}

func (x *FieldOptions) GetRealmInheritsWriter() bool {
	if x != nil {
		return x.xxx_hidden_RealmInheritsWriter
	}
	return false
}

func (x *FieldOptions) SetCheck(v *FieldOptions_CheckFieldOptions) {
	x.xxx_hidden_Check = v
}

func (x *FieldOptions) SetId(v *FieldOptions_IdentifierOptions) {
	x.xxx_hidden_Id = v
}

func (x *FieldOptions) SetCreationOnly(v bool) {
	x.xxx_hidden_CreationOnly = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 4)
}

func (x *FieldOptions) SetRealmInheritsWriter(v bool) {
	x.xxx_hidden_RealmInheritsWriter = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 4)
}

func (x *FieldOptions) HasCheck() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Check != nil
}

func (x *FieldOptions) HasId() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Id != nil
}

func (x *FieldOptions) HasCreationOnly() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *FieldOptions) HasRealmInheritsWriter() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *FieldOptions) ClearCheck() {
	x.xxx_hidden_Check = nil
}

func (x *FieldOptions) ClearId() {
	x.xxx_hidden_Id = nil
}

func (x *FieldOptions) ClearCreationOnly() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_CreationOnly = false
}

func (x *FieldOptions) ClearRealmInheritsWriter() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_RealmInheritsWriter = false
}

type FieldOptions_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Field options which apply to Check messages.
	Check *FieldOptions_CheckFieldOptions
	// Field options which apply to fields containing Identifiers.
	Id *FieldOptions_IdentifierOptions
	// True if this field only applies during creation of the target node.
	//
	// If this field is supplied and the target node already exists, its value
	// must match the target's value for this field.
	CreationOnly *bool
	// If set on a `realm` field in WriteNodesRequest, it indicates that this
	// realm, if left unset, will inherit the realm of the writer making the
	// request (encoded in the `token` supplied in the WriteNodesRequest).
	RealmInheritsWriter *bool
}

func (b0 FieldOptions_builder) Build() *FieldOptions {
	m0 := &FieldOptions{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Check = b.Check
	x.xxx_hidden_Id = b.Id
	if b.CreationOnly != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 4)
		x.xxx_hidden_CreationOnly = *b.CreationOnly
	}
	if b.RealmInheritsWriter != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 4)
		x.xxx_hidden_RealmInheritsWriter = *b.RealmInheritsWriter
	}
	return m0
}

// CheckFieldOptions are field options which apply to Check messages.
type FieldOptions_CheckFieldOptions struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Editable    CheckState             `protobuf:"varint,1,opt,name=editable,proto3,enum=turboci.graph.orchestrator.v1.CheckState,oneof"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *FieldOptions_CheckFieldOptions) Reset() {
	*x = FieldOptions_CheckFieldOptions{}
	mi := &file_turboci_graph_orchestrator_v1_field_options_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldOptions_CheckFieldOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldOptions_CheckFieldOptions) ProtoMessage() {}

func (x *FieldOptions_CheckFieldOptions) ProtoReflect() protoreflect.Message {
	mi := &file_turboci_graph_orchestrator_v1_field_options_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *FieldOptions_CheckFieldOptions) GetEditable() CheckState {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 0) {
			return x.xxx_hidden_Editable
		}
	}
	return CheckState_CHECK_STATE_UNKNOWN
}

func (x *FieldOptions_CheckFieldOptions) SetEditable(v CheckState) {
	x.xxx_hidden_Editable = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *FieldOptions_CheckFieldOptions) HasEditable() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *FieldOptions_CheckFieldOptions) ClearEditable() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Editable = CheckState_CHECK_STATE_UNKNOWN
}

type FieldOptions_CheckFieldOptions_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Indicates that this field is mutable at this CheckState or earlier.
	//
	// We use `editable` here (instead of `mutable`) to avoid name mangling in
	// C++.
	//
	// Example (this indicates that `foo` is mutable during the PLANNING
	// state):
	//
	//	message Check {
	//	  string foo = 1 [
	//	    (turboci).check.editable = CHECK_STATE_PLANNING
	//	  ];
	//	}
	Editable *CheckState
}

func (b0 FieldOptions_CheckFieldOptions_builder) Build() *FieldOptions_CheckFieldOptions {
	m0 := &FieldOptions_CheckFieldOptions{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Editable != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Editable = *b.Editable
	}
	return m0
}

// IdentifierOptions are field options which apply to message containing
// Identifiers.
type FieldOptions_IdentifierOptions struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Allowed []v1.IdentifierKind    `protobuf:"varint,1,rep,packed,name=allowed,proto3,enum=turboci.graph.ids.v1.IdentifierKind"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *FieldOptions_IdentifierOptions) Reset() {
	*x = FieldOptions_IdentifierOptions{}
	mi := &file_turboci_graph_orchestrator_v1_field_options_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldOptions_IdentifierOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldOptions_IdentifierOptions) ProtoMessage() {}

func (x *FieldOptions_IdentifierOptions) ProtoReflect() protoreflect.Message {
	mi := &file_turboci_graph_orchestrator_v1_field_options_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *FieldOptions_IdentifierOptions) GetAllowed() []v1.IdentifierKind {
	if x != nil {
		return x.xxx_hidden_Allowed
	}
	return nil
}

func (x *FieldOptions_IdentifierOptions) SetAllowed(v []v1.IdentifierKind) {
	x.xxx_hidden_Allowed = v
}

type FieldOptions_IdentifierOptions_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Indicates a list of allowed target types for Identifiers within this
	// field. Commonly used with Edge messages, but may also directly annotate
	// Identifier fields.
	//
	// Example:
	//
	//	message Foo {
	//	  repeated Edge dependencies = 1 [
	//	    (turboci).id.allowed: IDENTIFIER_KIND_STAGE,
	//	    (turboci).id.allowed: IDENTIFIER_KIND_CHECK
	//	  ];
	//	}
	Allowed []v1.IdentifierKind
}

func (b0 FieldOptions_IdentifierOptions_builder) Build() *FieldOptions_IdentifierOptions {
	m0 := &FieldOptions_IdentifierOptions{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Allowed = b.Allowed
	return m0
}

var file_turboci_graph_orchestrator_v1_field_options_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*FieldOptions)(nil),
		Field:         535801952,
		Name:          "turboci.graph.orchestrator.v1.turboci",
		Tag:           "bytes,535801952,opt,name=turboci",
		Filename:      "turboci/graph/orchestrator/v1/field_options.proto",
	},
}

// Extension fields to descriptorpb.FieldOptions.
var (
	// TurboCI options for fields.
	//
	// optional turboci.graph.orchestrator.v1.FieldOptions turboci = 535801952;
	E_Turboci = &file_turboci_graph_orchestrator_v1_field_options_proto_extTypes[0]
)

var File_turboci_graph_orchestrator_v1_field_options_proto protoreflect.FileDescriptor

const file_turboci_graph_orchestrator_v1_field_options_proto_rawDesc = "" +
	"\n" +
	"1turboci/graph/orchestrator/v1/field_options.proto\x12\x1dturboci.graph.orchestrator.v1\x1a google/protobuf/descriptor.proto\x1a*turboci/graph/ids/v1/identifier_kind.proto\x1a/turboci/graph/orchestrator/v1/check_state.proto\"\xa3\x04\n" +
	"\fFieldOptions\x12X\n" +
	"\x05check\x18\x01 \x01(\v2=.turboci.graph.orchestrator.v1.FieldOptions.CheckFieldOptionsH\x00R\x05check\x88\x01\x01\x12R\n" +
	"\x02id\x18\x02 \x01(\v2=.turboci.graph.orchestrator.v1.FieldOptions.IdentifierOptionsH\x01R\x02id\x88\x01\x01\x12(\n" +
	"\rcreation_only\x18\x03 \x01(\bH\x02R\fcreationOnly\x88\x01\x01\x127\n" +
	"\x15realm_inherits_writer\x18\x04 \x01(\bH\x03R\x13realmInheritsWriter\x88\x01\x01\x1al\n" +
	"\x11CheckFieldOptions\x12J\n" +
	"\beditable\x18\x01 \x01(\x0e2).turboci.graph.orchestrator.v1.CheckStateH\x00R\beditable\x88\x01\x01B\v\n" +
	"\t_editable\x1aW\n" +
	"\x11IdentifierOptions\x12B\n" +
	"\aallowed\x18\x01 \x03(\x0e2$.turboci.graph.ids.v1.IdentifierKindB\x02\x10\x01R\aallowedB\b\n" +
	"\x06_checkB\x05\n" +
	"\x03_idB\x10\n" +
	"\x0e_creation_onlyB\x18\n" +
	"\x16_realm_inherits_writer:k\n" +
	"\aturboci\x12\x1d.google.protobuf.FieldOptions\x18\xe0\xe0\xbe\xff\x01 \x01(\v2+.turboci.graph.orchestrator.v1.FieldOptionsR\aturboci\x88\x01\x01BIP\x01ZEgo.chromium.org/turboci/proto/go/graph/orchestrator/v1;orchestratorpbb\x06proto3"

var file_turboci_graph_orchestrator_v1_field_options_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_turboci_graph_orchestrator_v1_field_options_proto_goTypes = []any{
	(*FieldOptions)(nil),                   // 0: turboci.graph.orchestrator.v1.FieldOptions
	(*FieldOptions_CheckFieldOptions)(nil), // 1: turboci.graph.orchestrator.v1.FieldOptions.CheckFieldOptions
	(*FieldOptions_IdentifierOptions)(nil), // 2: turboci.graph.orchestrator.v1.FieldOptions.IdentifierOptions
	(CheckState)(0),                        // 3: turboci.graph.orchestrator.v1.CheckState
	(v1.IdentifierKind)(0),                 // 4: turboci.graph.ids.v1.IdentifierKind
	(*descriptorpb.FieldOptions)(nil),      // 5: google.protobuf.FieldOptions
}
var file_turboci_graph_orchestrator_v1_field_options_proto_depIdxs = []int32{
	1, // 0: turboci.graph.orchestrator.v1.FieldOptions.check:type_name -> turboci.graph.orchestrator.v1.FieldOptions.CheckFieldOptions
	2, // 1: turboci.graph.orchestrator.v1.FieldOptions.id:type_name -> turboci.graph.orchestrator.v1.FieldOptions.IdentifierOptions
	3, // 2: turboci.graph.orchestrator.v1.FieldOptions.CheckFieldOptions.editable:type_name -> turboci.graph.orchestrator.v1.CheckState
	4, // 3: turboci.graph.orchestrator.v1.FieldOptions.IdentifierOptions.allowed:type_name -> turboci.graph.ids.v1.IdentifierKind
	5, // 4: turboci.graph.orchestrator.v1.turboci:extendee -> google.protobuf.FieldOptions
	0, // 5: turboci.graph.orchestrator.v1.turboci:type_name -> turboci.graph.orchestrator.v1.FieldOptions
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	5, // [5:6] is the sub-list for extension type_name
	4, // [4:5] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_turboci_graph_orchestrator_v1_field_options_proto_init() }
func file_turboci_graph_orchestrator_v1_field_options_proto_init() {
	if File_turboci_graph_orchestrator_v1_field_options_proto != nil {
		return
	}
	file_turboci_graph_orchestrator_v1_check_state_proto_init()
	file_turboci_graph_orchestrator_v1_field_options_proto_msgTypes[0].OneofWrappers = []any{}
	file_turboci_graph_orchestrator_v1_field_options_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_turboci_graph_orchestrator_v1_field_options_proto_rawDesc), len(file_turboci_graph_orchestrator_v1_field_options_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_turboci_graph_orchestrator_v1_field_options_proto_goTypes,
		DependencyIndexes: file_turboci_graph_orchestrator_v1_field_options_proto_depIdxs,
		MessageInfos:      file_turboci_graph_orchestrator_v1_field_options_proto_msgTypes,
		ExtensionInfos:    file_turboci_graph_orchestrator_v1_field_options_proto_extTypes,
	}.Build()
	File_turboci_graph_orchestrator_v1_field_options_proto = out.File
	file_turboci_graph_orchestrator_v1_field_options_proto_goTypes = nil
	file_turboci_graph_orchestrator_v1_field_options_proto_depIdxs = nil
}
