// Copyright 2025 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: turboci/graph/orchestrator/v1/query_nodes_response.proto

package orchestratorpb

import (
	v1 "go.chromium.org/turboci/proto/go/graph/ids/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Response message for TurboCIGraphService.QueryNodes.
type QueryNodesResponse struct {
	state                          protoimpl.MessageState    `protogen:"opaque.v1"`
	xxx_hidden_Workplan            map[string]*WorkPlan      `protobuf:"bytes,1,rep,name=workplan,proto3" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	xxx_hidden_Absent              *[]*v1.Identifier         `protobuf:"bytes,2,rep,name=absent,proto3"`
	xxx_hidden_CurrentAttemptState *StageAttemptCurrentState `protobuf:"bytes,3,opt,name=current_attempt_state,json=currentAttemptState,proto3,oneof"`
	xxx_hidden_Version             *Revision                 `protobuf:"bytes,4,opt,name=version,proto3,oneof"`
	unknownFields                  protoimpl.UnknownFields
	sizeCache                      protoimpl.SizeCache
}

func (x *QueryNodesResponse) Reset() {
	*x = QueryNodesResponse{}
	mi := &file_turboci_graph_orchestrator_v1_query_nodes_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryNodesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryNodesResponse) ProtoMessage() {}

func (x *QueryNodesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_turboci_graph_orchestrator_v1_query_nodes_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *QueryNodesResponse) GetWorkplan() map[string]*WorkPlan {
	if x != nil {
		return x.xxx_hidden_Workplan
	}
	return nil
}

func (x *QueryNodesResponse) GetAbsent() []*v1.Identifier {
	if x != nil {
		if x.xxx_hidden_Absent != nil {
			return *x.xxx_hidden_Absent
		}
	}
	return nil
}

func (x *QueryNodesResponse) GetCurrentAttemptState() *StageAttemptCurrentState {
	if x != nil {
		return x.xxx_hidden_CurrentAttemptState
	}
	return nil
}

func (x *QueryNodesResponse) GetVersion() *Revision {
	if x != nil {
		return x.xxx_hidden_Version
	}
	return nil
}

func (x *QueryNodesResponse) SetWorkplan(v map[string]*WorkPlan) {
	x.xxx_hidden_Workplan = v
}

func (x *QueryNodesResponse) SetAbsent(v []*v1.Identifier) {
	x.xxx_hidden_Absent = &v
}

func (x *QueryNodesResponse) SetCurrentAttemptState(v *StageAttemptCurrentState) {
	x.xxx_hidden_CurrentAttemptState = v
}

func (x *QueryNodesResponse) SetVersion(v *Revision) {
	x.xxx_hidden_Version = v
}

func (x *QueryNodesResponse) HasCurrentAttemptState() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_CurrentAttemptState != nil
}

func (x *QueryNodesResponse) HasVersion() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Version != nil
}

func (x *QueryNodesResponse) ClearCurrentAttemptState() {
	x.xxx_hidden_CurrentAttemptState = nil
}

func (x *QueryNodesResponse) ClearVersion() {
	x.xxx_hidden_Version = nil
}

type QueryNodesResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The WorkPlans containing nodes matching the request.
	//
	// Indexed by each WorkPlan's canonical string id.
	Workplan map[string]*WorkPlan
	// A list of explicitly-selected nodes which were not found in the graph.
	Absent []*v1.Identifier
	// State of the current stage attempt.
	//
	// Only set if the `token` was for a stage attempt.
	CurrentAttemptState *StageAttemptCurrentState
	// The Spanner snapshot version used when executing all queries.
	Version *Revision
}

func (b0 QueryNodesResponse_builder) Build() *QueryNodesResponse {
	m0 := &QueryNodesResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Workplan = b.Workplan
	x.xxx_hidden_Absent = &b.Absent
	x.xxx_hidden_CurrentAttemptState = b.CurrentAttemptState
	x.xxx_hidden_Version = b.Version
	return m0
}

var File_turboci_graph_orchestrator_v1_query_nodes_response_proto protoreflect.FileDescriptor

const file_turboci_graph_orchestrator_v1_query_nodes_response_proto_rawDesc = "" +
	"\n" +
	"8turboci/graph/orchestrator/v1/query_nodes_response.proto\x12\x1dturboci.graph.orchestrator.v1\x1a%turboci/graph/ids/v1/identifier.proto\x1a,turboci/graph/orchestrator/v1/revision.proto\x1a)turboci/graph/orchestrator/v1/stage.proto\x1a,turboci/graph/orchestrator/v1/workplan.proto\"\xf1\x03\n" +
	"\x12QueryNodesResponse\x12[\n" +
	"\bworkplan\x18\x01 \x03(\v2?.turboci.graph.orchestrator.v1.QueryNodesResponse.WorkplanEntryR\bworkplan\x128\n" +
	"\x06absent\x18\x02 \x03(\v2 .turboci.graph.ids.v1.IdentifierR\x06absent\x12p\n" +
	"\x15current_attempt_state\x18\x03 \x01(\v27.turboci.graph.orchestrator.v1.StageAttemptCurrentStateH\x00R\x13currentAttemptState\x88\x01\x01\x12F\n" +
	"\aversion\x18\x04 \x01(\v2'.turboci.graph.orchestrator.v1.RevisionH\x01R\aversion\x88\x01\x01\x1ad\n" +
	"\rWorkplanEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12=\n" +
	"\x05value\x18\x02 \x01(\v2'.turboci.graph.orchestrator.v1.WorkPlanR\x05value:\x028\x01B\x18\n" +
	"\x16_current_attempt_stateB\n" +
	"\n" +
	"\b_versionBIP\x01ZEgo.chromium.org/turboci/proto/go/graph/orchestrator/v1;orchestratorpbb\x06proto3"

var file_turboci_graph_orchestrator_v1_query_nodes_response_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_turboci_graph_orchestrator_v1_query_nodes_response_proto_goTypes = []any{
	(*QueryNodesResponse)(nil),       // 0: turboci.graph.orchestrator.v1.QueryNodesResponse
	nil,                              // 1: turboci.graph.orchestrator.v1.QueryNodesResponse.WorkplanEntry
	(*v1.Identifier)(nil),            // 2: turboci.graph.ids.v1.Identifier
	(*StageAttemptCurrentState)(nil), // 3: turboci.graph.orchestrator.v1.StageAttemptCurrentState
	(*Revision)(nil),                 // 4: turboci.graph.orchestrator.v1.Revision
	(*WorkPlan)(nil),                 // 5: turboci.graph.orchestrator.v1.WorkPlan
}
var file_turboci_graph_orchestrator_v1_query_nodes_response_proto_depIdxs = []int32{
	1, // 0: turboci.graph.orchestrator.v1.QueryNodesResponse.workplan:type_name -> turboci.graph.orchestrator.v1.QueryNodesResponse.WorkplanEntry
	2, // 1: turboci.graph.orchestrator.v1.QueryNodesResponse.absent:type_name -> turboci.graph.ids.v1.Identifier
	3, // 2: turboci.graph.orchestrator.v1.QueryNodesResponse.current_attempt_state:type_name -> turboci.graph.orchestrator.v1.StageAttemptCurrentState
	4, // 3: turboci.graph.orchestrator.v1.QueryNodesResponse.version:type_name -> turboci.graph.orchestrator.v1.Revision
	5, // 4: turboci.graph.orchestrator.v1.QueryNodesResponse.WorkplanEntry.value:type_name -> turboci.graph.orchestrator.v1.WorkPlan
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_turboci_graph_orchestrator_v1_query_nodes_response_proto_init() }
func file_turboci_graph_orchestrator_v1_query_nodes_response_proto_init() {
	if File_turboci_graph_orchestrator_v1_query_nodes_response_proto != nil {
		return
	}
	file_turboci_graph_orchestrator_v1_revision_proto_init()
	file_turboci_graph_orchestrator_v1_stage_proto_init()
	file_turboci_graph_orchestrator_v1_workplan_proto_init()
	file_turboci_graph_orchestrator_v1_query_nodes_response_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_turboci_graph_orchestrator_v1_query_nodes_response_proto_rawDesc), len(file_turboci_graph_orchestrator_v1_query_nodes_response_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_turboci_graph_orchestrator_v1_query_nodes_response_proto_goTypes,
		DependencyIndexes: file_turboci_graph_orchestrator_v1_query_nodes_response_proto_depIdxs,
		MessageInfos:      file_turboci_graph_orchestrator_v1_query_nodes_response_proto_msgTypes,
	}.Build()
	File_turboci_graph_orchestrator_v1_query_nodes_response_proto = out.File
	file_turboci_graph_orchestrator_v1_query_nodes_response_proto_goTypes = nil
	file_turboci_graph_orchestrator_v1_query_nodes_response_proto_depIdxs = nil
}
