// Copyright 2025 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: turboci/graph/orchestrator/v1/query.proto

package orchestratorpb

import (
	v1 "go.chromium.org/turboci/proto/go/graph/ids/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// When expanding a query selection set with Query.Expand.Dependencies or
// Query.Expand.Dependants, how should we actually expand that set?
type QueryExpandDepsMode int32

const (
	// Unknown query expansion mode.
	//
	// Defaults to 'REQUESTED'.
	QueryExpandDepsMode_QUERY_EXPAND_DEPS_MODE_UNKNOWN QueryExpandDepsMode = 0
	// Expand to deps which are listed in dependencies.edges.
	QueryExpandDepsMode_QUERY_EXPAND_DEPS_MODE_EDGES QueryExpandDepsMode = 1
	// Expand to edges which were the ones that caused dependencies.resolved to be
	// RESOLUTION_SATISFIED.
	//
	// Note that this will be the empty set for nodes which are not already past
	// the PLANNED state, and for nodes which have RESOLUTION_UNSATISFIED
	// dependencies.
	QueryExpandDepsMode_QUERY_EXPAND_DEPS_MODE_SATISFIED QueryExpandDepsMode = 2
)

// Enum value maps for QueryExpandDepsMode.
var (
	QueryExpandDepsMode_name = map[int32]string{
		0: "QUERY_EXPAND_DEPS_MODE_UNKNOWN",
		1: "QUERY_EXPAND_DEPS_MODE_EDGES",
		2: "QUERY_EXPAND_DEPS_MODE_SATISFIED",
	}
	QueryExpandDepsMode_value = map[string]int32{
		"QUERY_EXPAND_DEPS_MODE_UNKNOWN":   0,
		"QUERY_EXPAND_DEPS_MODE_EDGES":     1,
		"QUERY_EXPAND_DEPS_MODE_SATISFIED": 2,
	}
)

func (x QueryExpandDepsMode) Enum() *QueryExpandDepsMode {
	p := new(QueryExpandDepsMode)
	*p = x
	return p
}

func (x QueryExpandDepsMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QueryExpandDepsMode) Descriptor() protoreflect.EnumDescriptor {
	return file_turboci_graph_orchestrator_v1_query_proto_enumTypes[0].Descriptor()
}

func (QueryExpandDepsMode) Type() protoreflect.EnumType {
	return &file_turboci_graph_orchestrator_v1_query_proto_enumTypes[0]
}

func (x QueryExpandDepsMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Query describes a simple graph query.
//
// This is composed of three phases: selection, expansion and collection.
//
// The selection phase queries for a set of nodes within a WorkPlan
// - effectively a regular SELECT type query on a traditional database.
//
// After the selection phase, the expansion phase allows traversal along the
// edges of the selected nodes. Currently only 'dependency' edge traversal is
// supported, but other types of relationships could be possible in the future
// (e.g. 'created_by', 'written_by', etc.).
//
// Finally, after the set of nodes has been fully expanded, we collect all the
// requested data from those Nodes.
//
// See QueryNodesRequest.version for how this Query interacts with transactions.
type Query struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Select  *Query_Select          `protobuf:"bytes,2,opt,name=select,proto3,oneof"`
	xxx_hidden_Expand  *Query_Expand          `protobuf:"bytes,3,opt,name=expand,proto3,oneof"`
	xxx_hidden_Collect *Query_Collect         `protobuf:"bytes,4,opt,name=collect,proto3,oneof"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Query) Reset() {
	*x = Query{}
	mi := &file_turboci_graph_orchestrator_v1_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Query) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Query) ProtoMessage() {}

func (x *Query) ProtoReflect() protoreflect.Message {
	mi := &file_turboci_graph_orchestrator_v1_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Query) GetSelect() *Query_Select {
	if x != nil {
		return x.xxx_hidden_Select
	}
	return nil
}

func (x *Query) GetExpand() *Query_Expand {
	if x != nil {
		return x.xxx_hidden_Expand
	}
	return nil
}

func (x *Query) GetCollect() *Query_Collect {
	if x != nil {
		return x.xxx_hidden_Collect
	}
	return nil
}

func (x *Query) SetSelect(v *Query_Select) {
	x.xxx_hidden_Select = v
}

func (x *Query) SetExpand(v *Query_Expand) {
	x.xxx_hidden_Expand = v
}

func (x *Query) SetCollect(v *Query_Collect) {
	x.xxx_hidden_Collect = v
}

func (x *Query) HasSelect() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Select != nil
}

func (x *Query) HasExpand() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Expand != nil
}

func (x *Query) HasCollect() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Collect != nil
}

func (x *Query) ClearSelect() {
	x.xxx_hidden_Select = nil
}

func (x *Query) ClearExpand() {
	x.xxx_hidden_Expand = nil
}

func (x *Query) ClearCollect() {
	x.xxx_hidden_Collect = nil
}

type Query_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Select an arbitrary set of nodes.
	Select *Query_Select
	// Expand that set of nodes by following their edges.
	Expand *Query_Expand
	// The data to collect from the expanded node set.
	Collect *Query_Collect
}

func (b0 Query_builder) Build() *Query {
	m0 := &Query{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Select = b.Select
	x.xxx_hidden_Expand = b.Expand
	x.xxx_hidden_Collect = b.Collect
	return m0
}

// Select picks some set of nodes out of the graph.
type Query_Select struct {
	state                    protoimpl.MessageState           `protogen:"opaque.v1"`
	xxx_hidden_Workplan      *Query_Select_WorkPlanConstraint `protobuf:"bytes,1,opt,name=workplan,proto3,oneof"`
	xxx_hidden_Nodes         *[]*v1.Identifier                `protobuf:"bytes,2,rep,name=nodes,proto3"`
	xxx_hidden_CheckPatterns *[]*Query_Select_CheckPattern    `protobuf:"bytes,3,rep,name=check_patterns,json=checkPatterns,proto3"`
	xxx_hidden_StagePatterns *[]*Query_Select_StagePattern    `protobuf:"bytes,4,rep,name=stage_patterns,json=stagePatterns,proto3"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *Query_Select) Reset() {
	*x = Query_Select{}
	mi := &file_turboci_graph_orchestrator_v1_query_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Query_Select) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Query_Select) ProtoMessage() {}

func (x *Query_Select) ProtoReflect() protoreflect.Message {
	mi := &file_turboci_graph_orchestrator_v1_query_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Query_Select) GetWorkplan() *Query_Select_WorkPlanConstraint {
	if x != nil {
		return x.xxx_hidden_Workplan
	}
	return nil
}

func (x *Query_Select) GetNodes() []*v1.Identifier {
	if x != nil {
		if x.xxx_hidden_Nodes != nil {
			return *x.xxx_hidden_Nodes
		}
	}
	return nil
}

func (x *Query_Select) GetCheckPatterns() []*Query_Select_CheckPattern {
	if x != nil {
		if x.xxx_hidden_CheckPatterns != nil {
			return *x.xxx_hidden_CheckPatterns
		}
	}
	return nil
}

func (x *Query_Select) GetStagePatterns() []*Query_Select_StagePattern {
	if x != nil {
		if x.xxx_hidden_StagePatterns != nil {
			return *x.xxx_hidden_StagePatterns
		}
	}
	return nil
}

func (x *Query_Select) SetWorkplan(v *Query_Select_WorkPlanConstraint) {
	x.xxx_hidden_Workplan = v
}

func (x *Query_Select) SetNodes(v []*v1.Identifier) {
	x.xxx_hidden_Nodes = &v
}

func (x *Query_Select) SetCheckPatterns(v []*Query_Select_CheckPattern) {
	x.xxx_hidden_CheckPatterns = &v
}

func (x *Query_Select) SetStagePatterns(v []*Query_Select_StagePattern) {
	x.xxx_hidden_StagePatterns = &v
}

func (x *Query_Select) HasWorkplan() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Workplan != nil
}

func (x *Query_Select) ClearWorkplan() {
	x.xxx_hidden_Workplan = nil
}

type Query_Select_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Which WorkPlans to search across.
	Workplan *Query_Select_WorkPlanConstraint
	// The identifiers of specific nodes to select.
	//
	// This should be used if you already know the identifiers of the nodes you
	// care about.
	Nodes []*v1.Identifier
	// Select Checks matching these patterns.
	CheckPatterns []*Query_Select_CheckPattern
	// Select Stages matching these patterns.
	StagePatterns []*Query_Select_StagePattern
}

func (b0 Query_Select_builder) Build() *Query_Select {
	m0 := &Query_Select{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Workplan = b.Workplan
	x.xxx_hidden_Nodes = &b.Nodes
	x.xxx_hidden_CheckPatterns = &b.CheckPatterns
	x.xxx_hidden_StagePatterns = &b.StagePatterns
	return m0
}

// Expand takes the selected node set and 'expands' it by following edges in
// the graph from those nodes.
type Query_Expand struct {
	state                   protoimpl.MessageState     `protogen:"opaque.v1"`
	xxx_hidden_Dependencies *Query_Expand_Dependencies `protobuf:"bytes,1,opt,name=dependencies,proto3,oneof"`
	xxx_hidden_Dependents   *Query_Expand_Dependents   `protobuf:"bytes,2,opt,name=dependents,proto3,oneof"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *Query_Expand) Reset() {
	*x = Query_Expand{}
	mi := &file_turboci_graph_orchestrator_v1_query_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Query_Expand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Query_Expand) ProtoMessage() {}

func (x *Query_Expand) ProtoReflect() protoreflect.Message {
	mi := &file_turboci_graph_orchestrator_v1_query_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Query_Expand) GetDependencies() *Query_Expand_Dependencies {
	if x != nil {
		return x.xxx_hidden_Dependencies
	}
	return nil
}

func (x *Query_Expand) GetDependents() *Query_Expand_Dependents {
	if x != nil {
		return x.xxx_hidden_Dependents
	}
	return nil
}

func (x *Query_Expand) SetDependencies(v *Query_Expand_Dependencies) {
	x.xxx_hidden_Dependencies = v
}

func (x *Query_Expand) SetDependents(v *Query_Expand_Dependents) {
	x.xxx_hidden_Dependents = v
}

func (x *Query_Expand) HasDependencies() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Dependencies != nil
}

func (x *Query_Expand) HasDependents() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Dependents != nil
}

func (x *Query_Expand) ClearDependencies() {
	x.xxx_hidden_Dependencies = nil
}

func (x *Query_Expand) ClearDependents() {
	x.xxx_hidden_Dependents = nil
}

type Query_Expand_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// For each selected Check or Stage, include its immediate dependencies.
	//
	// So given:
	//
	//	A -> {B, C}
	//
	// (B, C) are dependencies of A.
	Dependencies *Query_Expand_Dependencies
	// For each selected Check or Stage, include any Checks/Stages which depend
	// on it.
	//
	// So given:
	//
	//	A -> {B, C}
	//
	// A is a dependent of B.
	Dependents *Query_Expand_Dependents
}

func (b0 Query_Expand_builder) Build() *Query_Expand {
	m0 := &Query_Expand{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Dependencies = b.Dependencies
	x.xxx_hidden_Dependents = b.Dependents
	return m0
}

// Collect retrieves data from the expanded node set.
type Query_Collect struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Check *Query_Collect_Check   `protobuf:"bytes,1,opt,name=check,proto3,oneof"`
	xxx_hidden_Stage *Query_Collect_Stage   `protobuf:"bytes,2,opt,name=stage,proto3,oneof"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Query_Collect) Reset() {
	*x = Query_Collect{}
	mi := &file_turboci_graph_orchestrator_v1_query_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Query_Collect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Query_Collect) ProtoMessage() {}

func (x *Query_Collect) ProtoReflect() protoreflect.Message {
	mi := &file_turboci_graph_orchestrator_v1_query_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Query_Collect) GetCheck() *Query_Collect_Check {
	if x != nil {
		return x.xxx_hidden_Check
	}
	return nil
}

func (x *Query_Collect) GetStage() *Query_Collect_Stage {
	if x != nil {
		return x.xxx_hidden_Stage
	}
	return nil
}

func (x *Query_Collect) SetCheck(v *Query_Collect_Check) {
	x.xxx_hidden_Check = v
}

func (x *Query_Collect) SetStage(v *Query_Collect_Stage) {
	x.xxx_hidden_Stage = v
}

func (x *Query_Collect) HasCheck() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Check != nil
}

func (x *Query_Collect) HasStage() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Stage != nil
}

func (x *Query_Collect) ClearCheck() {
	x.xxx_hidden_Check = nil
}

func (x *Query_Collect) ClearStage() {
	x.xxx_hidden_Stage = nil
}

type Query_Collect_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Describes what data the caller wants to see for Checks.
	Check *Query_Collect_Check
	// Describes what data the caller wants to see for Stages.
	Stage *Query_Collect_Stage
}

func (b0 Query_Collect_builder) Build() *Query_Collect {
	m0 := &Query_Collect{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Check = b.Check
	x.xxx_hidden_Stage = b.Stage
	return m0
}

// How this selection of nodes should be constrained to one or more
// WorkPlans.
type Query_Select_WorkPlanConstraint struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_InWorkplans *[]*v1.WorkPlan        `protobuf:"bytes,1,rep,name=in_workplans,json=inWorkplans,proto3"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Query_Select_WorkPlanConstraint) Reset() {
	*x = Query_Select_WorkPlanConstraint{}
	mi := &file_turboci_graph_orchestrator_v1_query_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Query_Select_WorkPlanConstraint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Query_Select_WorkPlanConstraint) ProtoMessage() {}

func (x *Query_Select_WorkPlanConstraint) ProtoReflect() protoreflect.Message {
	mi := &file_turboci_graph_orchestrator_v1_query_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Query_Select_WorkPlanConstraint) GetInWorkplans() []*v1.WorkPlan {
	if x != nil {
		if x.xxx_hidden_InWorkplans != nil {
			return *x.xxx_hidden_InWorkplans
		}
	}
	return nil
}

func (x *Query_Select_WorkPlanConstraint) SetInWorkplans(v []*v1.WorkPlan) {
	x.xxx_hidden_InWorkplans = &v
}

type Query_Select_WorkPlanConstraint_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Constrain this Select to the given WorkPlan(s).
	InWorkplans []*v1.WorkPlan
}

func (b0 Query_Select_WorkPlanConstraint_builder) Build() *Query_Select_WorkPlanConstraint {
	m0 := &Query_Select_WorkPlanConstraint{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_InWorkplans = &b.InWorkplans
	return m0
}

// Select one or more Checks which match this pattern.
type Query_Select_CheckPattern struct {
	state                          protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Kind                CheckKind              `protobuf:"varint,1,opt,name=kind,proto3,enum=turboci.graph.orchestrator.v1.CheckKind,oneof"`
	xxx_hidden_IdRegex             *string                `protobuf:"bytes,2,opt,name=id_regex,json=idRegex,proto3,oneof"`
	xxx_hidden_WithOptionTypes     []string               `protobuf:"bytes,3,rep,name=with_option_types,json=withOptionTypes,proto3"`
	xxx_hidden_State               CheckState             `protobuf:"varint,4,opt,name=state,proto3,enum=turboci.graph.orchestrator.v1.CheckState,oneof"`
	xxx_hidden_WithResultDataTypes []string               `protobuf:"bytes,5,rep,name=with_result_data_types,json=withResultDataTypes,proto3"`
	XXX_raceDetectHookData         protoimpl.RaceDetectHookData
	XXX_presence                   [1]uint32
	unknownFields                  protoimpl.UnknownFields
	sizeCache                      protoimpl.SizeCache
}

func (x *Query_Select_CheckPattern) Reset() {
	*x = Query_Select_CheckPattern{}
	mi := &file_turboci_graph_orchestrator_v1_query_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Query_Select_CheckPattern) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Query_Select_CheckPattern) ProtoMessage() {}

func (x *Query_Select_CheckPattern) ProtoReflect() protoreflect.Message {
	mi := &file_turboci_graph_orchestrator_v1_query_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Query_Select_CheckPattern) GetKind() CheckKind {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 0) {
			return x.xxx_hidden_Kind
		}
	}
	return CheckKind_CHECK_KIND_UNKNOWN
}

func (x *Query_Select_CheckPattern) GetIdRegex() string {
	if x != nil {
		if x.xxx_hidden_IdRegex != nil {
			return *x.xxx_hidden_IdRegex
		}
		return ""
	}
	return ""
}

func (x *Query_Select_CheckPattern) GetWithOptionTypes() []string {
	if x != nil {
		return x.xxx_hidden_WithOptionTypes
	}
	return nil
}

func (x *Query_Select_CheckPattern) GetState() CheckState {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 3) {
			return x.xxx_hidden_State
		}
	}
	return CheckState_CHECK_STATE_UNKNOWN
}

func (x *Query_Select_CheckPattern) GetWithResultDataTypes() []string {
	if x != nil {
		return x.xxx_hidden_WithResultDataTypes
	}
	return nil
}

func (x *Query_Select_CheckPattern) SetKind(v CheckKind) {
	x.xxx_hidden_Kind = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 5)
}

func (x *Query_Select_CheckPattern) SetIdRegex(v string) {
	x.xxx_hidden_IdRegex = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 5)
}

func (x *Query_Select_CheckPattern) SetWithOptionTypes(v []string) {
	x.xxx_hidden_WithOptionTypes = v
}

func (x *Query_Select_CheckPattern) SetState(v CheckState) {
	x.xxx_hidden_State = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 5)
}

func (x *Query_Select_CheckPattern) SetWithResultDataTypes(v []string) {
	x.xxx_hidden_WithResultDataTypes = v
}

func (x *Query_Select_CheckPattern) HasKind() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Query_Select_CheckPattern) HasIdRegex() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Query_Select_CheckPattern) HasState() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *Query_Select_CheckPattern) ClearKind() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Kind = CheckKind_CHECK_KIND_UNKNOWN
}

func (x *Query_Select_CheckPattern) ClearIdRegex() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_IdRegex = nil
}

func (x *Query_Select_CheckPattern) ClearState() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_State = CheckState_CHECK_STATE_UNKNOWN
}

type Query_Select_CheckPattern_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Find Checks of this kind (unset means all kinds).
	Kind *CheckKind
	// Find Checks whose `Identifier.Check.id` matches this re2 regex.
	IdRegex *string
	// Find Checks with *any* of these options. Note that you still must set
	// type_urls and collect.data.check.options to actually get the
	// Check Option data in the result set.
	WithOptionTypes []string
	// Find Checks in this state.
	State *CheckState
	// Find Checks with *any* of these result data types. Note that you still
	// must set type_urls and collect.data.check.result_data to actually get the
	// Check Result data in the result set.
	WithResultDataTypes []string
}

func (b0 Query_Select_CheckPattern_builder) Build() *Query_Select_CheckPattern {
	m0 := &Query_Select_CheckPattern{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Kind != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 5)
		x.xxx_hidden_Kind = *b.Kind
	}
	if b.IdRegex != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 5)
		x.xxx_hidden_IdRegex = b.IdRegex
	}
	x.xxx_hidden_WithOptionTypes = b.WithOptionTypes
	if b.State != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 5)
		x.xxx_hidden_State = *b.State
	}
	x.xxx_hidden_WithResultDataTypes = b.WithResultDataTypes
	return m0
}

// Select one or more Stages which match this pattern.
type Query_Select_StagePattern struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Query_Select_StagePattern) Reset() {
	*x = Query_Select_StagePattern{}
	mi := &file_turboci_graph_orchestrator_v1_query_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Query_Select_StagePattern) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Query_Select_StagePattern) ProtoMessage() {}

func (x *Query_Select_StagePattern) ProtoReflect() protoreflect.Message {
	mi := &file_turboci_graph_orchestrator_v1_query_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type Query_Select_StagePattern_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 Query_Select_StagePattern_builder) Build() *Query_Select_StagePattern {
	m0 := &Query_Select_StagePattern{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

// How to expand the dependencies for a Check or Stage.
type Query_Expand_Dependencies struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Mode        QueryExpandDepsMode    `protobuf:"varint,1,opt,name=mode,proto3,enum=turboci.graph.orchestrator.v1.QueryExpandDepsMode,oneof"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Query_Expand_Dependencies) Reset() {
	*x = Query_Expand_Dependencies{}
	mi := &file_turboci_graph_orchestrator_v1_query_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Query_Expand_Dependencies) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Query_Expand_Dependencies) ProtoMessage() {}

func (x *Query_Expand_Dependencies) ProtoReflect() protoreflect.Message {
	mi := &file_turboci_graph_orchestrator_v1_query_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Query_Expand_Dependencies) GetMode() QueryExpandDepsMode {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 0) {
			return x.xxx_hidden_Mode
		}
	}
	return QueryExpandDepsMode_QUERY_EXPAND_DEPS_MODE_UNKNOWN
}

func (x *Query_Expand_Dependencies) SetMode(v QueryExpandDepsMode) {
	x.xxx_hidden_Mode = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *Query_Expand_Dependencies) HasMode() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Query_Expand_Dependencies) ClearMode() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Mode = QueryExpandDepsMode_QUERY_EXPAND_DEPS_MODE_UNKNOWN
}

type Query_Expand_Dependencies_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// How to expand dependencies.
	//
	// Defaults to QUERY_EXPAND_DEPS_MODE_EDGES.
	Mode *QueryExpandDepsMode
}

func (b0 Query_Expand_Dependencies_builder) Build() *Query_Expand_Dependencies {
	m0 := &Query_Expand_Dependencies{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Mode != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Mode = *b.Mode
	}
	return m0
}

// How to expand the dependents for a Check or Stage.
type Query_Expand_Dependents struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Mode        QueryExpandDepsMode    `protobuf:"varint,1,opt,name=mode,proto3,enum=turboci.graph.orchestrator.v1.QueryExpandDepsMode,oneof"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Query_Expand_Dependents) Reset() {
	*x = Query_Expand_Dependents{}
	mi := &file_turboci_graph_orchestrator_v1_query_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Query_Expand_Dependents) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Query_Expand_Dependents) ProtoMessage() {}

func (x *Query_Expand_Dependents) ProtoReflect() protoreflect.Message {
	mi := &file_turboci_graph_orchestrator_v1_query_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Query_Expand_Dependents) GetMode() QueryExpandDepsMode {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 0) {
			return x.xxx_hidden_Mode
		}
	}
	return QueryExpandDepsMode_QUERY_EXPAND_DEPS_MODE_UNKNOWN
}

func (x *Query_Expand_Dependents) SetMode(v QueryExpandDepsMode) {
	x.xxx_hidden_Mode = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *Query_Expand_Dependents) HasMode() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Query_Expand_Dependents) ClearMode() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Mode = QueryExpandDepsMode_QUERY_EXPAND_DEPS_MODE_UNKNOWN
}

type Query_Expand_Dependents_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// How to expand dependents.
	//
	// Defaults to QUERY_EXPAND_DEPS_MODE_EDGES.
	Mode *QueryExpandDepsMode
}

func (b0 Query_Expand_Dependents_builder) Build() *Query_Expand_Dependents {
	m0 := &Query_Expand_Dependents{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Mode != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Mode = *b.Mode
	}
	return m0
}

// Describes what data the caller wants to see for Checks.
type Query_Collect_Check struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Options     bool                   `protobuf:"varint,1,opt,name=options,proto3,oneof"`
	xxx_hidden_ResultData  bool                   `protobuf:"varint,2,opt,name=result_data,json=resultData,proto3,oneof"`
	xxx_hidden_Edits       *RevisionRange         `protobuf:"bytes,3,opt,name=edits,proto3,oneof"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Query_Collect_Check) Reset() {
	*x = Query_Collect_Check{}
	mi := &file_turboci_graph_orchestrator_v1_query_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Query_Collect_Check) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Query_Collect_Check) ProtoMessage() {}

func (x *Query_Collect_Check) ProtoReflect() protoreflect.Message {
	mi := &file_turboci_graph_orchestrator_v1_query_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Query_Collect_Check) GetOptions() bool {
	if x != nil {
		return x.xxx_hidden_Options
	}
	return false
}

func (x *Query_Collect_Check) GetResultData() bool {
	if x != nil {
		return x.xxx_hidden_ResultData
	}
	return false
}

func (x *Query_Collect_Check) GetEdits() *RevisionRange {
	if x != nil {
		return x.xxx_hidden_Edits
	}
	return nil
}

func (x *Query_Collect_Check) SetOptions(v bool) {
	x.xxx_hidden_Options = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *Query_Collect_Check) SetResultData(v bool) {
	x.xxx_hidden_ResultData = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *Query_Collect_Check) SetEdits(v *RevisionRange) {
	x.xxx_hidden_Edits = v
}

func (x *Query_Collect_Check) HasOptions() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Query_Collect_Check) HasResultData() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Query_Collect_Check) HasEdits() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Edits != nil
}

func (x *Query_Collect_Check) ClearOptions() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Options = false
}

func (x *Query_Collect_Check) ClearResultData() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_ResultData = false
}

func (x *Query_Collect_Check) ClearEdits() {
	x.xxx_hidden_Edits = nil
}

type Query_Collect_Check_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Include CheckOptions filtered by `type_urls` for any selected Checks.
	Options *bool
	// Include Result data filtered by `type_urls` for any selected Checks.
	ResultData *bool
	// Include edits only within this range of Revisions.
	//
	// An empty RevisionRange (e.g. {0, 0}) means `all edits`.
	Edits *RevisionRange
}

func (b0 Query_Collect_Check_builder) Build() *Query_Collect_Check {
	m0 := &Query_Collect_Check{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Options != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_Options = *b.Options
	}
	if b.ResultData != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_ResultData = *b.ResultData
	}
	x.xxx_hidden_Edits = b.Edits
	return m0
}

// Describes what data the caller wants to see for Stages.
type Query_Collect_Stage struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Edits *RevisionRange         `protobuf:"bytes,1,opt,name=edits,proto3,oneof"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Query_Collect_Stage) Reset() {
	*x = Query_Collect_Stage{}
	mi := &file_turboci_graph_orchestrator_v1_query_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Query_Collect_Stage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Query_Collect_Stage) ProtoMessage() {}

func (x *Query_Collect_Stage) ProtoReflect() protoreflect.Message {
	mi := &file_turboci_graph_orchestrator_v1_query_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Query_Collect_Stage) GetEdits() *RevisionRange {
	if x != nil {
		return x.xxx_hidden_Edits
	}
	return nil
}

func (x *Query_Collect_Stage) SetEdits(v *RevisionRange) {
	x.xxx_hidden_Edits = v
}

func (x *Query_Collect_Stage) HasEdits() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Edits != nil
}

func (x *Query_Collect_Stage) ClearEdits() {
	x.xxx_hidden_Edits = nil
}

type Query_Collect_Stage_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Include edits only within this range of Revisions.
	//
	// An empty RevisionRange (e.g. {0, 0}) means `all edits`.
	Edits *RevisionRange
}

func (b0 Query_Collect_Stage_builder) Build() *Query_Collect_Stage {
	m0 := &Query_Collect_Stage{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Edits = b.Edits
	return m0
}

var File_turboci_graph_orchestrator_v1_query_proto protoreflect.FileDescriptor

const file_turboci_graph_orchestrator_v1_query_proto_rawDesc = "" +
	"\n" +
	")turboci/graph/orchestrator/v1/query.proto\x12\x1dturboci.graph.orchestrator.v1\x1a%turboci/graph/ids/v1/identifier.proto\x1a.turboci/graph/orchestrator/v1/check_kind.proto\x1a/turboci/graph/orchestrator/v1/check_state.proto\x1a1turboci/graph/orchestrator/v1/field_options.proto\x1a2turboci/graph/orchestrator/v1/revision_range.proto\"\xbc\x0f\n" +
	"\x05Query\x12H\n" +
	"\x06select\x18\x02 \x01(\v2+.turboci.graph.orchestrator.v1.Query.SelectH\x00R\x06select\x88\x01\x01\x12H\n" +
	"\x06expand\x18\x03 \x01(\v2+.turboci.graph.orchestrator.v1.Query.ExpandH\x01R\x06expand\x88\x01\x01\x12K\n" +
	"\acollect\x18\x04 \x01(\v2,.turboci.graph.orchestrator.v1.Query.CollectH\x02R\acollect\x88\x01\x01\x1a\xa2\x06\n" +
	"\x06Select\x12_\n" +
	"\bworkplan\x18\x01 \x01(\v2>.turboci.graph.orchestrator.v1.Query.Select.WorkPlanConstraintH\x00R\bworkplan\x88\x01\x01\x12D\n" +
	"\x05nodes\x18\x02 \x03(\v2 .turboci.graph.ids.v1.IdentifierB\f\x82\x86\xf6\xfb\x0f\x06\x12\x04\n" +
	"\x02\x02\bR\x05nodes\x12_\n" +
	"\x0echeck_patterns\x18\x03 \x03(\v28.turboci.graph.orchestrator.v1.Query.Select.CheckPatternR\rcheckPatterns\x12_\n" +
	"\x0estage_patterns\x18\x04 \x03(\v28.turboci.graph.orchestrator.v1.Query.Select.StagePatternR\rstagePatterns\x1aW\n" +
	"\x12WorkPlanConstraint\x12A\n" +
	"\fin_workplans\x18\x01 \x03(\v2\x1e.turboci.graph.ids.v1.WorkPlanR\vinWorkplans\x1a\xb8\x02\n" +
	"\fCheckPattern\x12A\n" +
	"\x04kind\x18\x01 \x01(\x0e2(.turboci.graph.orchestrator.v1.CheckKindH\x00R\x04kind\x88\x01\x01\x12\x1e\n" +
	"\bid_regex\x18\x02 \x01(\tH\x01R\aidRegex\x88\x01\x01\x12*\n" +
	"\x11with_option_types\x18\x03 \x03(\tR\x0fwithOptionTypes\x12D\n" +
	"\x05state\x18\x04 \x01(\x0e2).turboci.graph.orchestrator.v1.CheckStateH\x02R\x05state\x88\x01\x01\x123\n" +
	"\x16with_result_data_types\x18\x05 \x03(\tR\x13withResultDataTypesB\a\n" +
	"\x05_kindB\v\n" +
	"\t_id_regexB\b\n" +
	"\x06_state\x1a\x0e\n" +
	"\fStagePatternB\v\n" +
	"\t_workplan\x1a\xb2\x03\n" +
	"\x06Expand\x12a\n" +
	"\fdependencies\x18\x01 \x01(\v28.turboci.graph.orchestrator.v1.Query.Expand.DependenciesH\x00R\fdependencies\x88\x01\x01\x12[\n" +
	"\n" +
	"dependents\x18\x02 \x01(\v26.turboci.graph.orchestrator.v1.Query.Expand.DependentsH\x01R\n" +
	"dependents\x88\x01\x01\x1ad\n" +
	"\fDependencies\x12K\n" +
	"\x04mode\x18\x01 \x01(\x0e22.turboci.graph.orchestrator.v1.QueryExpandDepsModeH\x00R\x04mode\x88\x01\x01B\a\n" +
	"\x05_mode\x1ab\n" +
	"\n" +
	"Dependents\x12K\n" +
	"\x04mode\x18\x01 \x01(\x0e22.turboci.graph.orchestrator.v1.QueryExpandDepsModeH\x00R\x04mode\x88\x01\x01B\a\n" +
	"\x05_modeB\x0f\n" +
	"\r_dependenciesB\r\n" +
	"\v_dependents\x1a\xd5\x03\n" +
	"\aCollect\x12M\n" +
	"\x05check\x18\x01 \x01(\v22.turboci.graph.orchestrator.v1.Query.Collect.CheckH\x00R\x05check\x88\x01\x01\x12M\n" +
	"\x05stage\x18\x02 \x01(\v22.turboci.graph.orchestrator.v1.Query.Collect.StageH\x01R\x05stage\x88\x01\x01\x1a\xbb\x01\n" +
	"\x05Check\x12\x1d\n" +
	"\aoptions\x18\x01 \x01(\bH\x00R\aoptions\x88\x01\x01\x12$\n" +
	"\vresult_data\x18\x02 \x01(\bH\x01R\n" +
	"resultData\x88\x01\x01\x12G\n" +
	"\x05edits\x18\x03 \x01(\v2,.turboci.graph.orchestrator.v1.RevisionRangeH\x02R\x05edits\x88\x01\x01B\n" +
	"\n" +
	"\b_optionsB\x0e\n" +
	"\f_result_dataB\b\n" +
	"\x06_edits\x1aZ\n" +
	"\x05Stage\x12G\n" +
	"\x05edits\x18\x01 \x01(\v2,.turboci.graph.orchestrator.v1.RevisionRangeH\x00R\x05edits\x88\x01\x01B\b\n" +
	"\x06_editsB\b\n" +
	"\x06_checkB\b\n" +
	"\x06_stageB\t\n" +
	"\a_selectB\t\n" +
	"\a_expandB\n" +
	"\n" +
	"\b_collect*\x81\x01\n" +
	"\x13QueryExpandDepsMode\x12\"\n" +
	"\x1eQUERY_EXPAND_DEPS_MODE_UNKNOWN\x10\x00\x12 \n" +
	"\x1cQUERY_EXPAND_DEPS_MODE_EDGES\x10\x01\x12$\n" +
	" QUERY_EXPAND_DEPS_MODE_SATISFIED\x10\x02BIP\x01ZEgo.chromium.org/turboci/proto/go/graph/orchestrator/v1;orchestratorpbb\x06proto3"

var file_turboci_graph_orchestrator_v1_query_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_turboci_graph_orchestrator_v1_query_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_turboci_graph_orchestrator_v1_query_proto_goTypes = []any{
	(QueryExpandDepsMode)(0),                // 0: turboci.graph.orchestrator.v1.QueryExpandDepsMode
	(*Query)(nil),                           // 1: turboci.graph.orchestrator.v1.Query
	(*Query_Select)(nil),                    // 2: turboci.graph.orchestrator.v1.Query.Select
	(*Query_Expand)(nil),                    // 3: turboci.graph.orchestrator.v1.Query.Expand
	(*Query_Collect)(nil),                   // 4: turboci.graph.orchestrator.v1.Query.Collect
	(*Query_Select_WorkPlanConstraint)(nil), // 5: turboci.graph.orchestrator.v1.Query.Select.WorkPlanConstraint
	(*Query_Select_CheckPattern)(nil),       // 6: turboci.graph.orchestrator.v1.Query.Select.CheckPattern
	(*Query_Select_StagePattern)(nil),       // 7: turboci.graph.orchestrator.v1.Query.Select.StagePattern
	(*Query_Expand_Dependencies)(nil),       // 8: turboci.graph.orchestrator.v1.Query.Expand.Dependencies
	(*Query_Expand_Dependents)(nil),         // 9: turboci.graph.orchestrator.v1.Query.Expand.Dependents
	(*Query_Collect_Check)(nil),             // 10: turboci.graph.orchestrator.v1.Query.Collect.Check
	(*Query_Collect_Stage)(nil),             // 11: turboci.graph.orchestrator.v1.Query.Collect.Stage
	(*v1.Identifier)(nil),                   // 12: turboci.graph.ids.v1.Identifier
	(*v1.WorkPlan)(nil),                     // 13: turboci.graph.ids.v1.WorkPlan
	(CheckKind)(0),                          // 14: turboci.graph.orchestrator.v1.CheckKind
	(CheckState)(0),                         // 15: turboci.graph.orchestrator.v1.CheckState
	(*RevisionRange)(nil),                   // 16: turboci.graph.orchestrator.v1.RevisionRange
}
var file_turboci_graph_orchestrator_v1_query_proto_depIdxs = []int32{
	2,  // 0: turboci.graph.orchestrator.v1.Query.select:type_name -> turboci.graph.orchestrator.v1.Query.Select
	3,  // 1: turboci.graph.orchestrator.v1.Query.expand:type_name -> turboci.graph.orchestrator.v1.Query.Expand
	4,  // 2: turboci.graph.orchestrator.v1.Query.collect:type_name -> turboci.graph.orchestrator.v1.Query.Collect
	5,  // 3: turboci.graph.orchestrator.v1.Query.Select.workplan:type_name -> turboci.graph.orchestrator.v1.Query.Select.WorkPlanConstraint
	12, // 4: turboci.graph.orchestrator.v1.Query.Select.nodes:type_name -> turboci.graph.ids.v1.Identifier
	6,  // 5: turboci.graph.orchestrator.v1.Query.Select.check_patterns:type_name -> turboci.graph.orchestrator.v1.Query.Select.CheckPattern
	7,  // 6: turboci.graph.orchestrator.v1.Query.Select.stage_patterns:type_name -> turboci.graph.orchestrator.v1.Query.Select.StagePattern
	8,  // 7: turboci.graph.orchestrator.v1.Query.Expand.dependencies:type_name -> turboci.graph.orchestrator.v1.Query.Expand.Dependencies
	9,  // 8: turboci.graph.orchestrator.v1.Query.Expand.dependents:type_name -> turboci.graph.orchestrator.v1.Query.Expand.Dependents
	10, // 9: turboci.graph.orchestrator.v1.Query.Collect.check:type_name -> turboci.graph.orchestrator.v1.Query.Collect.Check
	11, // 10: turboci.graph.orchestrator.v1.Query.Collect.stage:type_name -> turboci.graph.orchestrator.v1.Query.Collect.Stage
	13, // 11: turboci.graph.orchestrator.v1.Query.Select.WorkPlanConstraint.in_workplans:type_name -> turboci.graph.ids.v1.WorkPlan
	14, // 12: turboci.graph.orchestrator.v1.Query.Select.CheckPattern.kind:type_name -> turboci.graph.orchestrator.v1.CheckKind
	15, // 13: turboci.graph.orchestrator.v1.Query.Select.CheckPattern.state:type_name -> turboci.graph.orchestrator.v1.CheckState
	0,  // 14: turboci.graph.orchestrator.v1.Query.Expand.Dependencies.mode:type_name -> turboci.graph.orchestrator.v1.QueryExpandDepsMode
	0,  // 15: turboci.graph.orchestrator.v1.Query.Expand.Dependents.mode:type_name -> turboci.graph.orchestrator.v1.QueryExpandDepsMode
	16, // 16: turboci.graph.orchestrator.v1.Query.Collect.Check.edits:type_name -> turboci.graph.orchestrator.v1.RevisionRange
	16, // 17: turboci.graph.orchestrator.v1.Query.Collect.Stage.edits:type_name -> turboci.graph.orchestrator.v1.RevisionRange
	18, // [18:18] is the sub-list for method output_type
	18, // [18:18] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_turboci_graph_orchestrator_v1_query_proto_init() }
func file_turboci_graph_orchestrator_v1_query_proto_init() {
	if File_turboci_graph_orchestrator_v1_query_proto != nil {
		return
	}
	file_turboci_graph_orchestrator_v1_check_kind_proto_init()
	file_turboci_graph_orchestrator_v1_check_state_proto_init()
	file_turboci_graph_orchestrator_v1_field_options_proto_init()
	file_turboci_graph_orchestrator_v1_revision_range_proto_init()
	file_turboci_graph_orchestrator_v1_query_proto_msgTypes[0].OneofWrappers = []any{}
	file_turboci_graph_orchestrator_v1_query_proto_msgTypes[1].OneofWrappers = []any{}
	file_turboci_graph_orchestrator_v1_query_proto_msgTypes[2].OneofWrappers = []any{}
	file_turboci_graph_orchestrator_v1_query_proto_msgTypes[3].OneofWrappers = []any{}
	file_turboci_graph_orchestrator_v1_query_proto_msgTypes[5].OneofWrappers = []any{}
	file_turboci_graph_orchestrator_v1_query_proto_msgTypes[7].OneofWrappers = []any{}
	file_turboci_graph_orchestrator_v1_query_proto_msgTypes[8].OneofWrappers = []any{}
	file_turboci_graph_orchestrator_v1_query_proto_msgTypes[9].OneofWrappers = []any{}
	file_turboci_graph_orchestrator_v1_query_proto_msgTypes[10].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_turboci_graph_orchestrator_v1_query_proto_rawDesc), len(file_turboci_graph_orchestrator_v1_query_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_turboci_graph_orchestrator_v1_query_proto_goTypes,
		DependencyIndexes: file_turboci_graph_orchestrator_v1_query_proto_depIdxs,
		EnumInfos:         file_turboci_graph_orchestrator_v1_query_proto_enumTypes,
		MessageInfos:      file_turboci_graph_orchestrator_v1_query_proto_msgTypes,
	}.Build()
	File_turboci_graph_orchestrator_v1_query_proto = out.File
	file_turboci_graph_orchestrator_v1_query_proto_goTypes = nil
	file_turboci_graph_orchestrator_v1_query_proto_depIdxs = nil
}
