// Copyright 2025 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: turboci/graph/orchestrator/v1/revision_range.proto

package orchestratorpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RevisionRange represents a range of revisions.
//
// This range is half-open: `[start, end)`.
type RevisionRange struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Start *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=start,proto3,oneof"`
	xxx_hidden_End   *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=end,proto3,oneof"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RevisionRange) Reset() {
	*x = RevisionRange{}
	mi := &file_turboci_graph_orchestrator_v1_revision_range_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevisionRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevisionRange) ProtoMessage() {}

func (x *RevisionRange) ProtoReflect() protoreflect.Message {
	mi := &file_turboci_graph_orchestrator_v1_revision_range_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RevisionRange) GetStart() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_Start
	}
	return nil
}

func (x *RevisionRange) GetEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_End
	}
	return nil
}

func (x *RevisionRange) SetStart(v *timestamppb.Timestamp) {
	x.xxx_hidden_Start = v
}

func (x *RevisionRange) SetEnd(v *timestamppb.Timestamp) {
	x.xxx_hidden_End = v
}

func (x *RevisionRange) HasStart() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Start != nil
}

func (x *RevisionRange) HasEnd() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_End != nil
}

func (x *RevisionRange) ClearStart() {
	x.xxx_hidden_Start = nil
}

func (x *RevisionRange) ClearEnd() {
	x.xxx_hidden_End = nil
}

type RevisionRange_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The first revision in the range.
	//
	// If omitted, the range is unbounded on the lower end.
	Start *timestamppb.Timestamp
	// The first revision *after* the range.
	//
	// Objects with a revision equal to this are NOT included in the range.
	//
	// If omitted, the range is unbounded on the upper end.
	End *timestamppb.Timestamp
}

func (b0 RevisionRange_builder) Build() *RevisionRange {
	m0 := &RevisionRange{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Start = b.Start
	x.xxx_hidden_End = b.End
	return m0
}

var File_turboci_graph_orchestrator_v1_revision_range_proto protoreflect.FileDescriptor

const file_turboci_graph_orchestrator_v1_revision_range_proto_rawDesc = "" +
	"\n" +
	"2turboci/graph/orchestrator/v1/revision_range.proto\x12\x1dturboci.graph.orchestrator.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8b\x01\n" +
	"\rRevisionRange\x125\n" +
	"\x05start\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\x05start\x88\x01\x01\x121\n" +
	"\x03end\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\x03end\x88\x01\x01B\b\n" +
	"\x06_startB\x06\n" +
	"\x04_endBIP\x01ZEgo.chromium.org/turboci/proto/go/graph/orchestrator/v1;orchestratorpbb\x06proto3"

var file_turboci_graph_orchestrator_v1_revision_range_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_turboci_graph_orchestrator_v1_revision_range_proto_goTypes = []any{
	(*RevisionRange)(nil),         // 0: turboci.graph.orchestrator.v1.RevisionRange
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_turboci_graph_orchestrator_v1_revision_range_proto_depIdxs = []int32{
	1, // 0: turboci.graph.orchestrator.v1.RevisionRange.start:type_name -> google.protobuf.Timestamp
	1, // 1: turboci.graph.orchestrator.v1.RevisionRange.end:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_turboci_graph_orchestrator_v1_revision_range_proto_init() }
func file_turboci_graph_orchestrator_v1_revision_range_proto_init() {
	if File_turboci_graph_orchestrator_v1_revision_range_proto != nil {
		return
	}
	file_turboci_graph_orchestrator_v1_revision_range_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_turboci_graph_orchestrator_v1_revision_range_proto_rawDesc), len(file_turboci_graph_orchestrator_v1_revision_range_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_turboci_graph_orchestrator_v1_revision_range_proto_goTypes,
		DependencyIndexes: file_turboci_graph_orchestrator_v1_revision_range_proto_depIdxs,
		MessageInfos:      file_turboci_graph_orchestrator_v1_revision_range_proto_msgTypes,
	}.Build()
	File_turboci_graph_orchestrator_v1_revision_range_proto = out.File
	file_turboci_graph_orchestrator_v1_revision_range_proto_goTypes = nil
	file_turboci_graph_orchestrator_v1_revision_range_proto_depIdxs = nil
}
