// Copyright 2025 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: turboci/graph/orchestrator/v1/stage_attempt_execution_policy.proto

package orchestratorpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// StageAttemptExecutionPolicy describes constraints on how a StageAttempt
// may be executed by the Orchestrator.
type StageAttemptExecutionPolicy struct {
	state                       protoimpl.MessageState                 `protogen:"opaque.v1"`
	xxx_hidden_AttemptHeartbeat *StageAttemptExecutionPolicy_Heartbeat `protobuf:"bytes,1,opt,name=attempt_heartbeat,json=attemptHeartbeat,proto3,oneof"`
	xxx_hidden_Timeout          *StageAttemptExecutionPolicy_Timeout   `protobuf:"bytes,2,opt,name=timeout,proto3,oneof"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *StageAttemptExecutionPolicy) Reset() {
	*x = StageAttemptExecutionPolicy{}
	mi := &file_turboci_graph_orchestrator_v1_stage_attempt_execution_policy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StageAttemptExecutionPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StageAttemptExecutionPolicy) ProtoMessage() {}

func (x *StageAttemptExecutionPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_turboci_graph_orchestrator_v1_stage_attempt_execution_policy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StageAttemptExecutionPolicy) GetAttemptHeartbeat() *StageAttemptExecutionPolicy_Heartbeat {
	if x != nil {
		return x.xxx_hidden_AttemptHeartbeat
	}
	return nil
}

func (x *StageAttemptExecutionPolicy) GetTimeout() *StageAttemptExecutionPolicy_Timeout {
	if x != nil {
		return x.xxx_hidden_Timeout
	}
	return nil
}

func (x *StageAttemptExecutionPolicy) SetAttemptHeartbeat(v *StageAttemptExecutionPolicy_Heartbeat) {
	x.xxx_hidden_AttemptHeartbeat = v
}

func (x *StageAttemptExecutionPolicy) SetTimeout(v *StageAttemptExecutionPolicy_Timeout) {
	x.xxx_hidden_Timeout = v
}

func (x *StageAttemptExecutionPolicy) HasAttemptHeartbeat() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_AttemptHeartbeat != nil
}

func (x *StageAttemptExecutionPolicy) HasTimeout() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Timeout != nil
}

func (x *StageAttemptExecutionPolicy) ClearAttemptHeartbeat() {
	x.xxx_hidden_AttemptHeartbeat = nil
}

func (x *StageAttemptExecutionPolicy) ClearTimeout() {
	x.xxx_hidden_Timeout = nil
}

type StageAttemptExecutionPolicy_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The heartbeat policies for Attempts of this Stage.
	AttemptHeartbeat *StageAttemptExecutionPolicy_Heartbeat
	// The timeout policies for the StageAttempt.
	Timeout *StageAttemptExecutionPolicy_Timeout
}

func (b0 StageAttemptExecutionPolicy_builder) Build() *StageAttemptExecutionPolicy {
	m0 := &StageAttemptExecutionPolicy{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_AttemptHeartbeat = b.AttemptHeartbeat
	x.xxx_hidden_Timeout = b.Timeout
	return m0
}

// Heartbeat indicates the minimum heartbeat interval for Stage Attempts in
// a given state.
//
// Heartbeats allow the Orchestrator to detect missing stages sooner than
// the execution timeout, by declaring non-receipt of a heartbeat message for
// a certain amount of time to mean that the stage is gone and should be
// treated accordingly.
//
// If, say, `pending` is 30s, it means that the executor must send a Heartbeat
// RPC to the Orchestrator at least once every 30s while the Stage Attempt is
// in the PENDING state. It's allowed to heartbeat faster than this interval,
// but shouldn't be necessary.
//
// In addition, we want to ensure that a single lost heartbeat doesn't time
// out an expensive stage that might be close to completion, so the
// Orchestrator will allow 1 missed heartbeat before declaring the next
// non-received heartbeat to mean the stage is gone and should be marked
// INCOMPLETE. However, missing/late heartbeats will be monitored and alerted
// on, as they are likely pre-indicators of something about to go wrong.
//
// In other words, if the Orchestrator doesn't get an RPC from the Stage
// Attempt before missing 2 heartbeats the Orchestrator will mark the Stage
// Attempt as INCOMPLETE.
//
// It is expected that clients writing heartbeats will write them at an
// interval faster than the minimum required here to account for network
// latency and delays (including contention on a busy client machine).
// A suggested rule of thumb is to heartbeat at an interval which is 90% of
// the interval here. So if there is a 30s interval for RUNNING, the client
// would target doing the RPC to heartbeat every 27 seconds. Ultimately,
// though, it's up to the Executor how to ensure that a heartbeat gets to the
// Orchestrator under this deadline.
//
// The fields here correspond to StageAttemptState values where a heartbeat
// is applicable.
//
// It is TYPICAL to only define a heartbeat for `running`.
//
// Heartbeat intervals, if set, currently cannot exceed 30 minutes.
type StageAttemptExecutionPolicy_Heartbeat struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Scheduled   *durationpb.Duration   `protobuf:"bytes,1,opt,name=scheduled,proto3,oneof"`
	xxx_hidden_Running     *durationpb.Duration   `protobuf:"bytes,2,opt,name=running,proto3,oneof"`
	xxx_hidden_TearingDown *durationpb.Duration   `protobuf:"bytes,3,opt,name=tearing_down,json=tearingDown,proto3,oneof"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *StageAttemptExecutionPolicy_Heartbeat) Reset() {
	*x = StageAttemptExecutionPolicy_Heartbeat{}
	mi := &file_turboci_graph_orchestrator_v1_stage_attempt_execution_policy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StageAttemptExecutionPolicy_Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StageAttemptExecutionPolicy_Heartbeat) ProtoMessage() {}

func (x *StageAttemptExecutionPolicy_Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_turboci_graph_orchestrator_v1_stage_attempt_execution_policy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StageAttemptExecutionPolicy_Heartbeat) GetScheduled() *durationpb.Duration {
	if x != nil {
		return x.xxx_hidden_Scheduled
	}
	return nil
}

func (x *StageAttemptExecutionPolicy_Heartbeat) GetRunning() *durationpb.Duration {
	if x != nil {
		return x.xxx_hidden_Running
	}
	return nil
}

func (x *StageAttemptExecutionPolicy_Heartbeat) GetTearingDown() *durationpb.Duration {
	if x != nil {
		return x.xxx_hidden_TearingDown
	}
	return nil
}

func (x *StageAttemptExecutionPolicy_Heartbeat) SetScheduled(v *durationpb.Duration) {
	x.xxx_hidden_Scheduled = v
}

func (x *StageAttemptExecutionPolicy_Heartbeat) SetRunning(v *durationpb.Duration) {
	x.xxx_hidden_Running = v
}

func (x *StageAttemptExecutionPolicy_Heartbeat) SetTearingDown(v *durationpb.Duration) {
	x.xxx_hidden_TearingDown = v
}

func (x *StageAttemptExecutionPolicy_Heartbeat) HasScheduled() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Scheduled != nil
}

func (x *StageAttemptExecutionPolicy_Heartbeat) HasRunning() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Running != nil
}

func (x *StageAttemptExecutionPolicy_Heartbeat) HasTearingDown() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_TearingDown != nil
}

func (x *StageAttemptExecutionPolicy_Heartbeat) ClearScheduled() {
	x.xxx_hidden_Scheduled = nil
}

func (x *StageAttemptExecutionPolicy_Heartbeat) ClearRunning() {
	x.xxx_hidden_Running = nil
}

func (x *StageAttemptExecutionPolicy_Heartbeat) ClearTearingDown() {
	x.xxx_hidden_TearingDown = nil
}

type StageAttemptExecutionPolicy_Heartbeat_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The expected duration that a Stage Attempt can be in the SCHEDULED
	// state without sending a heartbeat.
	//
	// If unset, then there is no required heartbeat cadence, though the stage
	// is still subject to timeouts for the phase.
	Scheduled *durationpb.Duration
	// The expected duration that a Stage Attempt can be in the RUNNING state
	// without sending a heartbeat.
	//
	// If unset, then there is no required heartbeat cadence, though the stage
	// is still subject to timeouts for the phase.
	//
	// NOTE: This heartbeat still applies during the CANCELLING state - it's
	// expected that CANCELLING only applies to Stage Attempts which are
	// RUNNING, but before the Stage Attempt actually knows this.
	Running *durationpb.Duration
	// The expected duration that a Stage Attempt can be in the TEARING_DOWN
	// state without sending a heartbeat.
	//
	// If unset, then there is no required heartbeat cadence, though the stage
	// is still subject to timeouts for the phase.
	TearingDown *durationpb.Duration
}

func (b0 StageAttemptExecutionPolicy_Heartbeat_builder) Build() *StageAttemptExecutionPolicy_Heartbeat {
	m0 := &StageAttemptExecutionPolicy_Heartbeat{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Scheduled = b.Scheduled
	x.xxx_hidden_Running = b.Running
	x.xxx_hidden_TearingDown = b.TearingDown
	return m0
}

// Timeout describes the maximum amount of time a Stage Attempt can be in a
// given state (in addition to restrictions imposed by Heartbeat).
//
// The Orchestrator will automatically transition a Stage Attempt to
// INCOMPLETE after the timeout has passed if the Stage Attempt has not yet
// transitioned to the next state.
type StageAttemptExecutionPolicy_Timeout struct {
	state                       protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_PendingThrottled *durationpb.Duration   `protobuf:"bytes,1,opt,name=pending_throttled,json=pendingThrottled,proto3,oneof"`
	xxx_hidden_Scheduled        *durationpb.Duration   `protobuf:"bytes,2,opt,name=scheduled,proto3,oneof"`
	xxx_hidden_Running          *durationpb.Duration   `protobuf:"bytes,3,opt,name=running,proto3,oneof"`
	xxx_hidden_TearingDown      *durationpb.Duration   `protobuf:"bytes,4,opt,name=tearing_down,json=tearingDown,proto3,oneof"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *StageAttemptExecutionPolicy_Timeout) Reset() {
	*x = StageAttemptExecutionPolicy_Timeout{}
	mi := &file_turboci_graph_orchestrator_v1_stage_attempt_execution_policy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StageAttemptExecutionPolicy_Timeout) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StageAttemptExecutionPolicy_Timeout) ProtoMessage() {}

func (x *StageAttemptExecutionPolicy_Timeout) ProtoReflect() protoreflect.Message {
	mi := &file_turboci_graph_orchestrator_v1_stage_attempt_execution_policy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StageAttemptExecutionPolicy_Timeout) GetPendingThrottled() *durationpb.Duration {
	if x != nil {
		return x.xxx_hidden_PendingThrottled
	}
	return nil
}

func (x *StageAttemptExecutionPolicy_Timeout) GetScheduled() *durationpb.Duration {
	if x != nil {
		return x.xxx_hidden_Scheduled
	}
	return nil
}

func (x *StageAttemptExecutionPolicy_Timeout) GetRunning() *durationpb.Duration {
	if x != nil {
		return x.xxx_hidden_Running
	}
	return nil
}

func (x *StageAttemptExecutionPolicy_Timeout) GetTearingDown() *durationpb.Duration {
	if x != nil {
		return x.xxx_hidden_TearingDown
	}
	return nil
}

func (x *StageAttemptExecutionPolicy_Timeout) SetPendingThrottled(v *durationpb.Duration) {
	x.xxx_hidden_PendingThrottled = v
}

func (x *StageAttemptExecutionPolicy_Timeout) SetScheduled(v *durationpb.Duration) {
	x.xxx_hidden_Scheduled = v
}

func (x *StageAttemptExecutionPolicy_Timeout) SetRunning(v *durationpb.Duration) {
	x.xxx_hidden_Running = v
}

func (x *StageAttemptExecutionPolicy_Timeout) SetTearingDown(v *durationpb.Duration) {
	x.xxx_hidden_TearingDown = v
}

func (x *StageAttemptExecutionPolicy_Timeout) HasPendingThrottled() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_PendingThrottled != nil
}

func (x *StageAttemptExecutionPolicy_Timeout) HasScheduled() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Scheduled != nil
}

func (x *StageAttemptExecutionPolicy_Timeout) HasRunning() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Running != nil
}

func (x *StageAttemptExecutionPolicy_Timeout) HasTearingDown() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_TearingDown != nil
}

func (x *StageAttemptExecutionPolicy_Timeout) ClearPendingThrottled() {
	x.xxx_hidden_PendingThrottled = nil
}

func (x *StageAttemptExecutionPolicy_Timeout) ClearScheduled() {
	x.xxx_hidden_Scheduled = nil
}

func (x *StageAttemptExecutionPolicy_Timeout) ClearRunning() {
	x.xxx_hidden_Running = nil
}

func (x *StageAttemptExecutionPolicy_Timeout) ClearTearingDown() {
	x.xxx_hidden_TearingDown = nil
}

type StageAttemptExecutionPolicy_Timeout_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The maximum amount of time a Stage Attempt can be in the
	// PENDING/THROTTLED state.
	//
	// It is calculated from the time the Attempt first enters `PENDING` to the
	// time that it leaves `PENDING` for a non-THROTTLED state.
	//
	// If unset, then there is a large default limit on how long a Stage Attempt
	// can be in the PENDING/THROTTLED state.
	PendingThrottled *durationpb.Duration
	// The maximum amount of time a Stage Attempt can be in the SCHEDULED
	// state.
	//
	// If unset, then there is a large default limit on how long a Stage Attempt
	// can be in the SCHEDULED state.
	Scheduled *durationpb.Duration
	// The maximum amount of time a Stage Attempt can be in the RUNNING state.
	//
	// If unset, then there is a large default limit on how long a Stage Attempt
	// can be in the RUNNING state.
	//
	// NOTE: This timeout still applies during the CANCELLING state - it's
	// expected that CANCELLING only applies to Stage Attempts which are
	// RUNNING, but before the Stage Attempt actually knows this.
	Running *durationpb.Duration
	// The maximum amount of time a Stage Attempt can be in the
	// TEARING_DOWN state.
	//
	// If unset, then there is a large default limit on how long a Stage Attempt can be in
	// the TEARING_DOWN state.
	TearingDown *durationpb.Duration
}

func (b0 StageAttemptExecutionPolicy_Timeout_builder) Build() *StageAttemptExecutionPolicy_Timeout {
	m0 := &StageAttemptExecutionPolicy_Timeout{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_PendingThrottled = b.PendingThrottled
	x.xxx_hidden_Scheduled = b.Scheduled
	x.xxx_hidden_Running = b.Running
	x.xxx_hidden_TearingDown = b.TearingDown
	return m0
}

var File_turboci_graph_orchestrator_v1_stage_attempt_execution_policy_proto protoreflect.FileDescriptor

const file_turboci_graph_orchestrator_v1_stage_attempt_execution_policy_proto_rawDesc = "" +
	"\n" +
	"Bturboci/graph/orchestrator/v1/stage_attempt_execution_policy.proto\x12\x1dturboci.graph.orchestrator.v1\x1a\x1egoogle/protobuf/duration.proto\"\xe3\x06\n" +
	"\x1bStageAttemptExecutionPolicy\x12v\n" +
	"\x11attempt_heartbeat\x18\x01 \x01(\v2D.turboci.graph.orchestrator.v1.StageAttemptExecutionPolicy.HeartbeatH\x00R\x10attemptHeartbeat\x88\x01\x01\x12a\n" +
	"\atimeout\x18\x02 \x01(\v2B.turboci.graph.orchestrator.v1.StageAttemptExecutionPolicy.TimeoutH\x01R\atimeout\x88\x01\x01\x1a\xf1\x01\n" +
	"\tHeartbeat\x12<\n" +
	"\tscheduled\x18\x01 \x01(\v2\x19.google.protobuf.DurationH\x00R\tscheduled\x88\x01\x01\x128\n" +
	"\arunning\x18\x02 \x01(\v2\x19.google.protobuf.DurationH\x01R\arunning\x88\x01\x01\x12A\n" +
	"\ftearing_down\x18\x03 \x01(\v2\x19.google.protobuf.DurationH\x02R\vtearingDown\x88\x01\x01B\f\n" +
	"\n" +
	"_scheduledB\n" +
	"\n" +
	"\b_runningB\x0f\n" +
	"\r_tearing_down\x1a\xd2\x02\n" +
	"\aTimeout\x12K\n" +
	"\x11pending_throttled\x18\x01 \x01(\v2\x19.google.protobuf.DurationH\x00R\x10pendingThrottled\x88\x01\x01\x12<\n" +
	"\tscheduled\x18\x02 \x01(\v2\x19.google.protobuf.DurationH\x01R\tscheduled\x88\x01\x01\x128\n" +
	"\arunning\x18\x03 \x01(\v2\x19.google.protobuf.DurationH\x02R\arunning\x88\x01\x01\x12A\n" +
	"\ftearing_down\x18\x04 \x01(\v2\x19.google.protobuf.DurationH\x03R\vtearingDown\x88\x01\x01B\x14\n" +
	"\x12_pending_throttledB\f\n" +
	"\n" +
	"_scheduledB\n" +
	"\n" +
	"\b_runningB\x0f\n" +
	"\r_tearing_downB\x14\n" +
	"\x12_attempt_heartbeatB\n" +
	"\n" +
	"\b_timeoutBIP\x01ZEgo.chromium.org/turboci/proto/go/graph/orchestrator/v1;orchestratorpbb\x06proto3"

var file_turboci_graph_orchestrator_v1_stage_attempt_execution_policy_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_turboci_graph_orchestrator_v1_stage_attempt_execution_policy_proto_goTypes = []any{
	(*StageAttemptExecutionPolicy)(nil),           // 0: turboci.graph.orchestrator.v1.StageAttemptExecutionPolicy
	(*StageAttemptExecutionPolicy_Heartbeat)(nil), // 1: turboci.graph.orchestrator.v1.StageAttemptExecutionPolicy.Heartbeat
	(*StageAttemptExecutionPolicy_Timeout)(nil),   // 2: turboci.graph.orchestrator.v1.StageAttemptExecutionPolicy.Timeout
	(*durationpb.Duration)(nil),                   // 3: google.protobuf.Duration
}
var file_turboci_graph_orchestrator_v1_stage_attempt_execution_policy_proto_depIdxs = []int32{
	1, // 0: turboci.graph.orchestrator.v1.StageAttemptExecutionPolicy.attempt_heartbeat:type_name -> turboci.graph.orchestrator.v1.StageAttemptExecutionPolicy.Heartbeat
	2, // 1: turboci.graph.orchestrator.v1.StageAttemptExecutionPolicy.timeout:type_name -> turboci.graph.orchestrator.v1.StageAttemptExecutionPolicy.Timeout
	3, // 2: turboci.graph.orchestrator.v1.StageAttemptExecutionPolicy.Heartbeat.scheduled:type_name -> google.protobuf.Duration
	3, // 3: turboci.graph.orchestrator.v1.StageAttemptExecutionPolicy.Heartbeat.running:type_name -> google.protobuf.Duration
	3, // 4: turboci.graph.orchestrator.v1.StageAttemptExecutionPolicy.Heartbeat.tearing_down:type_name -> google.protobuf.Duration
	3, // 5: turboci.graph.orchestrator.v1.StageAttemptExecutionPolicy.Timeout.pending_throttled:type_name -> google.protobuf.Duration
	3, // 6: turboci.graph.orchestrator.v1.StageAttemptExecutionPolicy.Timeout.scheduled:type_name -> google.protobuf.Duration
	3, // 7: turboci.graph.orchestrator.v1.StageAttemptExecutionPolicy.Timeout.running:type_name -> google.protobuf.Duration
	3, // 8: turboci.graph.orchestrator.v1.StageAttemptExecutionPolicy.Timeout.tearing_down:type_name -> google.protobuf.Duration
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_turboci_graph_orchestrator_v1_stage_attempt_execution_policy_proto_init() }
func file_turboci_graph_orchestrator_v1_stage_attempt_execution_policy_proto_init() {
	if File_turboci_graph_orchestrator_v1_stage_attempt_execution_policy_proto != nil {
		return
	}
	file_turboci_graph_orchestrator_v1_stage_attempt_execution_policy_proto_msgTypes[0].OneofWrappers = []any{}
	file_turboci_graph_orchestrator_v1_stage_attempt_execution_policy_proto_msgTypes[1].OneofWrappers = []any{}
	file_turboci_graph_orchestrator_v1_stage_attempt_execution_policy_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_turboci_graph_orchestrator_v1_stage_attempt_execution_policy_proto_rawDesc), len(file_turboci_graph_orchestrator_v1_stage_attempt_execution_policy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_turboci_graph_orchestrator_v1_stage_attempt_execution_policy_proto_goTypes,
		DependencyIndexes: file_turboci_graph_orchestrator_v1_stage_attempt_execution_policy_proto_depIdxs,
		MessageInfos:      file_turboci_graph_orchestrator_v1_stage_attempt_execution_policy_proto_msgTypes,
	}.Build()
	File_turboci_graph_orchestrator_v1_stage_attempt_execution_policy_proto = out.File
	file_turboci_graph_orchestrator_v1_stage_attempt_execution_policy_proto_goTypes = nil
	file_turboci_graph_orchestrator_v1_stage_attempt_execution_policy_proto_depIdxs = nil
}
