// Copyright 2025 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: turboci/graph/orchestrator/v1/stage_execution_policy.proto

package orchestratorpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// StageExecutionPolicy describes constraints on how a Stage may be executed
// by the Orchestrator.
type StageExecutionPolicy struct {
	state                                     protoimpl.MessageState       `protogen:"opaque.v1"`
	xxx_hidden_Retry                          *StageExecutionPolicy_Retry  `protobuf:"bytes,1,opt,name=retry,proto3,oneof"`
	xxx_hidden_StageTimeout                   *durationpb.Duration         `protobuf:"bytes,2,opt,name=stage_timeout,json=stageTimeout,proto3,oneof"`
	xxx_hidden_ExecuteAtLeastOneAttempt       bool                         `protobuf:"varint,3,opt,name=execute_at_least_one_attempt,json=executeAtLeastOneAttempt,proto3,oneof"`
	xxx_hidden_AttemptExecutionPolicyTemplate *StageAttemptExecutionPolicy `protobuf:"bytes,4,opt,name=attempt_execution_policy_template,json=attemptExecutionPolicyTemplate,proto3,oneof"`
	xxx_hidden_ThrottleFirstAttemptUntil      *timestamppb.Timestamp       `protobuf:"bytes,5,opt,name=throttle_first_attempt_until,json=throttleFirstAttemptUntil,proto3,oneof"`
	XXX_raceDetectHookData                    protoimpl.RaceDetectHookData
	XXX_presence                              [1]uint32
	unknownFields                             protoimpl.UnknownFields
	sizeCache                                 protoimpl.SizeCache
}

func (x *StageExecutionPolicy) Reset() {
	*x = StageExecutionPolicy{}
	mi := &file_turboci_graph_orchestrator_v1_stage_execution_policy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StageExecutionPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StageExecutionPolicy) ProtoMessage() {}

func (x *StageExecutionPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_turboci_graph_orchestrator_v1_stage_execution_policy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StageExecutionPolicy) GetRetry() *StageExecutionPolicy_Retry {
	if x != nil {
		return x.xxx_hidden_Retry
	}
	return nil
}

func (x *StageExecutionPolicy) GetStageTimeout() *durationpb.Duration {
	if x != nil {
		return x.xxx_hidden_StageTimeout
	}
	return nil
}

func (x *StageExecutionPolicy) GetExecuteAtLeastOneAttempt() bool {
	if x != nil {
		return x.xxx_hidden_ExecuteAtLeastOneAttempt
	}
	return false
}

func (x *StageExecutionPolicy) GetAttemptExecutionPolicyTemplate() *StageAttemptExecutionPolicy {
	if x != nil {
		return x.xxx_hidden_AttemptExecutionPolicyTemplate
	}
	return nil
}

func (x *StageExecutionPolicy) GetThrottleFirstAttemptUntil() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_ThrottleFirstAttemptUntil
	}
	return nil
}

func (x *StageExecutionPolicy) SetRetry(v *StageExecutionPolicy_Retry) {
	x.xxx_hidden_Retry = v
}

func (x *StageExecutionPolicy) SetStageTimeout(v *durationpb.Duration) {
	x.xxx_hidden_StageTimeout = v
}

func (x *StageExecutionPolicy) SetExecuteAtLeastOneAttempt(v bool) {
	x.xxx_hidden_ExecuteAtLeastOneAttempt = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 5)
}

func (x *StageExecutionPolicy) SetAttemptExecutionPolicyTemplate(v *StageAttemptExecutionPolicy) {
	x.xxx_hidden_AttemptExecutionPolicyTemplate = v
}

func (x *StageExecutionPolicy) SetThrottleFirstAttemptUntil(v *timestamppb.Timestamp) {
	x.xxx_hidden_ThrottleFirstAttemptUntil = v
}

func (x *StageExecutionPolicy) HasRetry() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Retry != nil
}

func (x *StageExecutionPolicy) HasStageTimeout() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_StageTimeout != nil
}

func (x *StageExecutionPolicy) HasExecuteAtLeastOneAttempt() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *StageExecutionPolicy) HasAttemptExecutionPolicyTemplate() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_AttemptExecutionPolicyTemplate != nil
}

func (x *StageExecutionPolicy) HasThrottleFirstAttemptUntil() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_ThrottleFirstAttemptUntil != nil
}

func (x *StageExecutionPolicy) ClearRetry() {
	x.xxx_hidden_Retry = nil
}

func (x *StageExecutionPolicy) ClearStageTimeout() {
	x.xxx_hidden_StageTimeout = nil
}

func (x *StageExecutionPolicy) ClearExecuteAtLeastOneAttempt() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_ExecuteAtLeastOneAttempt = false
}

func (x *StageExecutionPolicy) ClearAttemptExecutionPolicyTemplate() {
	x.xxx_hidden_AttemptExecutionPolicyTemplate = nil
}

func (x *StageExecutionPolicy) ClearThrottleFirstAttemptUntil() {
	x.xxx_hidden_ThrottleFirstAttemptUntil = nil
}

type StageExecutionPolicy_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Policy for retrying this Stage across multiple Attempts.
	//
	// If omitted, the Stage will be attempted at most once (if at all permitted
	// by `stage_timeout` and `execute_at_least_one_attempt`).
	Retry *StageExecutionPolicy_Retry
	// An approximate cap on the maximum amount of time the Stage itself can stay
	// in a non-FINAL state.
	//
	// This timeout starts from the time the Stage is *created*.
	//
	// When launching an attempt, the orchestrator will estimate when the attempt
	// will finish executing in the most pessimistic scenario (e.g. hitting all
	// possible StageAttemptExecutionPolicy timeouts). A new attempt will be
	// allowed to run if its estimated completion time still fits within the stage
	// timeout. Retrying an attempt has extra conditions (see Retry for details).
	// If `execute_at_least_one_attempt` is true, then this timeout will be
	// totally ignored when launching the first attempt.
	//
	// This timeout normally should be greater than the cumulative timeouts in
	// StageAttemptExecutionPolicy. It should also account for some amount of time
	// for this Stage to enter the ATTEMPTING state in the first place.
	//
	// Note this timeout is enforced only when launching an attempt, i.e. if
	// a stage attempt is already running, it will always be allowed to run to its
	// completion (or an attempt timeout per its own StageAttemptExecutionPolicy).
	//
	// Note that the timeout enforcement doesn't apply to stages that are still
	// blocked on their dependencies: if a stage timeout is reached while the
	// stage is still in PLANNED state, nothing will happen to the stage state at
	// that particular moment. The stage will remain in PLANNED state until its
	// dependencies are resolved (just like happens in a normal scenario). Only
	// then will it potentially move into FINAL state due to hitting the stage
	// timeout (depending on `execute_at_least_one_attempt`).
	//
	// If unset, this timeout will not apply at all (i.e. logically this timeout
	// will be infinite).
	StageTimeout *durationpb.Duration
	// If true, always launch the first attempt, totally ignoring `stage_timeout`.
	//
	// If false or unset, and the estimated stage attempt completion time exceeds
	// the stage timeout (see `stage_timeout` for details), the stage (when its
	// dependencies are unblocked) will move into FINAL state immediately without
	// running any attempts at all. StageConcludedReason will be TIMEOUT.
	ExecuteAtLeastOneAttempt *bool
	// Template for an attempt level execution policy.
	//
	// Each attempt will be created with this policy as requested. But the
	// executor may augment the policy by merging the requested policy and what
	// is in the configs.
	AttemptExecutionPolicyTemplate *StageAttemptExecutionPolicy
	// If set, specifies the earliest time the stage is allowed to run.
	//
	// If the stage is unblocked before that time, its first attempt will be
	// created in THROTTLED state and it won't start running until the given time.
	// If the stage is unblocked past that time, it will start running its first
	// attempt right away.
	//
	// If unset, the stage will start running its first attempt as soon as it is
	// unblocked.
	ThrottleFirstAttemptUntil *timestamppb.Timestamp
}

func (b0 StageExecutionPolicy_builder) Build() *StageExecutionPolicy {
	m0 := &StageExecutionPolicy{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Retry = b.Retry
	x.xxx_hidden_StageTimeout = b.StageTimeout
	if b.ExecuteAtLeastOneAttempt != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 5)
		x.xxx_hidden_ExecuteAtLeastOneAttempt = *b.ExecuteAtLeastOneAttempt
	}
	x.xxx_hidden_AttemptExecutionPolicyTemplate = b.AttemptExecutionPolicyTemplate
	x.xxx_hidden_ThrottleFirstAttemptUntil = b.ThrottleFirstAttemptUntil
	return m0
}

// Retry describes the policy for retrying a Stage across multiple Attempts.
type StageExecutionPolicy_Retry struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_MaxRetries  int32                  `protobuf:"varint,1,opt,name=max_retries,json=maxRetries,proto3,oneof"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *StageExecutionPolicy_Retry) Reset() {
	*x = StageExecutionPolicy_Retry{}
	mi := &file_turboci_graph_orchestrator_v1_stage_execution_policy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StageExecutionPolicy_Retry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StageExecutionPolicy_Retry) ProtoMessage() {}

func (x *StageExecutionPolicy_Retry) ProtoReflect() protoreflect.Message {
	mi := &file_turboci_graph_orchestrator_v1_stage_execution_policy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StageExecutionPolicy_Retry) GetMaxRetries() int32 {
	if x != nil {
		return x.xxx_hidden_MaxRetries
	}
	return 0
}

func (x *StageExecutionPolicy_Retry) SetMaxRetries(v int32) {
	x.xxx_hidden_MaxRetries = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *StageExecutionPolicy_Retry) HasMaxRetries() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *StageExecutionPolicy_Retry) ClearMaxRetries() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_MaxRetries = 0
}

type StageExecutionPolicy_Retry_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The maximum number of retries (apart from the first attempt) that will be
	// made for this Stage.
	//
	// If an Attempt fails (i.e. becomes INCOMPLETE), a new Attempt is created
	// when all of the below is true:
	//  1. The new number of Attempts does not exceed max_retries+1. If this
	//     condition is violated, StageConcludedReason will be NO_RETRIES_LEFT.
	//  2. There's enough time left in `stage_timeout` to run the new attempt
	//     to completion in the most pessimistic case (waiting the attempt
	//     retry backoff timer and hitting all possible stage attempt timeouts
	//     configured in the StageAttemptExecutionPolicy). If this condition
	//     is violated, StageConcludedReason will be TIMEOUT.
	//  3. The last attempt had `WriteNodes.current_state.block_new_attempts`
	//     set to false. If this condition is violated, StageConcludedReason
	//     will be FINAL_ATTEMPT_BLOCKED_RETRY.
	//
	// If no retries are allowed, the stage will transition to FINAL or
	// AWAITING_GROUP state (in case the incomplete attempt managed to submit
	// a continuation group before it died).
	MaxRetries *int32
}

func (b0 StageExecutionPolicy_Retry_builder) Build() *StageExecutionPolicy_Retry {
	m0 := &StageExecutionPolicy_Retry{}
	b, x := &b0, m0
	_, _ = b, x
	if b.MaxRetries != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_MaxRetries = *b.MaxRetries
	}
	return m0
}

var File_turboci_graph_orchestrator_v1_stage_execution_policy_proto protoreflect.FileDescriptor

const file_turboci_graph_orchestrator_v1_stage_execution_policy_proto_rawDesc = "" +
	"\n" +
	":turboci/graph/orchestrator/v1/stage_execution_policy.proto\x12\x1dturboci.graph.orchestrator.v1\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1aBturboci/graph/orchestrator/v1/stage_attempt_execution_policy.proto\"\xa8\x05\n" +
	"\x14StageExecutionPolicy\x12T\n" +
	"\x05retry\x18\x01 \x01(\v29.turboci.graph.orchestrator.v1.StageExecutionPolicy.RetryH\x00R\x05retry\x88\x01\x01\x12C\n" +
	"\rstage_timeout\x18\x02 \x01(\v2\x19.google.protobuf.DurationH\x01R\fstageTimeout\x88\x01\x01\x12C\n" +
	"\x1cexecute_at_least_one_attempt\x18\x03 \x01(\bH\x02R\x18executeAtLeastOneAttempt\x88\x01\x01\x12\x8a\x01\n" +
	"!attempt_execution_policy_template\x18\x04 \x01(\v2:.turboci.graph.orchestrator.v1.StageAttemptExecutionPolicyH\x03R\x1eattemptExecutionPolicyTemplate\x88\x01\x01\x12`\n" +
	"\x1cthrottle_first_attempt_until\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampH\x04R\x19throttleFirstAttemptUntil\x88\x01\x01\x1a=\n" +
	"\x05Retry\x12$\n" +
	"\vmax_retries\x18\x01 \x01(\x05H\x00R\n" +
	"maxRetries\x88\x01\x01B\x0e\n" +
	"\f_max_retriesB\b\n" +
	"\x06_retryB\x10\n" +
	"\x0e_stage_timeoutB\x1f\n" +
	"\x1d_execute_at_least_one_attemptB$\n" +
	"\"_attempt_execution_policy_templateB\x1f\n" +
	"\x1d_throttle_first_attempt_untilBIP\x01ZEgo.chromium.org/turboci/proto/go/graph/orchestrator/v1;orchestratorpbb\x06proto3"

var file_turboci_graph_orchestrator_v1_stage_execution_policy_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_turboci_graph_orchestrator_v1_stage_execution_policy_proto_goTypes = []any{
	(*StageExecutionPolicy)(nil),        // 0: turboci.graph.orchestrator.v1.StageExecutionPolicy
	(*StageExecutionPolicy_Retry)(nil),  // 1: turboci.graph.orchestrator.v1.StageExecutionPolicy.Retry
	(*durationpb.Duration)(nil),         // 2: google.protobuf.Duration
	(*StageAttemptExecutionPolicy)(nil), // 3: turboci.graph.orchestrator.v1.StageAttemptExecutionPolicy
	(*timestamppb.Timestamp)(nil),       // 4: google.protobuf.Timestamp
}
var file_turboci_graph_orchestrator_v1_stage_execution_policy_proto_depIdxs = []int32{
	1, // 0: turboci.graph.orchestrator.v1.StageExecutionPolicy.retry:type_name -> turboci.graph.orchestrator.v1.StageExecutionPolicy.Retry
	2, // 1: turboci.graph.orchestrator.v1.StageExecutionPolicy.stage_timeout:type_name -> google.protobuf.Duration
	3, // 2: turboci.graph.orchestrator.v1.StageExecutionPolicy.attempt_execution_policy_template:type_name -> turboci.graph.orchestrator.v1.StageAttemptExecutionPolicy
	4, // 3: turboci.graph.orchestrator.v1.StageExecutionPolicy.throttle_first_attempt_until:type_name -> google.protobuf.Timestamp
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_turboci_graph_orchestrator_v1_stage_execution_policy_proto_init() }
func file_turboci_graph_orchestrator_v1_stage_execution_policy_proto_init() {
	if File_turboci_graph_orchestrator_v1_stage_execution_policy_proto != nil {
		return
	}
	file_turboci_graph_orchestrator_v1_stage_attempt_execution_policy_proto_init()
	file_turboci_graph_orchestrator_v1_stage_execution_policy_proto_msgTypes[0].OneofWrappers = []any{}
	file_turboci_graph_orchestrator_v1_stage_execution_policy_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_turboci_graph_orchestrator_v1_stage_execution_policy_proto_rawDesc), len(file_turboci_graph_orchestrator_v1_stage_execution_policy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_turboci_graph_orchestrator_v1_stage_execution_policy_proto_goTypes,
		DependencyIndexes: file_turboci_graph_orchestrator_v1_stage_execution_policy_proto_depIdxs,
		MessageInfos:      file_turboci_graph_orchestrator_v1_stage_execution_policy_proto_msgTypes,
	}.Build()
	File_turboci_graph_orchestrator_v1_stage_execution_policy_proto = out.File
	file_turboci_graph_orchestrator_v1_stage_execution_policy_proto_goTypes = nil
	file_turboci_graph_orchestrator_v1_stage_execution_policy_proto_depIdxs = nil
}
