// Copyright 2025 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: turboci/graph/orchestrator/v1/stage_view.proto

package orchestratorpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// StageView is a collated, partial, view of a single Stage and the nodes
// which belong to it.
type StageView struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Stage *Stage                 `protobuf:"bytes,1,opt,name=stage,proto3,oneof"`
	xxx_hidden_Edits *[]*StageEditView      `protobuf:"bytes,3,rep,name=edits,proto3"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StageView) Reset() {
	*x = StageView{}
	mi := &file_turboci_graph_orchestrator_v1_stage_view_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StageView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StageView) ProtoMessage() {}

func (x *StageView) ProtoReflect() protoreflect.Message {
	mi := &file_turboci_graph_orchestrator_v1_stage_view_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StageView) GetStage() *Stage {
	if x != nil {
		return x.xxx_hidden_Stage
	}
	return nil
}

func (x *StageView) GetEdits() []*StageEditView {
	if x != nil {
		if x.xxx_hidden_Edits != nil {
			return *x.xxx_hidden_Edits
		}
	}
	return nil
}

func (x *StageView) SetStage(v *Stage) {
	x.xxx_hidden_Stage = v
}

func (x *StageView) SetEdits(v []*StageEditView) {
	x.xxx_hidden_Edits = &v
}

func (x *StageView) HasStage() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Stage != nil
}

func (x *StageView) ClearStage() {
	x.xxx_hidden_Stage = nil
}

type StageView_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The Stage itself - always present.
	Stage *Stage
	// StageEdits for this Stage which are being read.
	//
	// Some StageEdits may be omitted if the user did not request them.
	Edits []*StageEditView
}

func (b0 StageView_builder) Build() *StageView {
	m0 := &StageView{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Stage = b.Stage
	x.xxx_hidden_Edits = &b.Edits
	return m0
}

var File_turboci_graph_orchestrator_v1_stage_view_proto protoreflect.FileDescriptor

const file_turboci_graph_orchestrator_v1_stage_view_proto_rawDesc = "" +
	"\n" +
	".turboci/graph/orchestrator/v1/stage_view.proto\x12\x1dturboci.graph.orchestrator.v1\x1a)turboci/graph/orchestrator/v1/stage.proto\x1a3turboci/graph/orchestrator/v1/stage_edit_view.proto\"\xa0\x01\n" +
	"\tStageView\x12?\n" +
	"\x05stage\x18\x01 \x01(\v2$.turboci.graph.orchestrator.v1.StageH\x00R\x05stage\x88\x01\x01\x12B\n" +
	"\x05edits\x18\x03 \x03(\v2,.turboci.graph.orchestrator.v1.StageEditViewR\x05editsB\b\n" +
	"\x06_stageJ\x04\b\x02\x10\x03BIP\x01ZEgo.chromium.org/turboci/proto/go/graph/orchestrator/v1;orchestratorpbb\x06proto3"

var file_turboci_graph_orchestrator_v1_stage_view_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_turboci_graph_orchestrator_v1_stage_view_proto_goTypes = []any{
	(*StageView)(nil),     // 0: turboci.graph.orchestrator.v1.StageView
	(*Stage)(nil),         // 1: turboci.graph.orchestrator.v1.Stage
	(*StageEditView)(nil), // 2: turboci.graph.orchestrator.v1.StageEditView
}
var file_turboci_graph_orchestrator_v1_stage_view_proto_depIdxs = []int32{
	1, // 0: turboci.graph.orchestrator.v1.StageView.stage:type_name -> turboci.graph.orchestrator.v1.Stage
	2, // 1: turboci.graph.orchestrator.v1.StageView.edits:type_name -> turboci.graph.orchestrator.v1.StageEditView
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_turboci_graph_orchestrator_v1_stage_view_proto_init() }
func file_turboci_graph_orchestrator_v1_stage_view_proto_init() {
	if File_turboci_graph_orchestrator_v1_stage_view_proto != nil {
		return
	}
	file_turboci_graph_orchestrator_v1_stage_proto_init()
	file_turboci_graph_orchestrator_v1_stage_edit_view_proto_init()
	file_turboci_graph_orchestrator_v1_stage_view_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_turboci_graph_orchestrator_v1_stage_view_proto_rawDesc), len(file_turboci_graph_orchestrator_v1_stage_view_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_turboci_graph_orchestrator_v1_stage_view_proto_goTypes,
		DependencyIndexes: file_turboci_graph_orchestrator_v1_stage_view_proto_depIdxs,
		MessageInfos:      file_turboci_graph_orchestrator_v1_stage_view_proto_msgTypes,
	}.Build()
	File_turboci_graph_orchestrator_v1_stage_view_proto = out.File
	file_turboci_graph_orchestrator_v1_stage_view_proto_goTypes = nil
	file_turboci_graph_orchestrator_v1_stage_view_proto_depIdxs = nil
}
