// Copyright 2026 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: turboci/graph/orchestrator/v1/transaction_details.proto

package orchestratorpb

import (
	v1 "go.chromium.org/turboci/proto/go/graph/ids/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TransactionDetails encapsulates the information necessary to make a
// WriteNodes RPC conditional based on the state of some previously observed
// nodes. It does this by describing the snapshot of the graph which the writer
// observed. TurboCI Orchestrator will ensure that these nodes haven't changed
// since the writer observed them.
//
// It is valid to include nodes which were absent from the snapshot, if the
// writer wants to make its write conditional on their absence.
//
// Transaction Procedure:
//
//	retry {
//	  nodes, snapshot_version = QueryNodes(...)
//	  # computations
//
//	  more_nodes, _ = QueryNodes(..., ensure_version=snapshot_version)
//	  # This will cause QueryNodes to fail if any returned nodes have
//	  # a version greater than `snapshot_version`. This will allow the
//	  # transaction loop to retry immediately, rather than waiting for the
//	  # WriteNodes call.
//
//	  # computations
//
//	  if WriteNodes(..., txn={nodes+more_nodes, snapshot_version}) {
//	    # Success!
//
//	    # If you need to make another write, you CAN use the written_version
//	    # in the response from WriteNodes as an input snapshot_version to the
//	    # subsequent transaction. However, it's important that if this second
//	    # transaction gets a conflict that it will need to re-query for the
//	    # new state of the graph. For this reason it's recommended to either
//	    # include all the writes in a single WriteNodes call, or just make
//	    # a second transaction loop for the second transaction.
//	    break
//	  } else {
//	    # failure - retry from the top
//	  }
//	}
//
// Note that go.chromium.org/luci/turboci will provide a helper to manage
// transactions on the client side.
type TransactionDetails struct {
	state                      protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_NodesObserved   *[]*v1.Identifier      `protobuf:"bytes,1,rep,name=nodes_observed,json=nodesObserved,proto3"`
	xxx_hidden_SnapshotVersion *Revision              `protobuf:"bytes,2,opt,name=snapshot_version,json=snapshotVersion,proto3,oneof"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *TransactionDetails) Reset() {
	*x = TransactionDetails{}
	mi := &file_turboci_graph_orchestrator_v1_transaction_details_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionDetails) ProtoMessage() {}

func (x *TransactionDetails) ProtoReflect() protoreflect.Message {
	mi := &file_turboci_graph_orchestrator_v1_transaction_details_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TransactionDetails) GetNodesObserved() []*v1.Identifier {
	if x != nil {
		if x.xxx_hidden_NodesObserved != nil {
			return *x.xxx_hidden_NodesObserved
		}
	}
	return nil
}

func (x *TransactionDetails) GetSnapshotVersion() *Revision {
	if x != nil {
		return x.xxx_hidden_SnapshotVersion
	}
	return nil
}

func (x *TransactionDetails) SetNodesObserved(v []*v1.Identifier) {
	x.xxx_hidden_NodesObserved = &v
}

func (x *TransactionDetails) SetSnapshotVersion(v *Revision) {
	x.xxx_hidden_SnapshotVersion = v
}

func (x *TransactionDetails) HasSnapshotVersion() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_SnapshotVersion != nil
}

func (x *TransactionDetails) ClearSnapshotVersion() {
	x.xxx_hidden_SnapshotVersion = nil
}

type TransactionDetails_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// A list of all nodes observed which lead to this write.
	//
	// This SHOULD include all nodes which your computation used as inputs
	// for making a decision. If you locally filtered the WorkPlan before the
	// computation, it is OK to omit nodes which were filtered out, because you
	// would do the same write regardless of those filtered nodes' content.
	//
	// This MAY include nodes which were absent from the WorkPlan - this means
	// that the write is conditional on their absence (e.g. "I queried for X and
	// didn't find it, so I'm doing a write based on that information. If X DOES
	// exist at the time of the write, I want to abort and try again.").
	//
	// NOTE: If you are writing what you THINK are all new nodes, but haven't
	// done a query to verify this, just providing `txn` with `nodes_observed`
	// and `snapshot_version` left unset (zero) is sufficient to guard against
	// the nodes already being written.
	//
	// However, if you get a TransactionConflictFailure because the nodes already
	// exist, when you recover make sure to do the query before you try the write
	// again! You may be conflicting with a previous incarnation of your own
	// process!
	NodesObserved []*v1.Identifier
	// The 'version' of the WorkPlan returned from QueryNodes.
	//
	// If multiple queries were made in this transaction, this revision MUST be
	// the *first* revision observed. Providing version.require to QueryNodes
	// will help enforce this.
	//
	// If `snapshot_version` is unset, it is treated as a 0 value (which means
	// that all `nodes_observed` plus all nodes being written in this request
	// must not already exist).
	SnapshotVersion *Revision
}

func (b0 TransactionDetails_builder) Build() *TransactionDetails {
	m0 := &TransactionDetails{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_NodesObserved = &b.NodesObserved
	x.xxx_hidden_SnapshotVersion = b.SnapshotVersion
	return m0
}

var File_turboci_graph_orchestrator_v1_transaction_details_proto protoreflect.FileDescriptor

const file_turboci_graph_orchestrator_v1_transaction_details_proto_rawDesc = "" +
	"\n" +
	"7turboci/graph/orchestrator/v1/transaction_details.proto\x12\x1dturboci.graph.orchestrator.v1\x1a%turboci/graph/ids/v1/identifier.proto\x1a1turboci/graph/orchestrator/v1/field_options.proto\x1a,turboci/graph/orchestrator/v1/revision.proto\"\xda\x01\n" +
	"\x12TransactionDetails\x12V\n" +
	"\x0enodes_observed\x18\x01 \x03(\v2 .turboci.graph.ids.v1.IdentifierB\r\x82\x86\xf6\xfb\x0f\a\x12\x05\n" +
	"\x03\x02\b\tR\rnodesObserved\x12W\n" +
	"\x10snapshot_version\x18\x02 \x01(\v2'.turboci.graph.orchestrator.v1.RevisionH\x00R\x0fsnapshotVersion\x88\x01\x01B\x13\n" +
	"\x11_snapshot_versionBIP\x01ZEgo.chromium.org/turboci/proto/go/graph/orchestrator/v1;orchestratorpbb\x06proto3"

var file_turboci_graph_orchestrator_v1_transaction_details_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_turboci_graph_orchestrator_v1_transaction_details_proto_goTypes = []any{
	(*TransactionDetails)(nil), // 0: turboci.graph.orchestrator.v1.TransactionDetails
	(*v1.Identifier)(nil),      // 1: turboci.graph.ids.v1.Identifier
	(*Revision)(nil),           // 2: turboci.graph.orchestrator.v1.Revision
}
var file_turboci_graph_orchestrator_v1_transaction_details_proto_depIdxs = []int32{
	1, // 0: turboci.graph.orchestrator.v1.TransactionDetails.nodes_observed:type_name -> turboci.graph.ids.v1.Identifier
	2, // 1: turboci.graph.orchestrator.v1.TransactionDetails.snapshot_version:type_name -> turboci.graph.orchestrator.v1.Revision
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_turboci_graph_orchestrator_v1_transaction_details_proto_init() }
func file_turboci_graph_orchestrator_v1_transaction_details_proto_init() {
	if File_turboci_graph_orchestrator_v1_transaction_details_proto != nil {
		return
	}
	file_turboci_graph_orchestrator_v1_field_options_proto_init()
	file_turboci_graph_orchestrator_v1_revision_proto_init()
	file_turboci_graph_orchestrator_v1_transaction_details_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_turboci_graph_orchestrator_v1_transaction_details_proto_rawDesc), len(file_turboci_graph_orchestrator_v1_transaction_details_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_turboci_graph_orchestrator_v1_transaction_details_proto_goTypes,
		DependencyIndexes: file_turboci_graph_orchestrator_v1_transaction_details_proto_depIdxs,
		MessageInfos:      file_turboci_graph_orchestrator_v1_transaction_details_proto_msgTypes,
	}.Build()
	File_turboci_graph_orchestrator_v1_transaction_details_proto = out.File
	file_turboci_graph_orchestrator_v1_transaction_details_proto_goTypes = nil
	file_turboci_graph_orchestrator_v1_transaction_details_proto_depIdxs = nil
}
