// Copyright 2025 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: turboci/graph/orchestrator/v1/transaction_invariant.proto

package orchestratorpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TransactionConflictFailure is a gRPC error detail message returned by QueryNodes
// and WriteNodes.
//
// If your client receives an rpc status with this message in it, it means that
// the client needs to retry its transaction from the beginning.
type TransactionConflictFailure struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionConflictFailure) Reset() {
	*x = TransactionConflictFailure{}
	mi := &file_turboci_graph_orchestrator_v1_transaction_invariant_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionConflictFailure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionConflictFailure) ProtoMessage() {}

func (x *TransactionConflictFailure) ProtoReflect() protoreflect.Message {
	mi := &file_turboci_graph_orchestrator_v1_transaction_invariant_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionConflictFailure.ProtoReflect.Descriptor instead.
func (*TransactionConflictFailure) Descriptor() ([]byte, []int) {
	return file_turboci_graph_orchestrator_v1_transaction_invariant_proto_rawDescGZIP(), []int{0}
}

var File_turboci_graph_orchestrator_v1_transaction_invariant_proto protoreflect.FileDescriptor

const file_turboci_graph_orchestrator_v1_transaction_invariant_proto_rawDesc = "" +
	"\n" +
	"9turboci/graph/orchestrator/v1/transaction_invariant.proto\x12\x1dturboci.graph.orchestrator.v1\"\x1c\n" +
	"\x1aTransactionConflictFailureBIP\x01ZEgo.chromium.org/turboci/proto/go/graph/orchestrator/v1;orchestratorpbb\beditionsp\xe8\a"

var (
	file_turboci_graph_orchestrator_v1_transaction_invariant_proto_rawDescOnce sync.Once
	file_turboci_graph_orchestrator_v1_transaction_invariant_proto_rawDescData []byte
)

func file_turboci_graph_orchestrator_v1_transaction_invariant_proto_rawDescGZIP() []byte {
	file_turboci_graph_orchestrator_v1_transaction_invariant_proto_rawDescOnce.Do(func() {
		file_turboci_graph_orchestrator_v1_transaction_invariant_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_turboci_graph_orchestrator_v1_transaction_invariant_proto_rawDesc), len(file_turboci_graph_orchestrator_v1_transaction_invariant_proto_rawDesc)))
	})
	return file_turboci_graph_orchestrator_v1_transaction_invariant_proto_rawDescData
}

var file_turboci_graph_orchestrator_v1_transaction_invariant_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_turboci_graph_orchestrator_v1_transaction_invariant_proto_goTypes = []any{
	(*TransactionConflictFailure)(nil), // 0: turboci.graph.orchestrator.v1.TransactionConflictFailure
}
var file_turboci_graph_orchestrator_v1_transaction_invariant_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_turboci_graph_orchestrator_v1_transaction_invariant_proto_init() }
func file_turboci_graph_orchestrator_v1_transaction_invariant_proto_init() {
	if File_turboci_graph_orchestrator_v1_transaction_invariant_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_turboci_graph_orchestrator_v1_transaction_invariant_proto_rawDesc), len(file_turboci_graph_orchestrator_v1_transaction_invariant_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_turboci_graph_orchestrator_v1_transaction_invariant_proto_goTypes,
		DependencyIndexes: file_turboci_graph_orchestrator_v1_transaction_invariant_proto_depIdxs,
		MessageInfos:      file_turboci_graph_orchestrator_v1_transaction_invariant_proto_msgTypes,
	}.Build()
	File_turboci_graph_orchestrator_v1_transaction_invariant_proto = out.File
	file_turboci_graph_orchestrator_v1_transaction_invariant_proto_goTypes = nil
	file_turboci_graph_orchestrator_v1_transaction_invariant_proto_depIdxs = nil
}
