// Copyright 2026 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: turboci/graph/orchestrator/v1/value_digest.proto

package orchestratorpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ValueHashAlgo identifies the type of hash used for a particular ValueRef.
//
// The server may only implement a subset of these.
type ValueHashAlgo int32

const (
	// Unknown, invalid, hash algorithm.
	ValueHashAlgo_VALUE_HASH_ALGO_UNKNOWN ValueHashAlgo = 0
	// SHA256(Any())
	//
	// The Any is serialized the same way that the Bazel Remote Build API defines
	// hashing protos, namely:
	//
	// * Fields are serialized in tag order.
	// * There are no unknown fields.
	// * There are no duplicate fields.
	// * Fields are serialized according to the default semantics for their type.
	//
	// Specifically, this means that this is computed as:
	//
	//	SHA256(protoTag(1, bytes) || type_url || protoTag(2, bytes) || value)
	//
	// Which is the *typical* encoding of a `google.protobuf.Any` using standard
	// serializers.
	//
	// len(hash) = 32
	ValueHashAlgo_VALUE_HASH_ALGO_SHA256 ValueHashAlgo = 1
)

// Enum value maps for ValueHashAlgo.
var (
	ValueHashAlgo_name = map[int32]string{
		0: "VALUE_HASH_ALGO_UNKNOWN",
		1: "VALUE_HASH_ALGO_SHA256",
	}
	ValueHashAlgo_value = map[string]int32{
		"VALUE_HASH_ALGO_UNKNOWN": 0,
		"VALUE_HASH_ALGO_SHA256":  1,
	}
)

func (x ValueHashAlgo) Enum() *ValueHashAlgo {
	p := new(ValueHashAlgo)
	*p = x
	return p
}

func (x ValueHashAlgo) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ValueHashAlgo) Descriptor() protoreflect.EnumDescriptor {
	return file_turboci_graph_orchestrator_v1_value_digest_proto_enumTypes[0].Descriptor()
}

func (ValueHashAlgo) Type() protoreflect.EnumType {
	return &file_turboci_graph_orchestrator_v1_value_digest_proto_enumTypes[0]
}

func (x ValueHashAlgo) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// ValueDigest is the de-serialized form of a ValueRef.digest.
//
// The TurboCI API always uses these in their serialized (URL safe string)
// form, not as protos - however this message is included because it is
// occasionally useful to extract the raw hash and/or size of the original
// hashed data.
//
// Serialized as:
//
//	BASE64_URLSAFE(hash || varint(size_bytes) || byte(algo))
//
// And de-serialized as:
//
//	rawDecoded = BASE64_URLSAFE_dec(encoded)
//	algo = ALGOS[rawDecoded[-1]]
//	rawHash = rawDecoded[algo.len]
//	size = varintDecode(rawDecoded[algo.len:-1])
//
// This puts `hash` at the front, rather than `algo`, in order to help uses of
// the ValueDigest as a primary key to avoid hotspotting. For the same reason,
// the algo is always put at the end because it will have the lowest entropy
// (almost certainly will always be the value '1').
type ValueDigest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Hash        []byte                 `protobuf:"bytes,1,opt,name=hash,proto3,oneof"`
	xxx_hidden_SizeBytes   int64                  `protobuf:"varint,2,opt,name=size_bytes,json=sizeBytes,proto3,oneof"`
	xxx_hidden_Algo        ValueHashAlgo          `protobuf:"varint,3,opt,name=algo,proto3,enum=turboci.graph.orchestrator.v1.ValueHashAlgo,oneof"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ValueDigest) Reset() {
	*x = ValueDigest{}
	mi := &file_turboci_graph_orchestrator_v1_value_digest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValueDigest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValueDigest) ProtoMessage() {}

func (x *ValueDigest) ProtoReflect() protoreflect.Message {
	mi := &file_turboci_graph_orchestrator_v1_value_digest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ValueDigest) GetHash() []byte {
	if x != nil {
		return x.xxx_hidden_Hash
	}
	return nil
}

func (x *ValueDigest) GetSizeBytes() int64 {
	if x != nil {
		return x.xxx_hidden_SizeBytes
	}
	return 0
}

func (x *ValueDigest) GetAlgo() ValueHashAlgo {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 2) {
			return x.xxx_hidden_Algo
		}
	}
	return ValueHashAlgo_VALUE_HASH_ALGO_UNKNOWN
}

func (x *ValueDigest) SetHash(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Hash = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *ValueDigest) SetSizeBytes(v int64) {
	x.xxx_hidden_SizeBytes = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *ValueDigest) SetAlgo(v ValueHashAlgo) {
	x.xxx_hidden_Algo = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *ValueDigest) HasHash() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ValueDigest) HasSizeBytes() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ValueDigest) HasAlgo() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *ValueDigest) ClearHash() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Hash = nil
}

func (x *ValueDigest) ClearSizeBytes() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_SizeBytes = 0
}

func (x *ValueDigest) ClearAlgo() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Algo = ValueHashAlgo_VALUE_HASH_ALGO_UNKNOWN
}

type ValueDigest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Required. The raw bytes of the hash.
	Hash []byte
	// Required. The size of the hashed data in bytes.
	SizeBytes *int64
	// Required. The algorithm used to compute `hash`.
	Algo *ValueHashAlgo
}

func (b0 ValueDigest_builder) Build() *ValueDigest {
	m0 := &ValueDigest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Hash != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_Hash = b.Hash
	}
	if b.SizeBytes != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_SizeBytes = *b.SizeBytes
	}
	if b.Algo != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_Algo = *b.Algo
	}
	return m0
}

var File_turboci_graph_orchestrator_v1_value_digest_proto protoreflect.FileDescriptor

const file_turboci_graph_orchestrator_v1_value_digest_proto_rawDesc = "" +
	"\n" +
	"0turboci/graph/orchestrator/v1/value_digest.proto\x12\x1dturboci.graph.orchestrator.v1\"\xb2\x01\n" +
	"\vValueDigest\x12\x17\n" +
	"\x04hash\x18\x01 \x01(\fH\x00R\x04hash\x88\x01\x01\x12\"\n" +
	"\n" +
	"size_bytes\x18\x02 \x01(\x03H\x01R\tsizeBytes\x88\x01\x01\x12E\n" +
	"\x04algo\x18\x03 \x01(\x0e2,.turboci.graph.orchestrator.v1.ValueHashAlgoH\x02R\x04algo\x88\x01\x01B\a\n" +
	"\x05_hashB\r\n" +
	"\v_size_bytesB\a\n" +
	"\x05_algo*H\n" +
	"\rValueHashAlgo\x12\x1b\n" +
	"\x17VALUE_HASH_ALGO_UNKNOWN\x10\x00\x12\x1a\n" +
	"\x16VALUE_HASH_ALGO_SHA256\x10\x01BIP\x01ZEgo.chromium.org/turboci/proto/go/graph/orchestrator/v1;orchestratorpbb\x06proto3"

var file_turboci_graph_orchestrator_v1_value_digest_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_turboci_graph_orchestrator_v1_value_digest_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_turboci_graph_orchestrator_v1_value_digest_proto_goTypes = []any{
	(ValueHashAlgo)(0),  // 0: turboci.graph.orchestrator.v1.ValueHashAlgo
	(*ValueDigest)(nil), // 1: turboci.graph.orchestrator.v1.ValueDigest
}
var file_turboci_graph_orchestrator_v1_value_digest_proto_depIdxs = []int32{
	0, // 0: turboci.graph.orchestrator.v1.ValueDigest.algo:type_name -> turboci.graph.orchestrator.v1.ValueHashAlgo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_turboci_graph_orchestrator_v1_value_digest_proto_init() }
func file_turboci_graph_orchestrator_v1_value_digest_proto_init() {
	if File_turboci_graph_orchestrator_v1_value_digest_proto != nil {
		return
	}
	file_turboci_graph_orchestrator_v1_value_digest_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_turboci_graph_orchestrator_v1_value_digest_proto_rawDesc), len(file_turboci_graph_orchestrator_v1_value_digest_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_turboci_graph_orchestrator_v1_value_digest_proto_goTypes,
		DependencyIndexes: file_turboci_graph_orchestrator_v1_value_digest_proto_depIdxs,
		EnumInfos:         file_turboci_graph_orchestrator_v1_value_digest_proto_enumTypes,
		MessageInfos:      file_turboci_graph_orchestrator_v1_value_digest_proto_msgTypes,
	}.Build()
	File_turboci_graph_orchestrator_v1_value_digest_proto = out.File
	file_turboci_graph_orchestrator_v1_value_digest_proto_goTypes = nil
	file_turboci_graph_orchestrator_v1_value_digest_proto_depIdxs = nil
}
