// Copyright 2025 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: turboci/data/common/v1/display_message.proto

package commonpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Different types of message formatting.
type DisplayMessage_MessageFormat int32

const (
	// Default message format.
	DisplayMessage_MESSAGE_FORMAT_UNKNOWN DisplayMessage_MessageFormat = 0
	// Plain text - no special formatting.
	DisplayMessage_MESSAGE_FORMAT_PLAIN_TEXT DisplayMessage_MessageFormat = 1
	// HTML markup.
	DisplayMessage_MESSAGE_FORMAT_HTML DisplayMessage_MessageFormat = 2
	// Markdown formatting.
	DisplayMessage_MESSAGE_FORMAT_MARKDOWN DisplayMessage_MessageFormat = 3
	// Includes ANSI escape codes for controlling things like text color.
	DisplayMessage_MESSAGE_FORMAT_ANSI DisplayMessage_MessageFormat = 4
)

// Enum value maps for DisplayMessage_MessageFormat.
var (
	DisplayMessage_MessageFormat_name = map[int32]string{
		0: "MESSAGE_FORMAT_UNKNOWN",
		1: "MESSAGE_FORMAT_PLAIN_TEXT",
		2: "MESSAGE_FORMAT_HTML",
		3: "MESSAGE_FORMAT_MARKDOWN",
		4: "MESSAGE_FORMAT_ANSI",
	}
	DisplayMessage_MessageFormat_value = map[string]int32{
		"MESSAGE_FORMAT_UNKNOWN":    0,
		"MESSAGE_FORMAT_PLAIN_TEXT": 1,
		"MESSAGE_FORMAT_HTML":       2,
		"MESSAGE_FORMAT_MARKDOWN":   3,
		"MESSAGE_FORMAT_ANSI":       4,
	}
)

func (x DisplayMessage_MessageFormat) Enum() *DisplayMessage_MessageFormat {
	p := new(DisplayMessage_MessageFormat)
	*p = x
	return p
}

func (x DisplayMessage_MessageFormat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DisplayMessage_MessageFormat) Descriptor() protoreflect.EnumDescriptor {
	return file_turboci_data_common_v1_display_message_proto_enumTypes[0].Descriptor()
}

func (DisplayMessage_MessageFormat) Type() protoreflect.EnumType {
	return &file_turboci_data_common_v1_display_message_proto_enumTypes[0]
}

func (x DisplayMessage_MessageFormat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// A message string and a format-type enum to instruct clients how to render the text.
type DisplayMessage struct {
	state                    protoimpl.MessageState       `protogen:"opaque.v1"`
	xxx_hidden_Message       *string                      `protobuf:"bytes,1,opt,name=message,proto3,oneof"`
	xxx_hidden_MessageFormat DisplayMessage_MessageFormat `protobuf:"varint,2,opt,name=message_format,json=messageFormat,proto3,enum=turboci.data.common.v1.DisplayMessage_MessageFormat,oneof"`
	XXX_raceDetectHookData   protoimpl.RaceDetectHookData
	XXX_presence             [1]uint32
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *DisplayMessage) Reset() {
	*x = DisplayMessage{}
	mi := &file_turboci_data_common_v1_display_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisplayMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisplayMessage) ProtoMessage() {}

func (x *DisplayMessage) ProtoReflect() protoreflect.Message {
	mi := &file_turboci_data_common_v1_display_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DisplayMessage) GetMessage() string {
	if x != nil {
		if x.xxx_hidden_Message != nil {
			return *x.xxx_hidden_Message
		}
		return ""
	}
	return ""
}

func (x *DisplayMessage) GetMessageFormat() DisplayMessage_MessageFormat {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 1) {
			return x.xxx_hidden_MessageFormat
		}
	}
	return DisplayMessage_MESSAGE_FORMAT_UNKNOWN
}

func (x *DisplayMessage) SetMessage(v string) {
	x.xxx_hidden_Message = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *DisplayMessage) SetMessageFormat(v DisplayMessage_MessageFormat) {
	x.xxx_hidden_MessageFormat = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *DisplayMessage) HasMessage() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *DisplayMessage) HasMessageFormat() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *DisplayMessage) ClearMessage() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Message = nil
}

func (x *DisplayMessage) ClearMessageFormat() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_MessageFormat = DisplayMessage_MESSAGE_FORMAT_UNKNOWN
}

type DisplayMessage_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The message string.
	Message *string
	// How the message string should be formatted.
	MessageFormat *DisplayMessage_MessageFormat
}

func (b0 DisplayMessage_builder) Build() *DisplayMessage {
	m0 := &DisplayMessage{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Message != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Message = b.Message
	}
	if b.MessageFormat != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_MessageFormat = *b.MessageFormat
	}
	return m0
}

var File_turboci_data_common_v1_display_message_proto protoreflect.FileDescriptor

const file_turboci_data_common_v1_display_message_proto_rawDesc = "" +
	"\n" +
	",turboci/data/common/v1/display_message.proto\x12\x16turboci.data.common.v1\"\xcc\x02\n" +
	"\x0eDisplayMessage\x12\x1d\n" +
	"\amessage\x18\x01 \x01(\tH\x00R\amessage\x88\x01\x01\x12`\n" +
	"\x0emessage_format\x18\x02 \x01(\x0e24.turboci.data.common.v1.DisplayMessage.MessageFormatH\x01R\rmessageFormat\x88\x01\x01\"\x99\x01\n" +
	"\rMessageFormat\x12\x1a\n" +
	"\x16MESSAGE_FORMAT_UNKNOWN\x10\x00\x12\x1d\n" +
	"\x19MESSAGE_FORMAT_PLAIN_TEXT\x10\x01\x12\x17\n" +
	"\x13MESSAGE_FORMAT_HTML\x10\x02\x12\x1b\n" +
	"\x17MESSAGE_FORMAT_MARKDOWN\x10\x03\x12\x17\n" +
	"\x13MESSAGE_FORMAT_ANSI\x10\x04B\n" +
	"\n" +
	"\b_messageB\x11\n" +
	"\x0f_message_formatB<P\x01Z8go.chromium.org/turboci/proto/go/data/common/v1;commonpbb\x06proto3"

var file_turboci_data_common_v1_display_message_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_turboci_data_common_v1_display_message_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_turboci_data_common_v1_display_message_proto_goTypes = []any{
	(DisplayMessage_MessageFormat)(0), // 0: turboci.data.common.v1.DisplayMessage.MessageFormat
	(*DisplayMessage)(nil),            // 1: turboci.data.common.v1.DisplayMessage
}
var file_turboci_data_common_v1_display_message_proto_depIdxs = []int32{
	0, // 0: turboci.data.common.v1.DisplayMessage.message_format:type_name -> turboci.data.common.v1.DisplayMessage.MessageFormat
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_turboci_data_common_v1_display_message_proto_init() }
func file_turboci_data_common_v1_display_message_proto_init() {
	if File_turboci_data_common_v1_display_message_proto != nil {
		return
	}
	file_turboci_data_common_v1_display_message_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_turboci_data_common_v1_display_message_proto_rawDesc), len(file_turboci_data_common_v1_display_message_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_turboci_data_common_v1_display_message_proto_goTypes,
		DependencyIndexes: file_turboci_data_common_v1_display_message_proto_depIdxs,
		EnumInfos:         file_turboci_data_common_v1_display_message_proto_enumTypes,
		MessageInfos:      file_turboci_data_common_v1_display_message_proto_msgTypes,
	}.Build()
	File_turboci_data_common_v1_display_message_proto = out.File
	file_turboci_data_common_v1_display_message_proto_goTypes = nil
	file_turboci_data_common_v1_display_message_proto_depIdxs = nil
}
